In [107]:
# Load the NLTK package
import nltk
#'*' shows downloading is going on jupyter

In [108]:
# Download aLl NLTK resources
nltk.download('all')
# took around 5 min to dowload 
# nltk.download('punkt')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package english_wordnet is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package mock_corpus to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mock_corpus is already up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package omw-2.0 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-2.0 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     C:\Users\bhavi\AppData\Roaming\nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!

True

In [109]:
### text corpus ###

# Example:
## Load the Brown Corpus: American English texts of varying genres
from nltk.corpus import brown

In [110]:
# categories in the corpus
# using categories method
brown.categories()

['adventure',
 'belles_lettres',
 'editorial',
 'fiction',
 'government',
 'hobbies',
 'humor',
 'learned',
 'lore',
 'mystery',
 'news',
 'religion',
 'reviews',
 'romance',
 'science_fiction']

In [111]:
# first 5 sentences
# using sents method to read sentences from the corpus
# a list of lists of strings is returned
sents = brown.sents()
sents[0:5]

[['The',
  'Fulton',
  'County',
  'Grand',
  'Jury',
  'said',
  'Friday',
  'an',
  'investigation',
  'of',
  "Atlanta's",
  'recent',
  'primary',
  'election',
  'produced',
  '``',
  'no',
  'evidence',
  "''",
  'that',
  'any',
  'irregularities',
  'took',
  'place',
  '.'],
 ['The',
  'jury',
  'further',
  'said',
  'in',
  'term-end',
  'presentments',
  'that',
  'the',
  'City',
  'Executive',
  'Committee',
  ',',
  'which',
  'had',
  'over-all',
  'charge',
  'of',
  'the',
  'election',
  ',',
  '``',
  'deserves',
  'the',
  'praise',
  'and',
  'thanks',
  'of',
  'the',
  'City',
  'of',
  'Atlanta',
  "''",
  'for',
  'the',
  'manner',
  'in',
  'which',
  'the',
  'election',
  'was',
  'conducted',
  '.'],
 ['The',
  'September-October',
  'term',
  'jury',
  'had',
  'been',
  'charged',
  'by',
  'Fulton',
  'Superior',
  'Court',
  'Judge',
  'Durwood',
  'Pye',
  'to',
  'investigate',
  'reports',
  'of',
  'possible',
  '``',
  'irregularities',
  "''",
  'in',
  'the',
  'hard-fought',
  'primary',
  'which',
  'was',
  'won',
  'by',
  'Mayor-nominate',
  'Ivan',
  'Allen',
  'Jr.',
  '.'],
 ['``',
  'Only',
  'a',
  'relative',
  'handful',
  'of',
  'such',
  'reports',
  'was',
  'received',
  "''",
  ',',
  'the',
  'jury',
  'said',
  ',',
  '``',
  'considering',
  'the',
  'widespread',
  'interest',
  'in',
  'the',
  'election',
  ',',
  'the',
  'number',
  'of',
  'voters',
  'and',
  'the',
  'size',
  'of',
  'this',
  'city',
  "''",
  '.'],
 ['The',
  'jury',
  'said',
  'it',
  'did',
  'find',
  'that',
  'many',
  'of',
  "Georgia's",
  'registration',
  'and',
  'election',
  'laws',
  '``',
  'are',
  'outmoded',
  'or',
  'inadequate',
  'and',
  'often',
  'ambiguous',
  "''",
  '.']]

In [112]:
# using join method to concatenate strings
sents = [' '.join(words) for words in sents]
sents[0:5]

["The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .",
 "The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .",
 "The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .",
 "`` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .",
 "The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' ."]

In [113]:
# from a particular category
# using categories argument
sents1 = brown.sents(categories=['government'])
sents1 = [' '.join(words) for words in sents1]
sents1[0:5]

['The Office of Business Economics ( OBE ) of the U.S. Department of Commerce provides basic measures of the national economy and current analysis of short-run changes in the economic situation and business outlook .',
 'It develops and analyzes the national income , balance of international payments , and many other business indicators .',
 'Such measures are essential to its job of presenting business and Government with the facts required to meet the objective of expanding business and improving the operation of the economy .',
 'Contact',
 'For further information contact Director , Office of Business Economics , U.S. Department of Commerce , Washington 25 , D.C. .']

In [114]:
# fileids in the corpus
# using fileids method
brown.fileids()

['ca01',
 'ca02',
 'ca03',
 'ca04',
 'ca05',
 'ca06',
 'ca07',
 'ca08',
 'ca09',
 'ca10',
 'ca11',
 'ca12',
 'ca13',
 'ca14',
 'ca15',
 'ca16',
 'ca17',
 'ca18',
 'ca19',
 'ca20',
 'ca21',
 'ca22',
 'ca23',
 'ca24',
 'ca25',
 'ca26',
 'ca27',
 'ca28',
 'ca29',
 'ca30',
 'ca31',
 'ca32',
 'ca33',
 'ca34',
 'ca35',
 'ca36',
 'ca37',
 'ca38',
 'ca39',
 'ca40',
 'ca41',
 'ca42',
 'ca43',
 'ca44',
 'cb01',
 'cb02',
 'cb03',
 'cb04',
 'cb05',
 'cb06',
 'cb07',
 'cb08',
 'cb09',
 'cb10',
 'cb11',
 'cb12',
 'cb13',
 'cb14',
 'cb15',
 'cb16',
 'cb17',
 'cb18',
 'cb19',
 'cb20',
 'cb21',
 'cb22',
 'cb23',
 'cb24',
 'cb25',
 'cb26',
 'cb27',
 'cc01',
 'cc02',
 'cc03',
 'cc04',
 'cc05',
 'cc06',
 'cc07',
 'cc08',
 'cc09',
 'cc10',
 'cc11',
 'cc12',
 'cc13',
 'cc14',
 'cc15',
 'cc16',
 'cc17',
 'cd01',
 'cd02',
 'cd03',
 'cd04',
 'cd05',
 'cd06',
 'cd07',
 'cd08',
 'cd09',
 'cd10',
 'cd11',
 'cd12',
 'cd13',
 'cd14',
 'cd15',
 'cd16',
 'cd17',
 'ce01',
 'ce02',
 'ce03',
 'ce04',
 'ce05',
 'ce06',
 'ce07',
 'ce08',
 'ce09',
 'ce10',
 'ce11',
 'ce12',
 'ce13',
 'ce14',
 'ce15',
 'ce16',
 'ce17',
 'ce18',
 'ce19',
 'ce20',
 'ce21',
 'ce22',
 'ce23',
 'ce24',
 'ce25',
 'ce26',
 'ce27',
 'ce28',
 'ce29',
 'ce30',
 'ce31',
 'ce32',
 'ce33',
 'ce34',
 'ce35',
 'ce36',
 'cf01',
 'cf02',
 'cf03',
 'cf04',
 'cf05',
 'cf06',
 'cf07',
 'cf08',
 'cf09',
 'cf10',
 'cf11',
 'cf12',
 'cf13',
 'cf14',
 'cf15',
 'cf16',
 'cf17',
 'cf18',
 'cf19',
 'cf20',
 'cf21',
 'cf22',
 'cf23',
 'cf24',
 'cf25',
 'cf26',
 'cf27',
 'cf28',
 'cf29',
 'cf30',
 'cf31',
 'cf32',
 'cf33',
 'cf34',
 'cf35',
 'cf36',
 'cf37',
 'cf38',
 'cf39',
 'cf40',
 'cf41',
 'cf42',
 'cf43',
 'cf44',
 'cf45',
 'cf46',
 'cf47',
 'cf48',
 'cg01',
 'cg02',
 'cg03',
 'cg04',
 'cg05',
 'cg06',
 'cg07',
 'cg08',
 'cg09',
 'cg10',
 'cg11',
 'cg12',
 'cg13',
 'cg14',
 'cg15',
 'cg16',
 'cg17',
 'cg18',
 'cg19',
 'cg20',
 'cg21',
 'cg22',
 'cg23',
 'cg24',
 'cg25',
 'cg26',
 'cg27',
 'cg28',
 'cg29',
 'cg30',
 'cg31',
 'cg32',
 'cg33',
 'cg34',
 'cg35',
 'cg36',
 'cg37',
 'cg38',
 'cg39',
 'cg40',
 'cg41',
 'cg42',
 'cg43',
 'cg44',
 'cg45',
 'cg46',
 'cg47',
 'cg48',
 'cg49',
 'cg50',
 'cg51',
 'cg52',
 'cg53',
 'cg54',
 'cg55',
 'cg56',
 'cg57',
 'cg58',
 'cg59',
 'cg60',
 'cg61',
 'cg62',
 'cg63',
 'cg64',
 'cg65',
 'cg66',
 'cg67',
 'cg68',
 'cg69',
 'cg70',
 'cg71',
 'cg72',
 'cg73',
 'cg74',
 'cg75',
 'ch01',
 'ch02',
 'ch03',
 'ch04',
 'ch05',
 'ch06',
 'ch07',
 'ch08',
 'ch09',
 'ch10',
 'ch11',
 'ch12',
 'ch13',
 'ch14',
 'ch15',
 'ch16',
 'ch17',
 'ch18',
 'ch19',
 'ch20',
 'ch21',
 'ch22',
 'ch23',
 'ch24',
 'ch25',
 'ch26',
 'ch27',
 'ch28',
 'ch29',
 'ch30',
 'cj01',
 'cj02',
 'cj03',
 'cj04',
 'cj05',
 'cj06',
 'cj07',
 'cj08',
 'cj09',
 'cj10',
 'cj11',
 'cj12',
 'cj13',
 'cj14',
 'cj15',
 'cj16',
 'cj17',
 'cj18',
 'cj19',
 'cj20',
 'cj21',
 'cj22',
 'cj23',
 'cj24',
 'cj25',
 'cj26',
 'cj27',
 'cj28',
 'cj29',
 'cj30',
 'cj31',
 'cj32',
 'cj33',
 'cj34',
 'cj35',
 'cj36',
 'cj37',
 'cj38',
 'cj39',
 'cj40',
 'cj41',
 'cj42',
 'cj43',
 'cj44',
 'cj45',
 'cj46',
 'cj47',
 'cj48',
 'cj49',
 'cj50',
 'cj51',
 'cj52',
 'cj53',
 'cj54',
 'cj55',
 'cj56',
 'cj57',
 'cj58',
 'cj59',
 'cj60',
 'cj61',
 'cj62',
 'cj63',
 'cj64',
 'cj65',
 'cj66',
 'cj67',
 'cj68',
 'cj69',
 'cj70',
 'cj71',
 'cj72',
 'cj73',
 'cj74',
 'cj75',
 'cj76',
 'cj77',
 'cj78',
 'cj79',
 'cj80',
 'ck01',
 'ck02',
 'ck03',
 'ck04',
 'ck05',
 'ck06',
 'ck07',
 'ck08',
 'ck09',
 'ck10',
 'ck11',
 'ck12',
 'ck13',
 'ck14',
 'ck15',
 'ck16',
 'ck17',
 'ck18',
 'ck19',
 'ck20',
 'ck21',
 'ck22',
 'ck23',
 'ck24',
 'ck25',
 'ck26',
 'ck27',
 'ck28',
 'ck29',
 'cl01',
 'cl02',
 'cl03',
 'cl04',
 'cl05',
 'cl06',
 'cl07',
 'cl08',
 'cl09',
 'cl10',
 'cl11',
 'cl12',
 'cl13',
 'cl14',
 'cl15',
 'cl16',
 'cl17',
 'cl18',
 'cl19',
 'cl20',
 'cl21',
 'cl22',
 'cl23',
 'cl24',
 'cm01',
 'cm02',
 'cm03',
 'cm04',
 'cm05',
 'cm06',
 'cn01',
 'cn02',
 'cn03',
 'cn04',
 'cn05',
 'cn06',
 'cn07',
 'cn08',
 'cn09',
 'cn10',
 'cn11',
 'cn12',
 'cn13',
 'cn14',
 'cn15',
 'cn16',
 'cn17',
 'cn18',
 'cn19',
 'cn20',
 'cn21',
 'cn22',
 'cn23',
 'cn24',
 'cn25',
 'cn26',
 'cn27',
 'cn28',
 'cn29',
 'cp01',
 'cp02',
 'cp03',
 'cp04',
 'cp05',
 'cp06',
 'cp07',
 'cp08',
 'cp09',
 'cp10',
 'cp11',
 'cp12',
 'cp13',
 'cp14',
 'cp15',
 'cp16',
 'cp17',
 'cp18',
 'cp19',
 'cp20',
 'cp21',
 'cp22',
 'cp23',
 'cp24',
 'cp25',
 'cp26',
 'cp27',
 'cp28',
 'cp29',
 'cr01',
 'cr02',
 'cr03',
 'cr04',
 'cr05',
 'cr06',
 'cr07',
 'cr08',
 'cr09']

In [115]:
# fileids in the humor category
brown.fileids(categories=['humor'])

['cr01', 'cr02', 'cr03', 'cr04', 'cr05', 'cr06', 'cr07', 'cr08', 'cr09']

In [116]:
# from a particular file
# using fileids argument
sents2 = brown.sents(fileids=['ca18'])
sents2 = [' '.join(words) for words in sents2]
sents2[0:5]

["`` A Night in New Orleans '' is the gayety planned by members of the Thrift Shop Committee for May 6 at Philmont Country Club .",
 "The women have a reputation for giving parties that are different and are fun and this year's promises to follow in this fine tradition .",
 'Mrs. H. J. Grinsfelder is chairman .',
 "The Louisiana city is known , of course , for its fine food , good music and its colorful hospitality `` and , when guests arrive at Philmont that night '' , says Mrs. Grinsfelder , `` that is exactly what we expect to offer them .",
 "We've been working for weeks ."]

In [117]:
## Text Collection & Transformation Part II

In [118]:
## Load the Gutenberg Corpus
from nltk.corpus import gutenberg

In [119]:
# fileids in the corpus
gutenberg.fileids()

['austen-emma.txt',
 'austen-persuasion.txt',
 'austen-sense.txt',
 'bible-kjv.txt',
 'blake-poems.txt',
 'bryant-stories.txt',
 'burgess-busterbrown.txt',
 'carroll-alice.txt',
 'chesterton-ball.txt',
 'chesterton-brown.txt',
 'chesterton-thursday.txt',
 'edgeworth-parents.txt',
 'melville-moby_dick.txt',
 'milton-paradise.txt',
 'shakespeare-caesar.txt',
 'shakespeare-hamlet.txt',
 'shakespeare-macbeth.txt',
 'whitman-leaves.txt']

In [120]:
# using raw method
# returns a single string for the file
emma = gutenberg.raw(fileids='austen-emma.txt')

In [121]:
# total no. of characters in emma
len(emma)

887071

In [122]:
# first 200 characters in the corpus
emma[0:200]

'[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; an'

In [123]:
print(emma[0:200])

[Emma by Jane Austen 1816]

VOLUME I

CHAPTER I


Emma Woodhouse, handsome, clever, and rich, with a comfortable home
and happy disposition, seemed to unite some of the best blessings
of existence; an

In [124]:
## sentence tokenization ##
# using different NLTK interfaces

# First approach:
# using sent_tokenize function to perform tokenization
# default and recommended sentence tokenizer
# pre-trained on several Language models and works really well on many popular Languages besides English

emma_sents = nltk.sent_tokenize(emma)

In [125]:
# no. of sentences
len(emma_sents)

7493

In [126]:
# first 5 sentences
emma_sents[0:5] # output1

# Note: tokenizer doesn't just use periods to delimit sentences
# It also considers other punctuation and the capitalization of words

['[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; and had lived nearly twenty-one years in the world\nwith very little to distress or vex her.',
 "She was the youngest of the two daughters of a most affectionate,\nindulgent father; and had, in consequence of her sister's marriage,\nbeen mistress of his house from a very early period.",
 'Her mother\nhad died too long ago for her to have more than an indistinct\nremembrance of her caresses; and her place had been supplied\nby an excellent woman as governess, who had fallen little short\nof a mother in affection.',
 "Sixteen years had Miss Taylor been in Mr. Woodhouse's family,\nless as a governess than a friend, very fond of both daughters,\nbut particularly of Emma.",
 'Between _them_ it was more the intimacy\nof sisters.']

In [127]:
# Second approach:
# using the default PunktSentenceTokenizer class to perform tokenization
# sent_tokenize function is also an instance of the PunktSentenceTokenizer class

punkt_st = nltk.tokenize.PunktSentenceTokenizer()

In [128]:
# using tokenize method
emma_sents2 = punkt_st.tokenize(emma)

In [129]:
emma_sents2[0:5] # similar to output1

['[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; and had lived nearly twenty-one years in the world\nwith very little to distress or vex her.',
 "She was the youngest of the two daughters of a most affectionate,\nindulgent father; and had, in consequence of her sister's marriage,\nbeen mistress of his house from a very early period.",
 'Her mother\nhad died too long ago for her to have more than an indistinct\nremembrance of her caresses; and her place had been supplied\nby an excellent woman as governess, who had fallen little short\nof a mother in affection.',
 'Sixteen years had Miss Taylor been in Mr.',
 "Woodhouse's family,\nless as a governess than a friend, very fond of both daughters,\nbut particularly of Emma."]

In [130]:
# Third approach:
# using an instance of the RegexpTokenizer class

# specific regular expression-based patterns are used
pattern1 = r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<![A-Z]\.)(?<=\.|\?|\!)\s'

In [131]:
# regex pattern for building the tokenizer
# the gaps parameter: if True, used to find the gaps between the tokens
# using RegexpTokenizer function
regex_st = nltk.tokenize.RegexpTokenizer(pattern=pattern1, gaps=True)

In [132]:
# using tokenize method
emma_sents3 = regex_st.tokenize(emma)

In [133]:
emma_sents3[0:5] # similar to output1

['[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; and had lived nearly twenty-one years in the world\nwith very little to distress or vex her.',
 "\nShe was the youngest of the two daughters of a most affectionate,\nindulgent father; and had, in consequence of her sister's marriage,\nbeen mistress of his house from a very early period.",
 ' Her mother\nhad died too long ago for her to have more than an indistinct\nremembrance of her caresses; and her place had been supplied\nby an excellent woman as governess, who had fallen little short\nof a mother in affection.',
 "\nSixteen years had Miss Taylor been in Mr. Woodhouse's family,\nless as a governess than a friend, very fond of both daughters,\nbut particularly of Emma.",
 ' Between _them_ it was more the intimacy\nof sisters.']

In [134]:
## word tokenization ##
# using different NLTK interfaces

# First approach:
# using word_tokenize function to perform tokenization
# default and recommended word tokenizer

emma_words = nltk.word_tokenize(emma)

In [135]:
# no. of words
len(emma_words)

191855

In [136]:
# first 500 words
emma_words[0:500] # output2

['[',
 'Emma',
 'by',
 'Jane',
 'Austen',
 '1816',
 ']',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse',
 ',',
 'handsome',
 ',',
 'clever',
 ',',
 'and',
 'rich',
 ',',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition',
 ',',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence',
 ';',
 'and',
 'had',
 'lived',
 'nearly',
 'twenty-one',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her',
 '.',
 'She',
 'was',
 'the',
 'youngest',
 'of',
 'the',
 'two',
 'daughters',
 'of',
 'a',
 'most',
 'affectionate',
 ',',
 'indulgent',
 'father',
 ';',
 'and',
 'had',
 ',',
 'in',
 'consequence',
 'of',
 'her',
 'sister',
 "'s",
 'marriage',
 ',',
 'been',
 'mistress',
 'of',
 'his',
 'house',
 'from',
 'a',
 'very',
 'early',
 'period',
 '.',
 'Her',
 'mother',
 'had',
 'died',
 'too',
 'long',
 'ago',
 'for',
 'her',
 'to',
 'have',
 'more',
 'than',
 'an',
 'indistinct',
 'remembrance',
 'of',
 'her',
 'caresses',
 ';',
 'and',
 'her',
 'place',
 'had',
 'been',
 'supplied',
 'by',
 'an',
 'excellent',
 'woman',
 'as',
 'governess',
 ',',
 'who',
 'had',
 'fallen',
 'little',
 'short',
 'of',
 'a',
 'mother',
 'in',
 'affection',
 '.',
 'Sixteen',
 'years',
 'had',
 'Miss',
 'Taylor',
 'been',
 'in',
 'Mr.',
 'Woodhouse',
 "'s",
 'family',
 ',',
 'less',
 'as',
 'a',
 'governess',
 'than',
 'a',
 'friend',
 ',',
 'very',
 'fond',
 'of',
 'both',
 'daughters',
 ',',
 'but',
 'particularly',
 'of',
 'Emma',
 '.',
 'Between',
 '_them_',
 'it',
 'was',
 'more',
 'the',
 'intimacy',
 'of',
 'sisters',
 '.',
 'Even',
 'before',
 'Miss',
 'Taylor',
 'had',
 'ceased',
 'to',
 'hold',
 'the',
 'nominal',
 'office',
 'of',
 'governess',
 ',',
 'the',
 'mildness',
 'of',
 'her',
 'temper',
 'had',
 'hardly',
 'allowed',
 'her',
 'to',
 'impose',
 'any',
 'restraint',
 ';',
 'and',
 'the',
 'shadow',
 'of',
 'authority',
 'being',
 'now',
 'long',
 'passed',
 'away',
 ',',
 'they',
 'had',
 'been',
 'living',
 'together',
 'as',
 'friend',
 'and',
 'friend',
 'very',
 'mutually',
 'attached',
 ',',
 'and',
 'Emma',
 'doing',
 'just',
 'what',
 'she',
 'liked',
 ';',
 'highly',
 'esteeming',
 'Miss',
 'Taylor',
 "'s",
 'judgment',
 ',',
 'but',
 'directed',
 'chiefly',
 'by',
 'her',
 'own',
 '.',
 'The',
 'real',
 'evils',
 ',',
 'indeed',
 ',',
 'of',
 'Emma',
 "'s",
 'situation',
 'were',
 'the',
 'power',
 'of',
 'having',
 'rather',
 'too',
 'much',
 'her',
 'own',
 'way',
 ',',
 'and',
 'a',
 'disposition',
 'to',
 'think',
 'a',
 'little',
 'too',
 'well',
 'of',
 'herself',
 ';',
 'these',
 'were',
 'the',
 'disadvantages',
 'which',
 'threatened',
 'alloy',
 'to',
 'her',
 'many',
 'enjoyments',
 '.',
 'The',
 'danger',
 ',',
 'however',
 ',',
 'was',
 'at',
 'present',
 'so',
 'unperceived',
 ',',
 'that',
 'they',
 'did',
 'not',
 'by',
 'any',
 'means',
 'rank',
 'as',
 'misfortunes',
 'with',
 'her',
 '.',
 'Sorrow',
 'came',
 '--',
 'a',
 'gentle',
 'sorrow',
 '--',
 'but',
 'not',
 'at',
 'all',
 'in',
 'the',
 'shape',
 'of',
 'any',
 'disagreeable',
 'consciousness.',
 '--',
 'Miss',
 'Taylor',
 'married',
 '.',
 'It',
 'was',
 'Miss',
 'Taylor',
 "'s",
 'loss',
 'which',
 'first',
 'brought',
 'grief',
 '.',
 'It',
 'was',
 'on',
 'the',
 'wedding-day',
 'of',
 'this',
 'beloved',
 'friend',
 'that',
 'Emma',
 'first',
 'sat',
 'in',
 'mournful',
 'thought',
 'of',
 'any',
 'continuance',
 '.',
 'The',
 'wedding',
 'over',
 ',',
 'and',
 'the',
 'bride-people',
 'gone',
 ',',
 'her',
 'father',
 'and',
 'herself',
 'were',
 'left',
 'to',
 'dine',
 'together',
 ',',
 'with',
 'no',
 'prospect',
 'of',
 'a',
 'third',
 'to',
 'cheer',
 'a',
 'long',
 'evening',
 '.',
 'Her',
 'father',
 'composed',
 'himself',
 'to',
 'sleep',
 'after',
 'dinner',
 ',',
 'as',
 'usual',
 ',',
 'and',
 'she',
 'had',
 'then',
 'only',
 'to',
 'sit',
 'and',
 'think',
 'of',
 'what',
 'she',
 'had',
 'lost',
 '.',
 'The',
 'event',
 'had',
 'every',
 'promise',
 'of',
 'happiness',
 'for',
 'her',
 'friend',
 '.',
 'Mr.',
 'Weston',
 'was',
 'a',
 'man',
 'of',
 'unexceptionable',
 'character',
 ',',
 'easy',
 'fortune',
 ',',
 'suitable',
 'age',
 ',',
 'and',
 'pleasant',
 'manners',
 ';',
 'and',
 'there',
 'was',
 'some',
 'satisfaction',
 'in',
 'considering',
 'with',
 'what',
 'self-denying',
 ',',
 'generous',
 'friendship',
 'she',
 'had',
 'always',
 'wished',
 'and',
 'promoted',
 'the',
 'match',
 ';',
 'but',
 'it',
 'was',
 'a',
 'black',
 'morning',
 "'s",
 'work',
 'for',
 'her',
 '.']

In [137]:
# Second approach:
# using TreebankWordTokenizer class to perform tokenization
# based on the Penn Treebank and uses various regular expressions to tokenize the text
treebank_wt = nltk. TreebankWordTokenizer()

# one primary assumption: sentence tokenization has been perfomred already
# used to tokenize the sentences into words
emma_sents[0]

'[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; and had lived nearly twenty-one years in the world\nwith very little to distress or vex her.'

In [138]:
emma_sents[1]

"She was the youngest of the two daughters of a most affectionate,\nindulgent father; and had, in consequence of her sister's marriage,\nbeen mistress of his house from a very early period."

In [139]:
# using tokenize method
emma_words2 = treebank_wt.tokenize(emma_sents[0])

In [140]:
emma_words2[0:500] # similar to output2

# Note: tokenizer splits and separates into independent tokens:
#periods appearing at the end of sentences,
#commas and single quotes when followed by whitespaces,
#Most punctuation characters
#words with standard contractions, e.g., don't to do and n't

['[',
 'Emma',
 'by',
 'Jane',
 'Austen',
 '1816',
 ']',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse',
 ',',
 'handsome',
 ',',
 'clever',
 ',',
 'and',
 'rich',
 ',',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition',
 ',',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence',
 ';',
 'and',
 'had',
 'lived',
 'nearly',
 'twenty-one',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her',
 '.']

In [141]:
# Third approach:
# using an instance of RegexpTokenizer class

# specific regular expression-based patterns are used
# pattern to identify tokens
pattern2 = r'\w+'

In [142]:
# using RegexpTokenizer function
regex_wt = nltk.RegexpTokenizer(pattern=pattern2, gaps=False)

In [143]:
# using tokenize method
emma_words3 = regex_wt.tokenize(emma)

In [144]:
emma_words3[0:500] # similar to output2

['Emma',
 'by',
 'Jane',
 'Austen',
 '1816',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse',
 'handsome',
 'clever',
 'and',
 'rich',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence',
 'and',
 'had',
 'lived',
 'nearly',
 'twenty',
 'one',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her',
 'She',
 'was',
 'the',
 'youngest',
 'of',
 'the',
 'two',
 'daughters',
 'of',
 'a',
 'most',
 'affectionate',
 'indulgent',
 'father',
 'and',
 'had',
 'in',
 'consequence',
 'of',
 'her',
 'sister',
 's',
 'marriage',
 'been',
 'mistress',
 'of',
 'his',
 'house',
 'from',
 'a',
 'very',
 'early',
 'period',
 'Her',
 'mother',
 'had',
 'died',
 'too',
 'long',
 'ago',
 'for',
 'her',
 'to',
 'have',
 'more',
 'than',
 'an',
 'indistinct',
 'remembrance',
 'of',
 'her',
 'caresses',
 'and',
 'her',
 'place',
 'had',
 'been',
 'supplied',
 'by',
 'an',
 'excellent',
 'woman',
 'as',
 'governess',
 'who',
 'had',
 'fallen',
 'little',
 'short',
 'of',
 'a',
 'mother',
 'in',
 'affection',
 'Sixteen',
 'years',
 'had',
 'Miss',
 'Taylor',
 'been',
 'in',
 'Mr',
 'Woodhouse',
 's',
 'family',
 'less',
 'as',
 'a',
 'governess',
 'than',
 'a',
 'friend',
 'very',
 'fond',
 'of',
 'both',
 'daughters',
 'but',
 'particularly',
 'of',
 'Emma',
 'Between',
 '_them_',
 'it',
 'was',
 'more',
 'the',
 'intimacy',
 'of',
 'sisters',
 'Even',
 'before',
 'Miss',
 'Taylor',
 'had',
 'ceased',
 'to',
 'hold',
 'the',
 'nominal',
 'office',
 'of',
 'governess',
 'the',
 'mildness',
 'of',
 'her',
 'temper',
 'had',
 'hardly',
 'allowed',
 'her',
 'to',
 'impose',
 'any',
 'restraint',
 'and',
 'the',
 'shadow',
 'of',
 'authority',
 'being',
 'now',
 'long',
 'passed',
 'away',
 'they',
 'had',
 'been',
 'living',
 'together',
 'as',
 'friend',
 'and',
 'friend',
 'very',
 'mutually',
 'attached',
 'and',
 'Emma',
 'doing',
 'just',
 'what',
 'she',
 'liked',
 'highly',
 'esteeming',
 'Miss',
 'Taylor',
 's',
 'judgment',
 'but',
 'directed',
 'chiefly',
 'by',
 'her',
 'own',
 'The',
 'real',
 'evils',
 'indeed',
 'of',
 'Emma',
 's',
 'situation',
 'were',
 'the',
 'power',
 'of',
 'having',
 'rather',
 'too',
 'much',
 'her',
 'own',
 'way',
 'and',
 'a',
 'disposition',
 'to',
 'think',
 'a',
 'little',
 'too',
 'well',
 'of',
 'herself',
 'these',
 'were',
 'the',
 'disadvantages',
 'which',
 'threatened',
 'alloy',
 'to',
 'her',
 'many',
 'enjoyments',
 'The',
 'danger',
 'however',
 'was',
 'at',
 'present',
 'so',
 'unperceived',
 'that',
 'they',
 'did',
 'not',
 'by',
 'any',
 'means',
 'rank',
 'as',
 'misfortunes',
 'with',
 'her',
 'Sorrow',
 'came',
 'a',
 'gentle',
 'sorrow',
 'but',
 'not',
 'at',
 'all',
 'in',
 'the',
 'shape',
 'of',
 'any',
 'disagreeable',
 'consciousness',
 'Miss',
 'Taylor',
 'married',
 'It',
 'was',
 'Miss',
 'Taylor',
 's',
 'loss',
 'which',
 'first',
 'brought',
 'grief',
 'It',
 'was',
 'on',
 'the',
 'wedding',
 'day',
 'of',
 'this',
 'beloved',
 'friend',
 'that',
 'Emma',
 'first',
 'sat',
 'in',
 'mournful',
 'thought',
 'of',
 'any',
 'continuance',
 'The',
 'wedding',
 'over',
 'and',
 'the',
 'bride',
 'people',
 'gone',
 'her',
 'father',
 'and',
 'herself',
 'were',
 'left',
 'to',
 'dine',
 'together',
 'with',
 'no',
 'prospect',
 'of',
 'a',
 'third',
 'to',
 'cheer',
 'a',
 'long',
 'evening',
 'Her',
 'father',
 'composed',
 'himself',
 'to',
 'sleep',
 'after',
 'dinner',
 'as',
 'usual',
 'and',
 'she',
 'had',
 'then',
 'only',
 'to',
 'sit',
 'and',
 'think',
 'of',
 'what',
 'she',
 'had',
 'lost',
 'The',
 'event',
 'had',
 'every',
 'promise',
 'of',
 'happiness',
 'for',
 'her',
 'friend',
 'Mr',
 'Weston',
 'was',
 'a',
 'man',
 'of',
 'unexceptionable',
 'character',
 'easy',
 'fortune',
 'suitable',
 'age',
 'and',
 'pleasant',
 'manners',
 'and',
 'there',
 'was',
 'some',
 'satisfaction',
 'in',
 'considering',
 'with',
 'what',
 'self',
 'denying',
 'generous',
 'friendship',
 'she',
 'had',
 'always',
 'wished',
 'and',
 'promoted',
 'the',
 'match',
 'but',
 'it',
 'was',
 'a',
 'black',
 'morning',
 's',
 'work',
 'for',
 'her',
 'The',
 'want',
 'of',
 'Miss',
 'Taylor',
 'would',
 'be',
 'felt',
 'every',
 'hour',
 'of',
 'every',
 'day',
 'She',
 'recalled',
 'her',
 'past',
 'kindness',
 'the',
 'kindness',
 'the',
 'affection',
 'of',
 'sixteen',
 'years',
 'how',
 'she',
 'had',
 'taught',
 'and',
 'how',
 'she',
 'had',
 'played',
 'with',
 'her',
 'from',
 'five',
 'years',
 'old',
 'how',
 'she',
 'had',
 'devoted',
 'all',
 'her',
 'powers',
 'to',
 'attach',
 'and',
 'amuse',
 'her',
 'in',
 'health',
 'and']

In [145]:
# pattern to identify gaps
pattern3 = r'\s+'

In [146]:
regex_wt1 = nltk.RegexpTokenizer(pattern=pattern3, gaps=True)

In [147]:
emma_words4 = regex_wt1.tokenize(emma)

In [148]:
emma_words4[0:500] # output3

['[Emma',
 'by',
 'Jane',
 'Austen',
 '1816]',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse,',
 'handsome,',
 'clever,',
 'and',
 'rich,',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition,',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence;',
 'and',
 'had',
 'lived',
 'nearly',
 'twenty-one',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her.',
 'She',
 'was',
 'the',
 'youngest',
 'of',
 'the',
 'two',
 'daughters',
 'of',
 'a',
 'most',
 'affectionate,',
 'indulgent',
 'father;',
 'and',
 'had,',
 'in',
 'consequence',
 'of',
 'her',
 "sister's",
 'marriage,',
 'been',
 'mistress',
 'of',
 'his',
 'house',
 'from',
 'a',
 'very',
 'early',
 'period.',
 'Her',
 'mother',
 'had',
 'died',
 'too',
 'long',
 'ago',
 'for',
 'her',
 'to',
 'have',
 'more',
 'than',
 'an',
 'indistinct',
 'remembrance',
 'of',
 'her',
 'caresses;',
 'and',
 'her',
 'place',
 'had',
 'been',
 'supplied',
 'by',
 'an',
 'excellent',
 'woman',
 'as',
 'governess,',
 'who',
 'had',
 'fallen',
 'little',
 'short',
 'of',
 'a',
 'mother',
 'in',
 'affection.',
 'Sixteen',
 'years',
 'had',
 'Miss',
 'Taylor',
 'been',
 'in',
 'Mr.',
 "Woodhouse's",
 'family,',
 'less',
 'as',
 'a',
 'governess',
 'than',
 'a',
 'friend,',
 'very',
 'fond',
 'of',
 'both',
 'daughters,',
 'but',
 'particularly',
 'of',
 'Emma.',
 'Between',
 '_them_',
 'it',
 'was',
 'more',
 'the',
 'intimacy',
 'of',
 'sisters.',
 'Even',
 'before',
 'Miss',
 'Taylor',
 'had',
 'ceased',
 'to',
 'hold',
 'the',
 'nominal',
 'office',
 'of',
 'governess,',
 'the',
 'mildness',
 'of',
 'her',
 'temper',
 'had',
 'hardly',
 'allowed',
 'her',
 'to',
 'impose',
 'any',
 'restraint;',
 'and',
 'the',
 'shadow',
 'of',
 'authority',
 'being',
 'now',
 'long',
 'passed',
 'away,',
 'they',
 'had',
 'been',
 'living',
 'together',
 'as',
 'friend',
 'and',
 'friend',
 'very',
 'mutually',
 'attached,',
 'and',
 'Emma',
 'doing',
 'just',
 'what',
 'she',
 'liked;',
 'highly',
 'esteeming',
 'Miss',
 "Taylor's",
 'judgment,',
 'but',
 'directed',
 'chiefly',
 'by',
 'her',
 'own.',
 'The',
 'real',
 'evils,',
 'indeed,',
 'of',
 "Emma's",
 'situation',
 'were',
 'the',
 'power',
 'of',
 'having',
 'rather',
 'too',
 'much',
 'her',
 'own',
 'way,',
 'and',
 'a',
 'disposition',
 'to',
 'think',
 'a',
 'little',
 'too',
 'well',
 'of',
 'herself;',
 'these',
 'were',
 'the',
 'disadvantages',
 'which',
 'threatened',
 'alloy',
 'to',
 'her',
 'many',
 'enjoyments.',
 'The',
 'danger,',
 'however,',
 'was',
 'at',
 'present',
 'so',
 'unperceived,',
 'that',
 'they',
 'did',
 'not',
 'by',
 'any',
 'means',
 'rank',
 'as',
 'misfortunes',
 'with',
 'her.',
 'Sorrow',
 'came--a',
 'gentle',
 'sorrow--but',
 'not',
 'at',
 'all',
 'in',
 'the',
 'shape',
 'of',
 'any',
 'disagreeable',
 'consciousness.--Miss',
 'Taylor',
 'married.',
 'It',
 'was',
 'Miss',
 "Taylor's",
 'loss',
 'which',
 'first',
 'brought',
 'grief.',
 'It',
 'was',
 'on',
 'the',
 'wedding-day',
 'of',
 'this',
 'beloved',
 'friend',
 'that',
 'Emma',
 'first',
 'sat',
 'in',
 'mournful',
 'thought',
 'of',
 'any',
 'continuance.',
 'The',
 'wedding',
 'over,',
 'and',
 'the',
 'bride-people',
 'gone,',
 'her',
 'father',
 'and',
 'herself',
 'were',
 'left',
 'to',
 'dine',
 'together,',
 'with',
 'no',
 'prospect',
 'of',
 'a',
 'third',
 'to',
 'cheer',
 'a',
 'long',
 'evening.',
 'Her',
 'father',
 'composed',
 'himself',
 'to',
 'sleep',
 'after',
 'dinner,',
 'as',
 'usual,',
 'and',
 'she',
 'had',
 'then',
 'only',
 'to',
 'sit',
 'and',
 'think',
 'of',
 'what',
 'she',
 'had',
 'lost.',
 'The',
 'event',
 'had',
 'every',
 'promise',
 'of',
 'happiness',
 'for',
 'her',
 'friend.',
 'Mr.',
 'Weston',
 'was',
 'a',
 'man',
 'of',
 'unexceptionable',
 'character,',
 'easy',
 'fortune,',
 'suitable',
 'age,',
 'and',
 'pleasant',
 'manners;',
 'and',
 'there',
 'was',
 'some',
 'satisfaction',
 'in',
 'considering',
 'with',
 'what',
 'self-denying,',
 'generous',
 'friendship',
 'she',
 'had',
 'always',
 'wished',
 'and',
 'promoted',
 'the',
 'match;',
 'but',
 'it',
 'was',
 'a',
 'black',
 "morning's",
 'work',
 'for',
 'her.',
 'The',
 'want',
 'of',
 'Miss',
 'Taylor',
 'would',
 'be',
 'felt',
 'every',
 'hour',
 'of',
 'every',
 'day.',
 'She',
 'recalled',
 'her',
 'past',
 'kindness--the',
 'kindness,',
 'the',
 'affection',
 'of',
 'sixteen',
 'years--how',
 'she',
 'had',
 'taught',
 'and',
 'how',
 'she',
 'had',
 'played',
 'with',
 'her',
 'from',
 'five',
 'years',
 'old--how',
 'she',
 'had',
 'devoted',
 'all',
 'her',
 'powers',
 'to',
 'attach',
 'and',
 'amuse',
 'her',
 'in',
 'health--and',
 'how',
 'nursed',
 'her',
 'through',
 'the',
 'various',
 'illnesses',
 'of',
 'childhood.',
 'A',
 'large',
 'debt',
 'of',
 'gratitude',
 'was',
 'owing',
 'here;']

In [149]:
# get start and end indices of each token
# using span_tokenize method
word_indices = list(regex_wt1.span_tokenize(emma))

In [150]:
word_indices

[(0, 5),
 (6, 8),
 (9, 13),
 (14, 20),
 (21, 26),
 (28, 34),
 (35, 36),
 (38, 45),
 (46, 47),
 (50, 54),
 (55, 65),
 (66, 75),
 (76, 83),
 (84, 87),
 (88, 93),
 (94, 98),
 (99, 100),
 (101, 112),
 (113, 117),
 (118, 121),
 (122, 127),
 (128, 140),
 (141, 147),
 (148, 150),
 (151, 156),
 (157, 161),
 (162, 164),
 (165, 168),
 (169, 173),
 (174, 183),
 (184, 186),
 (187, 197),
 (198, 201),
 (202, 205),
 (206, 211),
 (212, 218),
 (219, 229),
 (230, 235),
 (236, 238),
 (239, 242),
 (243, 248),
 (249, 253),
 (254, 258),
 (259, 265),
 (266, 268),
 (269, 277),
 (278, 280),
 (281, 284),
 (285, 289),
 (291, 294),
 (295, 298),
 (299, 302),
 (303, 311),
 (312, 314),
 (315, 318),
 (319, 322),
 (323, 332),
 (333, 335),
 (336, 337),
 (338, 342),
 (343, 356),
 (357, 366),
 (367, 374),
 (375, 378),
 (379, 383),
 (384, 386),
 (387, 398),
 (399, 401),
 (402, 405),
 (406, 414),
 (415, 424),
 (425, 429),
 (430, 438),
 (439, 441),
 (442, 445),
 (446, 451),
 (452, 456),
 (457, 458),
 (459, 463),
 (464, 469),
 (470, 477),
 (479, 482),
 (483, 489),
 (490, 493),
 (494, 498),
 (499, 502),
 (503, 507),
 (508, 511),
 (512, 515),
 (516, 519),
 (520, 522),
 (523, 527),
 (528, 532),
 (533, 537),
 (538, 540),
 (541, 551),
 (552, 563),
 (564, 566),
 (567, 570),
 (571, 580),
 (581, 584),
 (585, 588),
 (589, 594),
 (595, 598),
 (599, 603),
 (604, 612),
 (613, 615),
 (616, 618),
 (619, 628),
 (629, 634),
 (635, 637),
 (638, 648),
 (649, 652),
 (653, 656),
 (657, 663),
 (664, 670),
 (671, 676),
 (677, 679),
 (680, 681),
 (682, 688),
 (689, 691),
 (692, 702),
 (704, 711),
 (712, 717),
 (718, 721),
 (722, 726),
 (727, 733),
 (734, 738),
 (739, 741),
 (742, 745),
 (746, 757),
 (758, 765),
 (766, 770),
 (771, 773),
 (774, 775),
 (776, 785),
 (786, 790),
 (791, 792),
 (793, 800),
 (801, 805),
 (806, 810),
 (811, 813),
 (814, 818),
 (819, 829),
 (830, 833),
 (834, 846),
 (847, 849),
 (850, 855),
 (857, 864),
 (865, 871),
 (872, 874),
 (875, 878),
 (879, 883),
 (884, 887),
 (888, 896),
 (897, 899),
 (900, 908),
 (910, 914),
 (915, 921),
 (922, 926),
 (927, 933),
 (934, 937),
 (938, 944),
 (945, 947),
 (948, 952),
 (953, 956),
 (957, 964),
 (965, 971),
 (972, 974),
 (975, 985),
 (986, 989),
 (990, 998),
 (999, 1001),
 (1002, 1005),
 (1006, 1012),
 (1013, 1016),
 (1017, 1023),
 (1024, 1031),
 (1032, 1035),
 (1036, 1038),
 (1039, 1045),
 (1046, 1049),
 (1050, 1060),
 (1061, 1064),
 (1065, 1068),
 (1069, 1075),
 (1076, 1078),
 (1079, 1088),
 (1089, 1094),
 (1095, 1098),
 (1099, 1103),
 (1104, 1110),
 (1111, 1116),
 (1117, 1121),
 (1122, 1125),
 (1126, 1130),
 (1131, 1137),
 (1138, 1146),
 (1147, 1149),
 (1150, 1156),
 (1157, 1160),
 (1161, 1167),
 (1168, 1172),
 (1173, 1181),
 (1182, 1191),
 (1192, 1195),
 (1196, 1200),
 (1201, 1206),
 (1207, 1211),
 (1212, 1216),
 (1217, 1220),
 (1221, 1227),
 (1228, 1234),
 (1235, 1244),
 (1245, 1249),
 (1250, 1258),
 (1259, 1268),
 (1269, 1272),
 (1273, 1281),
 (1282, 1289),
 (1290, 1292),
 (1293, 1296),
 (1297, 1301),
 (1303, 1306),
 (1307, 1311),
 (1312, 1318),
 (1319, 1326),
 (1327, 1329),
 (1330, 1336),
 (1337, 1346),
 (1347, 1351),
 (1352, 1355),
 (1356, 1361),
 (1362, 1364),
 (1365, 1371),
 (1372, 1378),
 (1379, 1382),
 (1383, 1387),
 (1388, 1391),
 (1392, 1395),
 (1396, 1400),
 (1401, 1404),
 (1405, 1406),
 (1407, 1418),
 (1419, 1421),
 (1422, 1427),
 (1428, 1429),
 (1430, 1436),
 (1437, 1440),
 (1441, 1445),
 (1446, 1448),
 (1449, 1457),
 (1458, 1463),
 (1464, 1468),
 (1469, 1472),
 (1473, 1486),
 (1487, 1492),
 (1493, 1503),
 (1504, 1509),
 (1510, 1512),
 (1513, 1516),
 (1517, 1521),
 (1522, 1533),
 (1535, 1538),
 (1539, 1546),
 (1547, 1555),
 (1556, 1559),
 (1560, 1562),
 (1563, 1570),
 (1571, 1573),
 (1574, 1586),
 (1587, 1591),
 (1592, 1596),
 (1597, 1600),
 (1601, 1604),
 (1605, 1607),
 (1608, 1611),
 (1612, 1617),
 (1618, 1622),
 (1623, 1625),
 (1626, 1637),
 (1638, 1642),
 (1643, 1647),
 (1649, 1655),
 (1656, 1663),
 (1664, 1670),
 (1671, 1682),
 (1683, 1686),
 (1687, 1689),
 (1690, 1693),
 (1694, 1696),
 (1697, 1700),
 (1701, 1706),
 (1707, 1709),
 (1710, 1713),
 (1714, 1726),
 (1727, 1747),
 (1748, 1754),
 (1755, 1763),
 (1765, 1767),
 (1768, 1771),
 (1772, 1776),
 (1777, 1785),
 (1786, 1790),
 (1791, 1796),
 (1797, 1802),
 (1803, 1810),
 (1811, 1817),
 (1819, 1821),
 (1822, 1825),
 (1826, 1828),
 (1829, 1832),
 (1833, 1844),
 (1845, 1847),
 (1848, 1852),
 (1853, 1860),
 (1861, 1867),
 (1868, 1872),
 (1873, 1877),
 (1878, 1883),
 (1884, 1887),
 (1888, 1890),
 (1891, 1899),
 (1900, 1907),
 (1908, 1910),
 (1911, 1914),
 (1915, 1927),
 (1929, 1932),
 (1933, 1940),
 (1941, 1946),
 (1947, 1950),
 (1951, 1954),
 (1955, 1967),
 (1968, 1973),
 (1974, 1977),
 (1978, 1984),
 (1985, 1988),
 (1989, 1996),
 (1997, 2001),
 (2002, 2006),
 (2007, 2009),
 (2010, 2014),
 (2015, 2024),
 (2025, 2029),
 (2030, 2032),
 (2033, 2041),
 (2042, 2044),
 (2045, 2046),
 (2047, 2052),
 (2053, 2055),
 (2056, 2061),
 (2062, 2063),
 (2064, 2068),
 (2069, 2077),
 (2079, 2082),
 (2083, 2089),
 (2090, 2098),
 (2099, 2106),
 (2107, 2109),
 (2110, 2115),
 (2116, 2121),
 (2122, 2129),
 (2130, 2132),
 (2133, 2139),
 (2140, 2143),
 (2144, 2147),
 (2148, 2151),
 (2152, 2156),
 (2157, 2161),
 (2162, 2164),
 (2165, 2168),
 (2169, 2172),
 (2173, 2178),
 (2179, 2181),
 (2182, 2186),
 (2187, 2190),
 (2191, 2194),
 (2195, 2200),
 (2202, 2205),
 (2206, 2211),
 (2212, 2215),
 (2216, 2221),
 (2222, 2229),
 (2230, 2232),
 (2233, 2242),
 (2243, 2246),
 (2247, 2250),
 (2251, 2258),
 (2260, 2263),
 (2264, 2270),
 (2271, 2274),
 (2275, 2276),
 (2277, 2280),
 (2281, 2283),
 (2284, 2299),
 (2300, 2310),
 (2311, 2315),
 (2316, 2324),
 (2325, 2333),
 (2334, 2338),
 (2339, 2342),
 (2343, 2351),
 (2352, 2360),
 (2361, 2364),
 (2365, 2370),
 (2371, 2374),
 (2375, 2379),
 (2380, 2392),
 (2393, 2395),
 (2396, 2407),
 (2408, 2412),
 (2413, 2417),
 (2418, 2431),
 (2432, 2440),
 (2441, 2451),
 (2452, 2455),
 (2456, 2459),
 (2460, 2466),
 (2467, 2473),
 (2474, 2477),
 (2478, 2486),
 (2487, 2490),
 (2491, 2497),
 (2498, 2501),
 (2502, 2504),
 (2505, 2508),
 (2509, 2510),
 (2511, 2516),
 (2517, 2526),
 (2527, 2531),
 (2532, 2535),
 (2536, 2540),
 (2541, 2544),
 (2545, 2549),
 (2550, 2552),
 (2553, 2557),
 (2558, 2564),
 (2565, 2570),
 (2571, 2573),
 (2574, 2578),
 (2579, 2584),
 (2585, 2589),
 (2590, 2592),
 (2593, 2598),
 (2599, 2603),
 (2604, 2607),
 (2608, 2616),
 (2617, 2620),
 (2621, 2625),
 (2626, 2639),
 (2640, 2649),
 (2650, 2653),
 (2654, 2663),
 (2664, 2666),
 (2667, 2674),
 (2675, 2685),
 (2686, 2689),
 (2690, 2693),
 (2694, 2700),
 (2701, 2704),
 (2705, 2708),
 (2709, 2712),
 (2713, 2716),
 (2717, 2723),
 (2724, 2728),
 (2729, 2732),
 (2733, 2737),
 (2738, 2742),
 (2743, 2748),
 (2749, 2757),
 (2758, 2761),
 (2762, 2765),
 (2766, 2773),
 (2774, 2777),
 (2778, 2781),
 (2782, 2788),
 (2789, 2791),
 (2792, 2798),
 (2799, 2802),
 (2803, 2808),
 (2809, 2812),
 (2813, 2815),
 (2816, 2827),
 (2828, 2831),
 (2832, 2838),
 (2839, 2842),
 (2843, 2850),
 (2851, 2854),
 (2855, 2862),
 (2863, 2872),
 (2873, 2875),
 (2876, 2886),
 (2888, 2889),
 (2890, 2895),
 (2896, 2900),
 (2901, 2903),
 (2904, 2913),
 (2914, 2917),
 (2918, 2923),
 (2924, 2929),
 (2930, 2933),
 (2934, 2937),
 (2938, 2949),
 (2950, 2952),
 (2953, 2956),
 (2957, 2961),
 (2962, 2967),
 (2968, 2974),
 (2975, 2978),
 (2979, 2984),
 (2985, 2992),
 (2993, 2996),
 (2997, 3004),
 (3005, 3014),
 (3015, 3020),
 (3021, 3024),
 (3025, 3029),
 (3030, 3038),
 (3039, 3049),
 (3050, 3059),
 (3060, 3062),
 (3063, 3068),
 (3069, 3074),
 (3075, 3079),
 (3080, 3082),
 (3083, 3087),
 (3088, 3094),
 (3095, 3098),
 (3099, 3102),
 (3103, 3104),
 (3105, 3112),
 (3113, 3121),
 (3122, 3135),
 (3136, 3139),
 (3140, 3143),
 (3144, 3148),
 (3149, 3150),
 (3151, 3157),
 (3158, 3161),
 (3162, 3171),
 (3172, 3176),
 (3177, 3179),
 (3180, 3183),
 (3184, 3194),
 (3195, 3207),
 (3208, 3222),
 (3223, 3230),
 (3231, 3238),
 (3239, 3246),
 (3247, 3250),
 (3251, 3254),
 (3255, 3259),
 (3260, 3262),
 (3263, 3266),
 (3267, 3274),
 (3275, 3285),
 (3286, 3288),
 (3289, 3292),
 (3293, 3296),
 (3297, 3306),
 (3307, 3310),
 (3311, 3321),
 (3322, 3332),
 (3333, 3335),
 (3336, 3344),
 (3345, 3347),
 (3348, 3353),
 (3354, 3363),
 (3364, 3369),
 (3370, 3376),
 (3377, 3379),
 (3380, 3389),
 (3390, 3392),
 (3393, 3397),
 (3398, 3401),
 (3402, 3407),
 (3408, 3413),
 (3414, 3419),
 (3420, 3427),
 (3428, 3430),
 (3431, 3433),
 (3434, 3440),
 (3441, 3444),
 (3445, 3448),
 (3449, 3452),
 (3453, 3457),
 (3458, 3460),
 (3461, 3470),
 (3471, 3474),
 (3475, 3478),
 (3479, 3481),
 (3482, 3487),
 (3488, 3493),
 (3494, 3498),
 (3499, 3505),
 (3507, 3510),
 (3511, 3514),
 (3515, 3518),
 (3519, 3521),
 (3522, 3526),
 (3527, 3530),
 (3531, 3542),
 (3543, 3546),
 (3547, 3551),
 (3552, 3556),
 (3557, 3560),
 (3561, 3567),
 (3568, 3571),
 (3572, 3577),
 (3578, 3582),
 (3583, 3587),
 (3588, 3589),
 (3590, 3594),
 (3595, 3599),
 (3600, 3605),
 (3606, 3609),
 (3610, 3614),
 (3615, 3618),
 (3619, 3624),
 (3625, 3629),
 (3630, 3635),
 (3636, 3640),
 (3641, 3643),
 (3644, 3647),
 (3648, 3658),
 (3659, 3666),
 (3667, 3668),
 (3669, 3673),
 (3674, 3681),
 (3682, 3686),
 (3687, 3691),
 (3692, 3693),
 (3694, 3698),
 (3699, 3703),
 (3704, 3709),
 (3710, 3713),
 (3714, 3715),
 (3716, 3720),
 (3721, 3727),
 (3728, 3730),
 (3731, 3734),
 (3735, 3741),
 (3742, 3745),
 (3746, 3750),
 (3751, 3754),
 (3755, 3758),
 (3759, 3770),
 (3771, 3778),
 (3779, 3782),
 (3783, 3792),
 (3793, 3796),
 (3797, 3800),
 (3801, 3804),
 (3805, 3807),
 (3808, 3813),
 (3814, 3820),
 (3821, 3823),
 (3824, 3833),
 (3834, 3838),
 (3839, 3851),
 (3852, 3861),
 (3863, 3866),
 (3867, 3873),
 (3874, 3879),
 (3880, 3883),
 (3884, 3891),
 (3892, 3895),
 (3896, 3898),
 (3899, 3902),
 (3903, 3905),
 (3906, 3915),
 (3916, 3919),
 (3920, 3924),
 (3926, 3928),
 (3929, 3934),
 (3935, 3938),
 (3939, 3943),
 (3944, 3947),
 (3948, 3950),
 (3951, 3964),
 (3965, 3973),
 (3974, 3976),
 (3977, 3985),
 (3987, 3990),
 (3991, 3995),
 (3996, 3998),
 (3999, 4002),
 (4003, 4009),
 (4010, 4019),
 (4020, 4022),
 (4023, 4028),
 (4029, 4033),
 (4034, 4038),
 (4039, 4042),
 (4043, 4052),
 (4053, 4056),
 (4057, 4060),
 (4061, 4068),
 (4069, 4075),
 (4076, 4079),
 (4080, 4084),
 (4085, 4094),
 (4095, 4097),
 (4098, 4101),
 (4102, 4114),
 (4115, 4118),
 (4119, 4126),
 (4127, 4130),
 (4131, 4137),
 (4138, 4142),
 (4143, 4144),
 (4145, 4159),
 (4160, 4163),
 (4164, 4167),
 (4168, 4173),
 (4174, 4181),
 (4182, 4190),
 (4191, 4193),
 (4194, 4198),
 (4199, 4201),
 (4202, 4207),
 (4208, 4210),
 (4211, 4214),
 (4215, 4216),
 (4217, 4221),
 (4222, 4227),
 (4228, 4231),
 (4232, 4234),
 (4235, 4239),
 (4240, 4244),
 (4245, 4247),
 (4248, 4254),
 (4255, 4258),
 (4259, 4265),
 (4266, 4276),
 (4277, 4284),
 (4285, 4288),
 (4289, 4292),
 (4293, 4305),
 (4306, 4308),
 (4309, 4312),
 (4313, 4318),
 (4319, 4322),
 (4323, 4326),
 (4327, 4334),
 (4335, 4342),
 (4343, 4346),
 (4347, 4354),
 (4355, 4360),
 (4361, 4364),
 (4365, 4369),
 (4370, 4381),
 (4382, 4385),
 (4386, 4388),
 (4389, 4392),
 (4393, 4398),
 (4400, 4403),
 (4404, 4411),
 (4412, 4418),
 (4419, 4432),
 (4433, 4436),
 (4437, 4443),
 (4444, 4451),
 (4452, 4454),
 (4455, 4465),
 (4466, 4471),
 (4472, 4479),
 (4480, 4482),
 (4483, 4490),
 (4491, 4495),
 (4496, 4503),
 (4504, 4509),
 (4510, 4514),
 (4515, 4518),
 (4519, 4523),
 (4524, 4530),
 (4531, 4534),
 (4535, 4540),
 (4541, 4547),
 (4548, 4551),
 (4552, 4556),
 (4557, 4558),
 (4559, 4563),
 (4564, 4571),
 (4572, 4575),
 (4576, 4584),
 (4585, 4592),
 (4593, 4597),
 (4598, 4600),
 (4601, 4610),
 (4611, 4618),
 (4619, 4621),
 (4622, 4632),
 (4633, 4639),
 (4640, 4649),
 (4650, 4657),
 (4658, 4661),
 (4662, 4666),
 (4667, 4672),
 (4673, 4677),
 (4678, 4686),
 (4687, 4690),
 (4691, 4694),
 (4695, 4703),
 (4704, 4707),
 (4708, 4713),
 (4714, 4720),
 (4721, 4730),
 (4731, 4733),
 (4734, 4738),
 (4739, 4742),
 (4743, 4749),
 (4750, 4753),
 (4754, 4758),
 (4759, 4762),
 (4763, 4771),
 (4772, 4779),
 (4780, 4786),
 (4788, 4797),
 (4798, 4801),
 (4802, 4807),
 (4808, 4811),
 (4812, 4820),
 (4821, 4829),
 (4830, 4836),
 (4837, 4846),
 (4847, 4849),
 (4850, 4851),
 (4852, 4857),
 (4858, 4860),
 (4861, 4866),
 (4867, 4877),
 (4878, 4880),
 (4881, 4886),
 (4887, 4889),
 (4890, 4893),
 (4894, 4902),
 (4903, 4908),
 (4909, 4912),
 (4913, 4925),
 (4926, 4929),
 (4930, 4935),
 (4936, 4939),
 (4940, 4946),
 (4947, 4954),
 (4955, 4963),
 (4964, 4967),
 (4968, 4970),
 (4971, 4978),
 (4980, 4983),
 (4984, 4994),
 (4995, 4999),
 (5000, 5005),
 (5006, 5008),
 (5009, 5020),
 (5021, 5027),
 (5029, 5032),
 (5033, 5039),
 (5040, 5042),
 (5043, 5045),
 (5046, 5051),
 (5053, 5056),
 (5057, 5060),
 (5061, 5065),
 (5066, 5078),
 (5079, 5081),
 (5082, 5085),
 (5086, 5092),
 (5093, 5096),
 (5097, 5100),
 (5101, 5107),
 (5108, 5111),
 (5112, 5123),
 (5124, 5130),
 (5131, 5134),
 (5135, 5138),
 (5139, 5142),
 (5143, 5148),
 (5149, 5153),
 (5154, 5157),
 (5158, 5163),
 (5164, 5166),
 (5167, 5175),
 (5176, 5178),
 (5179, 5183),
 (5184, 5186),
 (5187, 5191),
 (5192, 5198),
 (5199, 5202),
 (5203, 5207),
 (5208, 5212),
 (5213, 5214),
 (5215, 5219),
 (5221, 5223),
 (5224, 5227),
 (5228, 5229),
 (5230, 5240),
 (5241, 5248),
 (5249, 5252),
 (5253, 5257),
 (5258, 5263),
 (5264, 5267),
 (5268, 5271),
 (5272, 5276),
 (5277, 5281),
 (5282, 5285),
 (5286, 5289),
 (5290, 5294),
 (5295, 5298),
 (5299, 5309),
 (5310, 5317),
 (5318, 5322),
 (5323, 5326),
 (5327, 5333),
 (5334, 5340),
 (5341, 5344),
 (5345, 5349),
 (5350, 5352),
 (5353, 5362),
 (5363, 5365),
 (5366, 5368),
 (5369, 5378),
 (5379, 5382),
 (5383, 5390),
 (5391, 5399),
 (5400, 5408),
 (5410, 5412),
 (5413, 5416),
 (5417, 5418),
 (5419, 5426),
 (5427, 5431),
 (5432, 5438),
 (5439, 5449),
 (5450, 5454),
 (5455, 5457),
 (5458, 5463),
 (5464, 5468),
 (5469, 5473),
 (5474, 5476),
 (5477, 5480),
 (5481, 5485),
 (5486, 5489),
 (5490, 5493),
 (5494, 5500),
 (5501, 5503),
 (5504, 5508),
 (5509, 5513),
 (5514, 5519),
 (5520, 5526),
 (5527, 5533),
 (5534, 5536),
 (5537, 5542),
 (5543, 5548),
 (5550, 5560),
 (5561, 5563),
 (5564, 5567),
 (5568, 5574),
 (5575, 5577),
 (5578, 5585),
 (5586, 5589),
 (5590, 5596),
 (5597, 5610),
 (5611, 5614),
 (5615, 5617),
 (5618, 5621),
 (5622, 5624),
 (5625, 5627),
 (5628, 5633),
 (5634, 5637),
 (5638, 5648),
 (5649, 5651),
 (5652, 5655),
 (5656, 5659),
 (5660, 5670),
 (5671, 5680),
 (5681, 5684),
 (5685, 5690),
 (5691, 5695),
 (5696, 5701),
 (5702, 5704),
 (5705, 5708),
 (5709, 5712),
 (5713, 5717),
 (5718, 5729),
 (5730, 5736),
 (5737, 5739),
 (5740, 5743),
 (5744, 5748),
 (5749, 5757),
 (5758, 5759),
 (5760, 5765),
 (5766, 5768),
 (5769, 5779),
 (5780, 5784),
 (5785, 5787),
 (5788, 5791),
 (5792, 5795),
 (5796, 5803),
 (5804, 5806),
 (5807, 5811),
 ...]

In [151]:
[emma[start:end] for start, end in word_indices] # similar to output3

['[Emma',
 'by',
 'Jane',
 'Austen',
 '1816]',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse,',
 'handsome,',
 'clever,',
 'and',
 'rich,',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition,',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence;',
 'and',
 'had',
 'lived',
 'nearly',
 'twenty-one',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her.',
 'She',
 'was',
 'the',
 'youngest',
 'of',
 'the',
 'two',
 'daughters',
 'of',
 'a',
 'most',
 'affectionate,',
 'indulgent',
 'father;',
 'and',
 'had,',
 'in',
 'consequence',
 'of',
 'her',
 "sister's",
 'marriage,',
 'been',
 'mistress',
 'of',
 'his',
 'house',
 'from',
 'a',
 'very',
 'early',
 'period.',
 'Her',
 'mother',
 'had',
 'died',
 'too',
 'long',
 'ago',
 'for',
 'her',
 'to',
 'have',
 'more',
 'than',
 'an',
 'indistinct',
 'remembrance',
 'of',
 'her',
 'caresses;',
 'and',
 'her',
 'place',
 'had',
 'been',
 'supplied',
 'by',
 'an',
 'excellent',
 'woman',
 'as',
 'governess,',
 'who',
 'had',
 'fallen',
 'little',
 'short',
 'of',
 'a',
 'mother',
 'in',
 'affection.',
 'Sixteen',
 'years',
 'had',
 'Miss',
 'Taylor',
 'been',
 'in',
 'Mr.',
 "Woodhouse's",
 'family,',
 'less',
 'as',
 'a',
 'governess',
 'than',
 'a',
 'friend,',
 'very',
 'fond',
 'of',
 'both',
 'daughters,',
 'but',
 'particularly',
 'of',
 'Emma.',
 'Between',
 '_them_',
 'it',
 'was',
 'more',
 'the',
 'intimacy',
 'of',
 'sisters.',
 'Even',
 'before',
 'Miss',
 'Taylor',
 'had',
 'ceased',
 'to',
 'hold',
 'the',
 'nominal',
 'office',
 'of',
 'governess,',
 'the',
 'mildness',
 'of',
 'her',
 'temper',
 'had',
 'hardly',
 'allowed',
 'her',
 'to',
 'impose',
 'any',
 'restraint;',
 'and',
 'the',
 'shadow',
 'of',
 'authority',
 'being',
 'now',
 'long',
 'passed',
 'away,',
 'they',
 'had',
 'been',
 'living',
 'together',
 'as',
 'friend',
 'and',
 'friend',
 'very',
 'mutually',
 'attached,',
 'and',
 'Emma',
 'doing',
 'just',
 'what',
 'she',
 'liked;',
 'highly',
 'esteeming',
 'Miss',
 "Taylor's",
 'judgment,',
 'but',
 'directed',
 'chiefly',
 'by',
 'her',
 'own.',
 'The',
 'real',
 'evils,',
 'indeed,',
 'of',
 "Emma's",
 'situation',
 'were',
 'the',
 'power',
 'of',
 'having',
 'rather',
 'too',
 'much',
 'her',
 'own',
 'way,',
 'and',
 'a',
 'disposition',
 'to',
 'think',
 'a',
 'little',
 'too',
 'well',
 'of',
 'herself;',
 'these',
 'were',
 'the',
 'disadvantages',
 'which',
 'threatened',
 'alloy',
 'to',
 'her',
 'many',
 'enjoyments.',
 'The',
 'danger,',
 'however,',
 'was',
 'at',
 'present',
 'so',
 'unperceived,',
 'that',
 'they',
 'did',
 'not',
 'by',
 'any',
 'means',
 'rank',
 'as',
 'misfortunes',
 'with',
 'her.',
 'Sorrow',
 'came--a',
 'gentle',
 'sorrow--but',
 'not',
 'at',
 'all',
 'in',
 'the',
 'shape',
 'of',
 'any',
 'disagreeable',
 'consciousness.--Miss',
 'Taylor',
 'married.',
 'It',
 'was',
 'Miss',
 "Taylor's",
 'loss',
 'which',
 'first',
 'brought',
 'grief.',
 'It',
 'was',
 'on',
 'the',
 'wedding-day',
 'of',
 'this',
 'beloved',
 'friend',
 'that',
 'Emma',
 'first',
 'sat',
 'in',
 'mournful',
 'thought',
 'of',
 'any',
 'continuance.',
 'The',
 'wedding',
 'over,',
 'and',
 'the',
 'bride-people',
 'gone,',
 'her',
 'father',
 'and',
 'herself',
 'were',
 'left',
 'to',
 'dine',
 'together,',
 'with',
 'no',
 'prospect',
 'of',
 'a',
 'third',
 'to',
 'cheer',
 'a',
 'long',
 'evening.',
 'Her',
 'father',
 'composed',
 'himself',
 'to',
 'sleep',
 'after',
 'dinner,',
 'as',
 'usual,',
 'and',
 'she',
 'had',
 'then',
 'only',
 'to',
 'sit',
 'and',
 'think',
 'of',
 'what',
 'she',
 'had',
 'lost.',
 'The',
 'event',
 'had',
 'every',
 'promise',
 'of',
 'happiness',
 'for',
 'her',
 'friend.',
 'Mr.',
 'Weston',
 'was',
 'a',
 'man',
 'of',
 'unexceptionable',
 'character,',
 'easy',
 'fortune,',
 'suitable',
 'age,',
 'and',
 'pleasant',
 'manners;',
 'and',
 'there',
 'was',
 'some',
 'satisfaction',
 'in',
 'considering',
 'with',
 'what',
 'self-denying,',
 'generous',
 'friendship',
 'she',
 'had',
 'always',
 'wished',
 'and',
 'promoted',
 'the',
 'match;',
 'but',
 'it',
 'was',
 'a',
 'black',
 "morning's",
 'work',
 'for',
 'her.',
 'The',
 'want',
 'of',
 'Miss',
 'Taylor',
 'would',
 'be',
 'felt',
 'every',
 'hour',
 'of',
 'every',
 'day.',
 'She',
 'recalled',
 'her',
 'past',
 'kindness--the',
 'kindness,',
 'the',
 'affection',
 'of',
 'sixteen',
 'years--how',
 'she',
 'had',
 'taught',
 'and',
 'how',
 'she',
 'had',
 'played',
 'with',
 'her',
 'from',
 'five',
 'years',
 'old--how',
 'she',
 'had',
 'devoted',
 'all',
 'her',
 'powers',
 'to',
 'attach',
 'and',
 'amuse',
 'her',
 'in',
 'health--and',
 'how',
 'nursed',
 'her',
 'through',
 'the',
 'various',
 'illnesses',
 'of',
 'childhood.',
 'A',
 'large',
 'debt',
 'of',
 'gratitude',
 'was',
 'owing',
 'here;',
 'but',
 'the',
 'intercourse',
 'of',
 'the',
 'last',
 'seven',
 'years,',
 'the',
 'equal',
 'footing',
 'and',
 'perfect',
 'unreserve',
 'which',
 'had',
 'soon',
 'followed',
 "Isabella's",
 'marriage,',
 'on',
 'their',
 'being',
 'left',
 'to',
 'each',
 'other,',
 'was',
 'yet',
 'a',
 'dearer,',
 'tenderer',
 'recollection.',
 'She',
 'had',
 'been',
 'a',
 'friend',
 'and',
 'companion',
 'such',
 'as',
 'few',
 'possessed:',
 'intelligent,',
 'well-informed,',
 'useful,',
 'gentle,',
 'knowing',
 'all',
 'the',
 'ways',
 'of',
 'the',
 'family,',
 'interested',
 'in',
 'all',
 'its',
 'concerns,',
 'and',
 'peculiarly',
 'interested',
 'in',
 'herself,',
 'in',
 'every',
 'pleasure,',
 'every',
 'scheme',
 'of',
 'hers--one',
 'to',
 'whom',
 'she',
 'could',
 'speak',
 'every',
 'thought',
 'as',
 'it',
 'arose,',
 'and',
 'who',
 'had',
 'such',
 'an',
 'affection',
 'for',
 'her',
 'as',
 'could',
 'never',
 'find',
 'fault.',
 'How',
 'was',
 'she',
 'to',
 'bear',
 'the',
 'change?--It',
 'was',
 'true',
 'that',
 'her',
 'friend',
 'was',
 'going',
 'only',
 'half',
 'a',
 'mile',
 'from',
 'them;',
 'but',
 'Emma',
 'was',
 'aware',
 'that',
 'great',
 'must',
 'be',
 'the',
 'difference',
 'between',
 'a',
 'Mrs.',
 'Weston,',
 'only',
 'half',
 'a',
 'mile',
 'from',
 'them,',
 'and',
 'a',
 'Miss',
 'Taylor',
 'in',
 'the',
 'house;',
 'and',
 'with',
 'all',
 'her',
 'advantages,',
 'natural',
 'and',
 'domestic,',
 'she',
 'was',
 'now',
 'in',
 'great',
 'danger',
 'of',
 'suffering',
 'from',
 'intellectual',
 'solitude.',
 'She',
 'dearly',
 'loved',
 'her',
 'father,',
 'but',
 'he',
 'was',
 'no',
 'companion',
 'for',
 'her.',
 'He',
 'could',
 'not',
 'meet',
 'her',
 'in',
 'conversation,',
 'rational',
 'or',
 'playful.',
 'The',
 'evil',
 'of',
 'the',
 'actual',
 'disparity',
 'in',
 'their',
 'ages',
 '(and',
 'Mr.',
 'Woodhouse',
 'had',
 'not',
 'married',
 'early)',
 'was',
 'much',
 'increased',
 'by',
 'his',
 'constitution',
 'and',
 'habits;',
 'for',
 'having',
 'been',
 'a',
 'valetudinarian',
 'all',
 'his',
 'life,',
 'without',
 'activity',
 'of',
 'mind',
 'or',
 'body,',
 'he',
 'was',
 'a',
 'much',
 'older',
 'man',
 'in',
 'ways',
 'than',
 'in',
 'years;',
 'and',
 'though',
 'everywhere',
 'beloved',
 'for',
 'the',
 'friendliness',
 'of',
 'his',
 'heart',
 'and',
 'his',
 'amiable',
 'temper,',
 'his',
 'talents',
 'could',
 'not',
 'have',
 'recommended',
 'him',
 'at',
 'any',
 'time.',
 'Her',
 'sister,',
 'though',
 'comparatively',
 'but',
 'little',
 'removed',
 'by',
 'matrimony,',
 'being',
 'settled',
 'in',
 'London,',
 'only',
 'sixteen',
 'miles',
 'off,',
 'was',
 'much',
 'beyond',
 'her',
 'daily',
 'reach;',
 'and',
 'many',
 'a',
 'long',
 'October',
 'and',
 'November',
 'evening',
 'must',
 'be',
 'struggled',
 'through',
 'at',
 'Hartfield,',
 'before',
 'Christmas',
 'brought',
 'the',
 'next',
 'visit',
 'from',
 'Isabella',
 'and',
 'her',
 'husband,',
 'and',
 'their',
 'little',
 'children,',
 'to',
 'fill',
 'the',
 'house,',
 'and',
 'give',
 'her',
 'pleasant',
 'society',
 'again.',
 'Highbury,',
 'the',
 'large',
 'and',
 'populous',
 'village,',
 'almost',
 'amounting',
 'to',
 'a',
 'town,',
 'to',
 'which',
 'Hartfield,',
 'in',
 'spite',
 'of',
 'its',
 'separate',
 'lawn,',
 'and',
 'shrubberies,',
 'and',
 'name,',
 'did',
 'really',
 'belong,',
 'afforded',
 'her',
 'no',
 'equals.',
 'The',
 'Woodhouses',
 'were',
 'first',
 'in',
 'consequence',
 'there.',
 'All',
 'looked',
 'up',
 'to',
 'them.',
 'She',
 'had',
 'many',
 'acquaintance',
 'in',
 'the',
 'place,',
 'for',
 'her',
 'father',
 'was',
 'universally',
 'civil,',
 'but',
 'not',
 'one',
 'among',
 'them',
 'who',
 'could',
 'be',
 'accepted',
 'in',
 'lieu',
 'of',
 'Miss',
 'Taylor',
 'for',
 'even',
 'half',
 'a',
 'day.',
 'It',
 'was',
 'a',
 'melancholy',
 'change;',
 'and',
 'Emma',
 'could',
 'not',
 'but',
 'sigh',
 'over',
 'it,',
 'and',
 'wish',
 'for',
 'impossible',
 'things,',
 'till',
 'her',
 'father',
 'awoke,',
 'and',
 'made',
 'it',
 'necessary',
 'to',
 'be',
 'cheerful.',
 'His',
 'spirits',
 'required',
 'support.',
 'He',
 'was',
 'a',
 'nervous',
 'man,',
 'easily',
 'depressed;',
 'fond',
 'of',
 'every',
 'body',
 'that',
 'he',
 'was',
 'used',
 'to,',
 'and',
 'hating',
 'to',
 'part',
 'with',
 'them;',
 'hating',
 'change',
 'of',
 'every',
 'kind.',
 'Matrimony,',
 'as',
 'the',
 'origin',
 'of',
 'change,',
 'was',
 'always',
 'disagreeable;',
 'and',
 'he',
 'was',
 'by',
 'no',
 'means',
 'yet',
 'reconciled',
 'to',
 'his',
 'own',
 "daughter's",
 'marrying,',
 'nor',
 'could',
 'ever',
 'speak',
 'of',
 'her',
 'but',
 'with',
 'compassion,',
 'though',
 'it',
 'had',
 'been',
 'entirely',
 'a',
 'match',
 'of',
 'affection,',
 'when',
 'he',
 'was',
 'now',
 'obliged',
 'to',
 'part',
 ...]

In [152]:
# Text Mining & Modeling Part I

In [153]:
# Fourth approach:
# derived classes for different types of word tokenization

# using an instance of WordPunktTokenizer class
# independent alphabetic and non-alphabetic tokens

# using WordPunktTokenizer function
wordpunct_wt = nltk.WordPunctTokenizer()

In [154]:
# using tokenize method
emma_words5 = wordpunct_wt.tokenize(emma)

In [155]:
emma_words5[0:500] # similar to output3

['[',
 'Emma',
 'by',
 'Jane',
 'Austen',
 '1816',
 ']',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse',
 ',',
 'handsome',
 ',',
 'clever',
 ',',
 'and',
 'rich',
 ',',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition',
 ',',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence',
 ';',
 'and',
 'had',
 'lived',
 'nearly',
 'twenty',
 '-',
 'one',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her',
 '.',
 'She',
 'was',
 'the',
 'youngest',
 'of',
 'the',
 'two',
 'daughters',
 'of',
 'a',
 'most',
 'affectionate',
 ',',
 'indulgent',
 'father',
 ';',
 'and',
 'had',
 ',',
 'in',
 'consequence',
 'of',
 'her',
 'sister',
 "'",
 's',
 'marriage',
 ',',
 'been',
 'mistress',
 'of',
 'his',
 'house',
 'from',
 'a',
 'very',
 'early',
 'period',
 '.',
 'Her',
 'mother',
 'had',
 'died',
 'too',
 'long',
 'ago',
 'for',
 'her',
 'to',
 'have',
 'more',
 'than',
 'an',
 'indistinct',
 'remembrance',
 'of',
 'her',
 'caresses',
 ';',
 'and',
 'her',
 'place',
 'had',
 'been',
 'supplied',
 'by',
 'an',
 'excellent',
 'woman',
 'as',
 'governess',
 ',',
 'who',
 'had',
 'fallen',
 'little',
 'short',
 'of',
 'a',
 'mother',
 'in',
 'affection',
 '.',
 'Sixteen',
 'years',
 'had',
 'Miss',
 'Taylor',
 'been',
 'in',
 'Mr',
 '.',
 'Woodhouse',
 "'",
 's',
 'family',
 ',',
 'less',
 'as',
 'a',
 'governess',
 'than',
 'a',
 'friend',
 ',',
 'very',
 'fond',
 'of',
 'both',
 'daughters',
 ',',
 'but',
 'particularly',
 'of',
 'Emma',
 '.',
 'Between',
 '_them_',
 'it',
 'was',
 'more',
 'the',
 'intimacy',
 'of',
 'sisters',
 '.',
 'Even',
 'before',
 'Miss',
 'Taylor',
 'had',
 'ceased',
 'to',
 'hold',
 'the',
 'nominal',
 'office',
 'of',
 'governess',
 ',',
 'the',
 'mildness',
 'of',
 'her',
 'temper',
 'had',
 'hardly',
 'allowed',
 'her',
 'to',
 'impose',
 'any',
 'restraint',
 ';',
 'and',
 'the',
 'shadow',
 'of',
 'authority',
 'being',
 'now',
 'long',
 'passed',
 'away',
 ',',
 'they',
 'had',
 'been',
 'living',
 'together',
 'as',
 'friend',
 'and',
 'friend',
 'very',
 'mutually',
 'attached',
 ',',
 'and',
 'Emma',
 'doing',
 'just',
 'what',
 'she',
 'liked',
 ';',
 'highly',
 'esteeming',
 'Miss',
 'Taylor',
 "'",
 's',
 'judgment',
 ',',
 'but',
 'directed',
 'chiefly',
 'by',
 'her',
 'own',
 '.',
 'The',
 'real',
 'evils',
 ',',
 'indeed',
 ',',
 'of',
 'Emma',
 "'",
 's',
 'situation',
 'were',
 'the',
 'power',
 'of',
 'having',
 'rather',
 'too',
 'much',
 'her',
 'own',
 'way',
 ',',
 'and',
 'a',
 'disposition',
 'to',
 'think',
 'a',
 'little',
 'too',
 'well',
 'of',
 'herself',
 ';',
 'these',
 'were',
 'the',
 'disadvantages',
 'which',
 'threatened',
 'alloy',
 'to',
 'her',
 'many',
 'enjoyments',
 '.',
 'The',
 'danger',
 ',',
 'however',
 ',',
 'was',
 'at',
 'present',
 'so',
 'unperceived',
 ',',
 'that',
 'they',
 'did',
 'not',
 'by',
 'any',
 'means',
 'rank',
 'as',
 'misfortunes',
 'with',
 'her',
 '.',
 'Sorrow',
 'came',
 '--',
 'a',
 'gentle',
 'sorrow',
 '--',
 'but',
 'not',
 'at',
 'all',
 'in',
 'the',
 'shape',
 'of',
 'any',
 'disagreeable',
 'consciousness',
 '.--',
 'Miss',
 'Taylor',
 'married',
 '.',
 'It',
 'was',
 'Miss',
 'Taylor',
 "'",
 's',
 'loss',
 'which',
 'first',
 'brought',
 'grief',
 '.',
 'It',
 'was',
 'on',
 'the',
 'wedding',
 '-',
 'day',
 'of',
 'this',
 'beloved',
 'friend',
 'that',
 'Emma',
 'first',
 'sat',
 'in',
 'mournful',
 'thought',
 'of',
 'any',
 'continuance',
 '.',
 'The',
 'wedding',
 'over',
 ',',
 'and',
 'the',
 'bride',
 '-',
 'people',
 'gone',
 ',',
 'her',
 'father',
 'and',
 'herself',
 'were',
 'left',
 'to',
 'dine',
 'together',
 ',',
 'with',
 'no',
 'prospect',
 'of',
 'a',
 'third',
 'to',
 'cheer',
 'a',
 'long',
 'evening',
 '.',
 'Her',
 'father',
 'composed',
 'himself',
 'to',
 'sleep',
 'after',
 'dinner',
 ',',
 'as',
 'usual',
 ',',
 'and',
 'she',
 'had',
 'then',
 'only',
 'to',
 'sit',
 'and',
 'think',
 'of',
 'what',
 'she',
 'had',
 'lost',
 '.',
 'The',
 'event',
 'had',
 'every',
 'promise',
 'of',
 'happiness',
 'for',
 'her',
 'friend',
 '.',
 'Mr',
 '.',
 'Weston',
 'was',
 'a',
 'man',
 'of',
 'unexceptionable',
 'character',
 ',',
 'easy',
 'fortune',
 ',',
 'suitable',
 'age',
 ',',
 'and',
 'pleasant',
 'manners',
 ';',
 'and',
 'there',
 'was',
 'some',
 'satisfaction',
 'in',
 'considering',
 'with',
 'what',
 'self',
 '-',
 'denying',
 ',',
 'generous',
 'friendship',
 'she',
 'had',
 'always',
 'wished',
 'and']

In [156]:
# using an instance of WhitespaceTokenizer class
# based on whitespaces

# using WhitespaceTokenizer function
whitespace_wt = nltk.WhitespaceTokenizer()

In [157]:
# using tokenize method
emma_words6 = whitespace_wt.tokenize(emma)

In [158]:
emma_words6[0:500] # similar to output3

['[Emma',
 'by',
 'Jane',
 'Austen',
 '1816]',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse,',
 'handsome,',
 'clever,',
 'and',
 'rich,',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition,',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence;',
 'and',
 'had',
 'lived',
 'nearly',
 'twenty-one',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her.',
 'She',
 'was',
 'the',
 'youngest',
 'of',
 'the',
 'two',
 'daughters',
 'of',
 'a',
 'most',
 'affectionate,',
 'indulgent',
 'father;',
 'and',
 'had,',
 'in',
 'consequence',
 'of',
 'her',
 "sister's",
 'marriage,',
 'been',
 'mistress',
 'of',
 'his',
 'house',
 'from',
 'a',
 'very',
 'early',
 'period.',
 'Her',
 'mother',
 'had',
 'died',
 'too',
 'long',
 'ago',
 'for',
 'her',
 'to',
 'have',
 'more',
 'than',
 'an',
 'indistinct',
 'remembrance',
 'of',
 'her',
 'caresses;',
 'and',
 'her',
 'place',
 'had',
 'been',
 'supplied',
 'by',
 'an',
 'excellent',
 'woman',
 'as',
 'governess,',
 'who',
 'had',
 'fallen',
 'little',
 'short',
 'of',
 'a',
 'mother',
 'in',
 'affection.',
 'Sixteen',
 'years',
 'had',
 'Miss',
 'Taylor',
 'been',
 'in',
 'Mr.',
 "Woodhouse's",
 'family,',
 'less',
 'as',
 'a',
 'governess',
 'than',
 'a',
 'friend,',
 'very',
 'fond',
 'of',
 'both',
 'daughters,',
 'but',
 'particularly',
 'of',
 'Emma.',
 'Between',
 '_them_',
 'it',
 'was',
 'more',
 'the',
 'intimacy',
 'of',
 'sisters.',
 'Even',
 'before',
 'Miss',
 'Taylor',
 'had',
 'ceased',
 'to',
 'hold',
 'the',
 'nominal',
 'office',
 'of',
 'governess,',
 'the',
 'mildness',
 'of',
 'her',
 'temper',
 'had',
 'hardly',
 'allowed',
 'her',
 'to',
 'impose',
 'any',
 'restraint;',
 'and',
 'the',
 'shadow',
 'of',
 'authority',
 'being',
 'now',
 'long',
 'passed',
 'away,',
 'they',
 'had',
 'been',
 'living',
 'together',
 'as',
 'friend',
 'and',
 'friend',
 'very',
 'mutually',
 'attached,',
 'and',
 'Emma',
 'doing',
 'just',
 'what',
 'she',
 'liked;',
 'highly',
 'esteeming',
 'Miss',
 "Taylor's",
 'judgment,',
 'but',
 'directed',
 'chiefly',
 'by',
 'her',
 'own.',
 'The',
 'real',
 'evils,',
 'indeed,',
 'of',
 "Emma's",
 'situation',
 'were',
 'the',
 'power',
 'of',
 'having',
 'rather',
 'too',
 'much',
 'her',
 'own',
 'way,',
 'and',
 'a',
 'disposition',
 'to',
 'think',
 'a',
 'little',
 'too',
 'well',
 'of',
 'herself;',
 'these',
 'were',
 'the',
 'disadvantages',
 'which',
 'threatened',
 'alloy',
 'to',
 'her',
 'many',
 'enjoyments.',
 'The',
 'danger,',
 'however,',
 'was',
 'at',
 'present',
 'so',
 'unperceived,',
 'that',
 'they',
 'did',
 'not',
 'by',
 'any',
 'means',
 'rank',
 'as',
 'misfortunes',
 'with',
 'her.',
 'Sorrow',
 'came--a',
 'gentle',
 'sorrow--but',
 'not',
 'at',
 'all',
 'in',
 'the',
 'shape',
 'of',
 'any',
 'disagreeable',
 'consciousness.--Miss',
 'Taylor',
 'married.',
 'It',
 'was',
 'Miss',
 "Taylor's",
 'loss',
 'which',
 'first',
 'brought',
 'grief.',
 'It',
 'was',
 'on',
 'the',
 'wedding-day',
 'of',
 'this',
 'beloved',
 'friend',
 'that',
 'Emma',
 'first',
 'sat',
 'in',
 'mournful',
 'thought',
 'of',
 'any',
 'continuance.',
 'The',
 'wedding',
 'over,',
 'and',
 'the',
 'bride-people',
 'gone,',
 'her',
 'father',
 'and',
 'herself',
 'were',
 'left',
 'to',
 'dine',
 'together,',
 'with',
 'no',
 'prospect',
 'of',
 'a',
 'third',
 'to',
 'cheer',
 'a',
 'long',
 'evening.',
 'Her',
 'father',
 'composed',
 'himself',
 'to',
 'sleep',
 'after',
 'dinner,',
 'as',
 'usual,',
 'and',
 'she',
 'had',
 'then',
 'only',
 'to',
 'sit',
 'and',
 'think',
 'of',
 'what',
 'she',
 'had',
 'lost.',
 'The',
 'event',
 'had',
 'every',
 'promise',
 'of',
 'happiness',
 'for',
 'her',
 'friend.',
 'Mr.',
 'Weston',
 'was',
 'a',
 'man',
 'of',
 'unexceptionable',
 'character,',
 'easy',
 'fortune,',
 'suitable',
 'age,',
 'and',
 'pleasant',
 'manners;',
 'and',
 'there',
 'was',
 'some',
 'satisfaction',
 'in',
 'considering',
 'with',
 'what',
 'self-denying,',
 'generous',
 'friendship',
 'she',
 'had',
 'always',
 'wished',
 'and',
 'promoted',
 'the',
 'match;',
 'but',
 'it',
 'was',
 'a',
 'black',
 "morning's",
 'work',
 'for',
 'her.',
 'The',
 'want',
 'of',
 'Miss',
 'Taylor',
 'would',
 'be',
 'felt',
 'every',
 'hour',
 'of',
 'every',
 'day.',
 'She',
 'recalled',
 'her',
 'past',
 'kindness--the',
 'kindness,',
 'the',
 'affection',
 'of',
 'sixteen',
 'years--how',
 'she',
 'had',
 'taught',
 'and',
 'how',
 'she',
 'had',
 'played',
 'with',
 'her',
 'from',
 'five',
 'years',
 'old--how',
 'she',
 'had',
 'devoted',
 'all',
 'her',
 'powers',
 'to',
 'attach',
 'and',
 'amuse',
 'her',
 'in',
 'health--and',
 'how',
 'nursed',
 'her',
 'through',
 'the',
 'various',
 'illnesses',
 'of',
 'childhood.',
 'A',
 'large',
 'debt',
 'of',
 'gratitude',
 'was',
 'owing',
 'here;']

In [159]:
## removing special characters ##
# Load required Libraries
import re
import string

## after tokenization

# create a regex pattern using string.punctuation attribute, which consists of all possible special characters/symbols
# using escape function to escape the special characters
# using fromat method to copy the pattern string in the replacement field delimited by (}
pattern4 = re.compile('[{}]'.format(re.escape(string.punctuation)))

In [160]:
# using a List comprehension based on sub method to find all matching tokens as per the pattern
# and replace them with empty string

# using filter function to remove empty tokens
emma_words_f = list(filter(None, [pattern4.sub('', token) for token in emma_words]))

In [161]:
emma_words_f[0:500]

['Emma',
 'by',
 'Jane',
 'Austen',
 '1816',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse',
 'handsome',
 'clever',
 'and',
 'rich',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence',
 'and',
 'had',
 'lived',
 'nearly',
 'twentyone',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her',
 'She',
 'was',
 'the',
 'youngest',
 'of',
 'the',
 'two',
 'daughters',
 'of',
 'a',
 'most',
 'affectionate',
 'indulgent',
 'father',
 'and',
 'had',
 'in',
 'consequence',
 'of',
 'her',
 'sister',
 's',
 'marriage',
 'been',
 'mistress',
 'of',
 'his',
 'house',
 'from',
 'a',
 'very',
 'early',
 'period',
 'Her',
 'mother',
 'had',
 'died',
 'too',
 'long',
 'ago',
 'for',
 'her',
 'to',
 'have',
 'more',
 'than',
 'an',
 'indistinct',
 'remembrance',
 'of',
 'her',
 'caresses',
 'and',
 'her',
 'place',
 'had',
 'been',
 'supplied',
 'by',
 'an',
 'excellent',
 'woman',
 'as',
 'governess',
 'who',
 'had',
 'fallen',
 'little',
 'short',
 'of',
 'a',
 'mother',
 'in',
 'affection',
 'Sixteen',
 'years',
 'had',
 'Miss',
 'Taylor',
 'been',
 'in',
 'Mr',
 'Woodhouse',
 's',
 'family',
 'less',
 'as',
 'a',
 'governess',
 'than',
 'a',
 'friend',
 'very',
 'fond',
 'of',
 'both',
 'daughters',
 'but',
 'particularly',
 'of',
 'Emma',
 'Between',
 'them',
 'it',
 'was',
 'more',
 'the',
 'intimacy',
 'of',
 'sisters',
 'Even',
 'before',
 'Miss',
 'Taylor',
 'had',
 'ceased',
 'to',
 'hold',
 'the',
 'nominal',
 'office',
 'of',
 'governess',
 'the',
 'mildness',
 'of',
 'her',
 'temper',
 'had',
 'hardly',
 'allowed',
 'her',
 'to',
 'impose',
 'any',
 'restraint',
 'and',
 'the',
 'shadow',
 'of',
 'authority',
 'being',
 'now',
 'long',
 'passed',
 'away',
 'they',
 'had',
 'been',
 'living',
 'together',
 'as',
 'friend',
 'and',
 'friend',
 'very',
 'mutually',
 'attached',
 'and',
 'Emma',
 'doing',
 'just',
 'what',
 'she',
 'liked',
 'highly',
 'esteeming',
 'Miss',
 'Taylor',
 's',
 'judgment',
 'but',
 'directed',
 'chiefly',
 'by',
 'her',
 'own',
 'The',
 'real',
 'evils',
 'indeed',
 'of',
 'Emma',
 's',
 'situation',
 'were',
 'the',
 'power',
 'of',
 'having',
 'rather',
 'too',
 'much',
 'her',
 'own',
 'way',
 'and',
 'a',
 'disposition',
 'to',
 'think',
 'a',
 'little',
 'too',
 'well',
 'of',
 'herself',
 'these',
 'were',
 'the',
 'disadvantages',
 'which',
 'threatened',
 'alloy',
 'to',
 'her',
 'many',
 'enjoyments',
 'The',
 'danger',
 'however',
 'was',
 'at',
 'present',
 'so',
 'unperceived',
 'that',
 'they',
 'did',
 'not',
 'by',
 'any',
 'means',
 'rank',
 'as',
 'misfortunes',
 'with',
 'her',
 'Sorrow',
 'came',
 'a',
 'gentle',
 'sorrow',
 'but',
 'not',
 'at',
 'all',
 'in',
 'the',
 'shape',
 'of',
 'any',
 'disagreeable',
 'consciousness',
 'Miss',
 'Taylor',
 'married',
 'It',
 'was',
 'Miss',
 'Taylor',
 's',
 'loss',
 'which',
 'first',
 'brought',
 'grief',
 'It',
 'was',
 'on',
 'the',
 'weddingday',
 'of',
 'this',
 'beloved',
 'friend',
 'that',
 'Emma',
 'first',
 'sat',
 'in',
 'mournful',
 'thought',
 'of',
 'any',
 'continuance',
 'The',
 'wedding',
 'over',
 'and',
 'the',
 'bridepeople',
 'gone',
 'her',
 'father',
 'and',
 'herself',
 'were',
 'left',
 'to',
 'dine',
 'together',
 'with',
 'no',
 'prospect',
 'of',
 'a',
 'third',
 'to',
 'cheer',
 'a',
 'long',
 'evening',
 'Her',
 'father',
 'composed',
 'himself',
 'to',
 'sleep',
 'after',
 'dinner',
 'as',
 'usual',
 'and',
 'she',
 'had',
 'then',
 'only',
 'to',
 'sit',
 'and',
 'think',
 'of',
 'what',
 'she',
 'had',
 'lost',
 'The',
 'event',
 'had',
 'every',
 'promise',
 'of',
 'happiness',
 'for',
 'her',
 'friend',
 'Mr',
 'Weston',
 'was',
 'a',
 'man',
 'of',
 'unexceptionable',
 'character',
 'easy',
 'fortune',
 'suitable',
 'age',
 'and',
 'pleasant',
 'manners',
 'and',
 'there',
 'was',
 'some',
 'satisfaction',
 'in',
 'considering',
 'with',
 'what',
 'selfdenying',
 'generous',
 'friendship',
 'she',
 'had',
 'always',
 'wished',
 'and',
 'promoted',
 'the',
 'match',
 'but',
 'it',
 'was',
 'a',
 'black',
 'morning',
 's',
 'work',
 'for',
 'her',
 'The',
 'want',
 'of',
 'Miss',
 'Taylor',
 'would',
 'be',
 'felt',
 'every',
 'hour',
 'of',
 'every',
 'day',
 'She',
 'recalled',
 'her',
 'past',
 'kindness',
 'the',
 'kindness',
 'the',
 'affection',
 'of',
 'sixteen',
 'years',
 'how',
 'she',
 'had',
 'taught',
 'and',
 'how',
 'she',
 'had',
 'played',
 'with',
 'her',
 'from',
 'five',
 'years',
 'old',
 'how',
 'she',
 'had',
 'devoted',
 'all',
 'her',
 'powers',
 'to',
 'attach',
 'and',
 'amuse',
 'her',
 'in',
 'health',
 'and',
 'how',
 'nursed',
 'her',
 'through']

In [162]:
emma_words[0:500]

['[',
 'Emma',
 'by',
 'Jane',
 'Austen',
 '1816',
 ']',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse',
 ',',
 'handsome',
 ',',
 'clever',
 ',',
 'and',
 'rich',
 ',',
 'with',
 'a',
 'comfortable',
 'home',
 'and',
 'happy',
 'disposition',
 ',',
 'seemed',
 'to',
 'unite',
 'some',
 'of',
 'the',
 'best',
 'blessings',
 'of',
 'existence',
 ';',
 'and',
 'had',
 'lived',
 'nearly',
 'twenty-one',
 'years',
 'in',
 'the',
 'world',
 'with',
 'very',
 'little',
 'to',
 'distress',
 'or',
 'vex',
 'her',
 '.',
 'She',
 'was',
 'the',
 'youngest',
 'of',
 'the',
 'two',
 'daughters',
 'of',
 'a',
 'most',
 'affectionate',
 ',',
 'indulgent',
 'father',
 ';',
 'and',
 'had',
 ',',
 'in',
 'consequence',
 'of',
 'her',
 'sister',
 "'s",
 'marriage',
 ',',
 'been',
 'mistress',
 'of',
 'his',
 'house',
 'from',
 'a',
 'very',
 'early',
 'period',
 '.',
 'Her',
 'mother',
 'had',
 'died',
 'too',
 'long',
 'ago',
 'for',
 'her',
 'to',
 'have',
 'more',
 'than',
 'an',
 'indistinct',
 'remembrance',
 'of',
 'her',
 'caresses',
 ';',
 'and',
 'her',
 'place',
 'had',
 'been',
 'supplied',
 'by',
 'an',
 'excellent',
 'woman',
 'as',
 'governess',
 ',',
 'who',
 'had',
 'fallen',
 'little',
 'short',
 'of',
 'a',
 'mother',
 'in',
 'affection',
 '.',
 'Sixteen',
 'years',
 'had',
 'Miss',
 'Taylor',
 'been',
 'in',
 'Mr.',
 'Woodhouse',
 "'s",
 'family',
 ',',
 'less',
 'as',
 'a',
 'governess',
 'than',
 'a',
 'friend',
 ',',
 'very',
 'fond',
 'of',
 'both',
 'daughters',
 ',',
 'but',
 'particularly',
 'of',
 'Emma',
 '.',
 'Between',
 '_them_',
 'it',
 'was',
 'more',
 'the',
 'intimacy',
 'of',
 'sisters',
 '.',
 'Even',
 'before',
 'Miss',
 'Taylor',
 'had',
 'ceased',
 'to',
 'hold',
 'the',
 'nominal',
 'office',
 'of',
 'governess',
 ',',
 'the',
 'mildness',
 'of',
 'her',
 'temper',
 'had',
 'hardly',
 'allowed',
 'her',
 'to',
 'impose',
 'any',
 'restraint',
 ';',
 'and',
 'the',
 'shadow',
 'of',
 'authority',
 'being',
 'now',
 'long',
 'passed',
 'away',
 ',',
 'they',
 'had',
 'been',
 'living',
 'together',
 'as',
 'friend',
 'and',
 'friend',
 'very',
 'mutually',
 'attached',
 ',',
 'and',
 'Emma',
 'doing',
 'just',
 'what',
 'she',
 'liked',
 ';',
 'highly',
 'esteeming',
 'Miss',
 'Taylor',
 "'s",
 'judgment',
 ',',
 'but',
 'directed',
 'chiefly',
 'by',
 'her',
 'own',
 '.',
 'The',
 'real',
 'evils',
 ',',
 'indeed',
 ',',
 'of',
 'Emma',
 "'s",
 'situation',
 'were',
 'the',
 'power',
 'of',
 'having',
 'rather',
 'too',
 'much',
 'her',
 'own',
 'way',
 ',',
 'and',
 'a',
 'disposition',
 'to',
 'think',
 'a',
 'little',
 'too',
 'well',
 'of',
 'herself',
 ';',
 'these',
 'were',
 'the',
 'disadvantages',
 'which',
 'threatened',
 'alloy',
 'to',
 'her',
 'many',
 'enjoyments',
 '.',
 'The',
 'danger',
 ',',
 'however',
 ',',
 'was',
 'at',
 'present',
 'so',
 'unperceived',
 ',',
 'that',
 'they',
 'did',
 'not',
 'by',
 'any',
 'means',
 'rank',
 'as',
 'misfortunes',
 'with',
 'her',
 '.',
 'Sorrow',
 'came',
 '--',
 'a',
 'gentle',
 'sorrow',
 '--',
 'but',
 'not',
 'at',
 'all',
 'in',
 'the',
 'shape',
 'of',
 'any',
 'disagreeable',
 'consciousness.',
 '--',
 'Miss',
 'Taylor',
 'married',
 '.',
 'It',
 'was',
 'Miss',
 'Taylor',
 "'s",
 'loss',
 'which',
 'first',
 'brought',
 'grief',
 '.',
 'It',
 'was',
 'on',
 'the',
 'wedding-day',
 'of',
 'this',
 'beloved',
 'friend',
 'that',
 'Emma',
 'first',
 'sat',
 'in',
 'mournful',
 'thought',
 'of',
 'any',
 'continuance',
 '.',
 'The',
 'wedding',
 'over',
 ',',
 'and',
 'the',
 'bride-people',
 'gone',
 ',',
 'her',
 'father',
 'and',
 'herself',
 'were',
 'left',
 'to',
 'dine',
 'together',
 ',',
 'with',
 'no',
 'prospect',
 'of',
 'a',
 'third',
 'to',
 'cheer',
 'a',
 'long',
 'evening',
 '.',
 'Her',
 'father',
 'composed',
 'himself',
 'to',
 'sleep',
 'after',
 'dinner',
 ',',
 'as',
 'usual',
 ',',
 'and',
 'she',
 'had',
 'then',
 'only',
 'to',
 'sit',
 'and',
 'think',
 'of',
 'what',
 'she',
 'had',
 'lost',
 '.',
 'The',
 'event',
 'had',
 'every',
 'promise',
 'of',
 'happiness',
 'for',
 'her',
 'friend',
 '.',
 'Mr.',
 'Weston',
 'was',
 'a',
 'man',
 'of',
 'unexceptionable',
 'character',
 ',',
 'easy',
 'fortune',
 ',',
 'suitable',
 'age',
 ',',
 'and',
 'pleasant',
 'manners',
 ';',
 'and',
 'there',
 'was',
 'some',
 'satisfaction',
 'in',
 'considering',
 'with',
 'what',
 'self-denying',
 ',',
 'generous',
 'friendship',
 'she',
 'had',
 'always',
 'wished',
 'and',
 'promoted',
 'the',
 'match',
 ';',
 'but',
 'it',
 'was',
 'a',
 'black',
 'morning',
 "'s",
 'work',
 'for',
 'her',
 '.']

In [163]:
## before tokenization

# First approach:
# create a regex pattern to only extract alpha-numeric characters
# add characters to be retained
pattern5 = r'[^a-zA-Z0-9 ]'

In [164]:
# using strip method to remove whitespaces

# using a list comprehension based on sub method to find all matching tokens as per the pattern
# and replace them with empty string

emma_f = [re.sub(pattern5, r'', sentence.strip()) for sentence in emma_sents]

In [165]:
emma_f[0:500]

['Emma by Jane Austen 1816VOLUME ICHAPTER IEmma Woodhouse handsome clever and rich with a comfortable homeand happy disposition seemed to unite some of the best blessingsof existence and had lived nearly twentyone years in the worldwith very little to distress or vex her',
 'She was the youngest of the two daughters of a most affectionateindulgent father and had in consequence of her sisters marriagebeen mistress of his house from a very early period',
 'Her motherhad died too long ago for her to have more than an indistinctremembrance of her caresses and her place had been suppliedby an excellent woman as governess who had fallen little shortof a mother in affection',
 'Sixteen years had Miss Taylor been in Mr Woodhouses familyless as a governess than a friend very fond of both daughtersbut particularly of Emma',
 'Between them it was more the intimacyof sisters',
 'Even before Miss Taylor had ceased to hold the nominaloffice of governess the mildness of her temper had hardly allowedher to impose any restraint and the shadow of authority beingnow long passed away they had been living together as friend andfriend very mutually attached and Emma doing just what she likedhighly esteeming Miss Taylors judgment but directed chiefly byher own',
 'The real evils indeed of Emmas situation were the power of havingrather too much her own way and a disposition to think a littletoo well of herself these were the disadvantages which threatenedalloy to her many enjoyments',
 'The danger however was at presentso unperceived that they did not by any means rank as misfortuneswith her',
 'Sorrow camea gentle sorrowbut not at all in the shape of anydisagreeable consciousnessMiss Taylor married',
 'It was MissTaylors loss which first brought grief',
 'It was on the weddingdayof this beloved friend that Emma first sat in mournful thoughtof any continuance',
 'The wedding over and the bridepeople goneher father and herself were left to dine together with no prospectof a third to cheer a long evening',
 'Her father composed himselfto sleep after dinner as usual and she had then only to sitand think of what she had lost',
 'The event had every promise of happiness for her friend',
 'Mr Westonwas a man of unexceptionable character easy fortune suitable ageand pleasant manners and there was some satisfaction in consideringwith what selfdenying generous friendship she had always wishedand promoted the match but it was a black mornings work for her',
 'The want of Miss Taylor would be felt every hour of every day',
 'She recalled her past kindnessthe kindness the affection of sixteenyearshow she had taught and how she had played with her from fiveyears oldhow she had devoted all her powers to attach and amuseher in healthand how nursed her through the various illnessesof childhood',
 'A large debt of gratitude was owing here but theintercourse of the last seven years the equal footing and perfectunreserve which had soon followed Isabellas marriage on theirbeing left to each other was yet a dearer tenderer recollection',
 'She had been a friend and companion such as few possessed intelligentwellinformed useful gentle knowing all the ways of the familyinterested in all its concerns and peculiarly interested in herselfin every pleasure every scheme of hersone to whom she could speakevery thought as it arose and who had such an affection for heras could never find fault',
 'How was she to bear the changeIt was true that her friend wasgoing only half a mile from them but Emma was aware that great mustbe the difference between a Mrs Weston only half a mile from themand a Miss Taylor in the house and with all her advantagesnatural and domestic she was now in great danger of sufferingfrom intellectual solitude',
 'She dearly loved her father but hewas no companion for her',
 'He could not meet her in conversationrational or playful',
 'The evil of the actual disparity in their ages and Mr Woodhouse hadnot married early was much increased by his constitution and habitsfor having been a valetudinarian all his life without activityof mind or body he was a much older man in ways than in yearsand though everywhere beloved for the friendliness of his heartand his amiable temper his talents could not have recommended himat any time',
 'Her sister though comparatively but little removed by matrimonybeing settled in London only sixteen miles off was much beyondher daily reach and many a long October and November evening mustbe struggled through at Hartfield before Christmas brought the nextvisit from Isabella and her husband and their little childrento fill the house and give her pleasant society again',
 'Highbury the large and populous village almost amounting to a townto which Hartfield in spite of its separate lawn and shrubberiesand name did really belong afforded her no equals',
 'The Woodhouseswere first in consequence there',
 'All looked up to them',
 'She hadmany acquaintance in the place for her father was universally civilbut not one among them who could be accepted in lieu of MissTaylor for even half a day',
 'It was a melancholy change and Emmacould not but sigh over it and wish for impossible thingstill her father awoke and made it necessary to be cheerful',
 'His spirits required support',
 'He was a nervous man easily depressedfond of every body that he was used to and hating to part with themhating change of every kind',
 'Matrimony as the origin of changewas always disagreeable and he was by no means yet reconciledto his own daughters marrying nor could ever speak of her butwith compassion though it had been entirely a match of affectionwhen he was now obliged to part with Miss Taylor too and fromhis habits of gentle selfishness and of being never able tosuppose that other people could feel differently from himselfhe was very much disposed to think Miss Taylor had done as sada thing for herself as for them and would have been a great dealhappier if she had spent all the rest of her life at Hartfield',
 'Emma smiled and chatted as cheerfully as she could to keep himfrom such thoughts but when tea came it was impossible for himnot to say exactly as he had said at dinnerPoor Miss TaylorI wish she were here again',
 'What a pity itis that Mr Weston ever thought of her',
 'I cannot agree with you papa you know I cannot',
 'Mr Weston is sucha goodhumoured pleasant excellent man that he thoroughly deservesa good wifeand you would not have had Miss Taylor live with usfor ever and bear all my odd humours when she might have a house of her own',
 'A house of her ownBut where is the advantage of a house of her own',
 'This is three times as largeAnd you have never any odd humoursmy dear',
 'How often we shall be going to see them and they coming to seeusWe shall be always meeting',
 'We must begin we must go and paywedding visit very soon',
 'My dear how am I to get so far',
 'Randalls is such a distance',
 'I could not walk half so far',
 'No papa nobody thought of your walking',
 'We must go in the carriageto be sure',
 'The carriage',
 'But James will not like to put the horses to forsuch a little wayand where are the poor horses to be while weare paying our visit',
 'They are to be put into Mr Westons stable papa',
 'You know wehave settled all that already',
 'We talked it all over with Mr Westonlast night',
 'And as for James you may be very sure he will always likegoing to Randalls because of his daughters being housemaid there',
 'I only doubt whether he will ever take us anywhere else',
 'That wasyour doing papa',
 'You got Hannah that good place',
 'Nobody thoughtof Hannah till you mentioned herJames is so obliged to you',
 'I am very glad I did think of her',
 'It was very lucky for I wouldnot have had poor James think himself slighted upon any accountand I am sure she will make a very good servant she is a civilprettyspoken girl I have a great opinion of her',
 'Whenever I see hershe always curtseys and asks me how I do in a very pretty mannerand when you have had her here to do needlework I observe shealways turns the lock of the door the right way and never bangs it',
 'I am sure she will be an excellent servant and it will be a greatcomfort to poor Miss Taylor to have somebody about her that she isused to see',
 'Whenever James goes over to see his daughter you knowshe will be hearing of us',
 'He will be able to tell her how weall are',
 'Emma spared no exertions to maintain this happier flow of ideasand hoped by the help of backgammon to get her father tolerablythrough the evening and be attacked by no regrets but her own',
 'The backgammontable was placed but a visitor immediately afterwardswalked in and made it unnecessary',
 'Mr Knightley a sensible man about seven or eightandthirty was notonly a very old and intimate friend of the family but particularlyconnected with it as the elder brother of Isabellas husband',
 'He lived about a mile from Highbury was a frequent visitorand always welcome and at this time more welcome than usualas coming directly from their mutual connexions in London',
 'He hadreturned to a late dinner after some days absence and now walkedup to Hartfield to say that all were well in Brunswick Square',
 'It was a happy circumstance and animated Mr Woodhouse for some time',
 'Mr Knightley had a cheerful manner which always did him goodand his many inquiries after poor Isabella and her children wereanswered most satisfactorily',
 'When this was over Mr Woodhousegratefully observed It is very kind of you Mr Knightley to comeout at this late hour to call upon us',
 'I am afraid you must havehad a shocking walk',
 'Not at all sir',
 'It is a beautiful moonlight night and so mildthat I must draw back from your great fire',
 'But you must have found it very damp and dirty',
 'I wish you maynot catch cold',
 'Dirty sir',
 'Look at my shoes',
 'Not a speck on them',
 'Well',
 'that is quite surprising for we have had a vast dealof rain here',
 'It rained dreadfully hard for half an hourwhile we were at breakfast',
 'I wanted them to put off the wedding',
 'By the byeI have not wished you joy',
 'Being pretty well awareof what sort of joy you must both be feeling I have been in no hurrywith my congratulations but I hope it all went off tolerably well',
 'How did you all behave',
 'Who cried most',
 'Ah',
 'poor Miss Taylor',
 'Tis a sad business',
 'Poor Mr and Miss Woodhouse if you please but I cannot possiblysay poor Miss Taylor',
 'I have a great regard for you and Emmabut when it comes to the question of dependence or independenceAtany rate it must be better to have only one to please than two',
 'Especially when one of those two is such a fanciful troublesome creature',
 'said Emma playfully',
 'That is what you have in your headI knowand what you would certainly say if my father were not by',
 'I believe it is very true my dear indeed said Mr Woodhousewith a sigh',
 'I am afraid I am sometimes very fanciful and troublesome',
 'My dearest papa',
 'You do not think I could mean you or supposeMr Knightley to mean you',
 'What a horrible idea',
 'Oh no',
 'I meantonly myself',
 'Mr Knightley loves to find fault with me you knowin a jokeit is all a joke',
 'We always say what we like to one another',
 'Mr Knightley in fact was one of the few people who could seefaults in Emma Woodhouse and the only one who ever told her of themand though this was not particularly agreeable to Emma herselfshe knew it would be so much less so to her father that she wouldnot have him really suspect such a circumstance as her not beingthought perfect by every body',
 'Emma knows I never flatter her said Mr Knightley but Imeant no reflection on any body',
 'Miss Taylor has been usedto have two persons to please she will now have but one',
 'The chances are that she must be a gainer',
 'Well said Emma willing to let it passyou want to hearabout the wedding and I shall be happy to tell you for we allbehaved charmingly',
 'Every body was punctual every body in theirbest looks not a tear and hardly a long face to be seen',
 'Oh nowe all felt that we were going to be only half a mile apartand were sure of meeting every day',
 'Dear Emma bears every thing so well said her father',
 'But Mr Knightley she is really very sorry to lose poor Miss Taylorand I am sure she will miss her more than she thinks for',
 'Emma turned away her head divided between tears and smiles',
 'It is impossible that Emma should not miss such a companionsaid Mr Knightley',
 'We should not like her so well as we do sirif we could suppose it but she knows how much the marriage is toMiss Taylors advantage she knows how very acceptable it must beat Miss Taylors time of life to be settled in a home of her ownand how important to her to be secure of a comfortable provisionand therefore cannot allow herself to feel so much pain as pleasure',
 'Every friend of Miss Taylor must be glad to have her so happilymarried',
 'And you have forgotten one matter of joy to me said Emmaand a very considerable onethat I made the match myself',
 'I made the match you know four years ago and to have it take placeand be proved in the right when so many people said Mr Weston wouldnever marry again may comfort me for any thing',
 'Mr Knightley shook his head at her',
 'Her father fondly repliedAh',
 'my dear I wish you would not make matches and foretell thingsfor whatever you say always comes to pass',
 'Pray do not make anymore matches',
 'I promise you to make none for myself papa but I must indeedfor other people',
 'It is the greatest amusement in the world',
 'Andafter such success you knowEvery body said that Mr Weston wouldnever marry again',
 'Oh dear no',
 'Mr Weston who had been a widowerso long and who seemed so perfectly comfortable without a wifeso constantly occupied either in his business in town or among hisfriends here always acceptable wherever he went always cheerfulMr Weston need not spend a single evening in the year alone if he didnot like it',
 'Oh no',
 'Mr Weston certainly would never marry again',
 'Some people even talked of a promise to his wife on her deathbedand others of the son and the uncle not letting him',
 'All mannerof solemn nonsense was talked on the subject but I believed noneof it',
 'Ever since the dayabout four years agothat Miss Taylor and Imet with him in Broadway Lane when because it began to drizzlehe darted away with so much gallantry and borrowed two umbrellasfor us from Farmer Mitchells I made up my mind on the subject',
 'I planned the match from that hour and when such success has blessedme in this instance dear papa you cannot think that I shall leaveoff matchmaking',
 'I do not understand what you mean by success said Mr Knightley',
 'Success supposes endeavour',
 'Your time has been properly anddelicately spent if you have been endeavouring for the last fouryears to bring about this marriage',
 'A worthy employment for a youngladys mind',
 'But if which I rather imagine your making the matchas you call it means only your planning it your saying to yourselfone idle day I think it would be a very good thing for Miss Taylorif Mr Weston were to marry her and saying it again to yourselfevery now and then afterwards why do you talk of success',
 'Whereis your merit',
 'What are you proud of',
 'You made a lucky guessand that is all that can be said',
 'And have you never known the pleasure and triumph of a lucky guessI pity youI thought you clevererfor depend upon it a luckyguess is never merely luck',
 'There is always some talent in it',
 'And as to my poor word success which you quarrel with I do notknow that I am so entirely without any claim to it',
 'You have drawntwo pretty pictures but I think there may be a thirda somethingbetween the donothing and the doall',
 'If I had not promoted Mr Westonsvisits here and given many little encouragements and smoothedmany little matters it might not have come to any thing after all',
 'I think you must know Hartfield enough to comprehend that',
 'A straightforward openhearted man like Weston and a rationalunaffected woman like Miss Taylor may be safely left to manage theirown concerns',
 'You are more likely to have done harm to yourselfthan good to them by interference',
 'Emma never thinks of herself if she can do good to othersrejoined Mr Woodhouse understanding but in part',
 'But my dearpray do not make any more matches they are silly things and break upones family circle grievously',
 'Only one more papa only for Mr Elton',
 'Poor Mr Elton',
 'Youlike Mr Elton papaI must look about for a wife for him',
 'There is nobody in Highbury who deserves himand he has beenhere a whole year and has fitted up his house so comfortablythat it would be a shame to have him single any longerand I thoughtwhen he was joining their hands today he looked so very much as ifhe would like to have the same kind office done for him',
 'I thinkvery well of Mr Elton and this is the only way I have of doinghim a service',
 'Mr Elton is a very pretty young man to be sure and a verygood young man and I have a great regard for him',
 'But if youwant to shew him any attention my dear ask him to comeand dine with us some day',
 'That will be a much better thing',
 'I dare say Mr Knightley will be so kind as to meet him',
 'With a great deal of pleasure sir at any time said Mr Knightleylaughing and I agree with you entirely that it will be a muchbetter thing',
 'Invite him to dinner Emma and help him to the bestof the fish and the chicken but leave him to chuse his own wife',
 'Depend upon it a man of six or sevenandtwenty can take careof himself',
 'CHAPTER IIMr Weston was a native of Highbury and born of a respectable familywhich for the last two or three generations had been rising intogentility and property',
 'He had received a good education buton succeeding early in life to a small independence had becomeindisposed for any of the more homely pursuits in which his brotherswere engaged and had satisfied an active cheerful mind and socialtemper by entering into the militia of his county then embodied',
 'Captain Weston was a general favourite and when the chancesof his military life had introduced him to Miss Churchillof a great Yorkshire family and Miss Churchill fell in lovewith him nobody was surprized except her brother and his wifewho had never seen him and who were full of pride and importancewhich the connexion would offend',
 'Miss Churchill however being of age and with the full commandof her fortunethough her fortune bore no proportion to thefamilyestatewas not to be dissuaded from the marriage and ittook place to the infinite mortification of Mr and Mrs Churchillwho threw her off with due decorum',
 'It was an unsuitable connexionand did not produce much happiness',
 'Mrs Weston ought to have foundmore in it for she had a husband whose warm heart and sweet tempermade him think every thing due to her in return for the great goodnessof being in love with him but though she had one sort of spiritshe had not the best',
 'She had resolution enough to pursueher own will in spite of her brother but not enough to refrainfrom unreasonable regrets at that brothers unreasonable angernor from missing the luxuries of her former home',
 'They lived beyondtheir income but still it was nothing in comparison of Enscombeshe did not cease to love her husband but she wanted at onceto be the wife of Captain Weston and Miss Churchill of Enscombe',
 'Captain Weston who had been considered especially by the Churchillsas making such an amazing match was proved to have much the worstof the bargain for when his wife died after a three years marriagehe was rather a poorer man than at first and with a child to maintain',
 'From the expense of the child however he was soon relieved',

In [166]:
emma_sents[0:500]

['[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; and had lived nearly twenty-one years in the world\nwith very little to distress or vex her.',
 "She was the youngest of the two daughters of a most affectionate,\nindulgent father; and had, in consequence of her sister's marriage,\nbeen mistress of his house from a very early period.",
 'Her mother\nhad died too long ago for her to have more than an indistinct\nremembrance of her caresses; and her place had been supplied\nby an excellent woman as governess, who had fallen little short\nof a mother in affection.',
 "Sixteen years had Miss Taylor been in Mr. Woodhouse's family,\nless as a governess than a friend, very fond of both daughters,\nbut particularly of Emma.",
 'Between _them_ it was more the intimacy\nof sisters.',
 "Even before Miss Taylor had ceased to hold the nominal\noffice of governess, the mildness of her temper had hardly allowed\nher to impose any restraint; and the shadow of authority being\nnow long passed away, they had been living together as friend and\nfriend very mutually attached, and Emma doing just what she liked;\nhighly esteeming Miss Taylor's judgment, but directed chiefly by\nher own.",
 "The real evils, indeed, of Emma's situation were the power of having\nrather too much her own way, and a disposition to think a little\ntoo well of herself; these were the disadvantages which threatened\nalloy to her many enjoyments.",
 'The danger, however, was at present\nso unperceived, that they did not by any means rank as misfortunes\nwith her.',
 'Sorrow came--a gentle sorrow--but not at all in the shape of any\ndisagreeable consciousness.--Miss Taylor married.',
 "It was Miss\nTaylor's loss which first brought grief.",
 'It was on the wedding-day\nof this beloved friend that Emma first sat in mournful thought\nof any continuance.',
 'The wedding over, and the bride-people gone,\nher father and herself were left to dine together, with no prospect\nof a third to cheer a long evening.',
 'Her father composed himself\nto sleep after dinner, as usual, and she had then only to sit\nand think of what she had lost.',
 'The event had every promise of happiness for her friend.',
 "Mr. Weston\nwas a man of unexceptionable character, easy fortune, suitable age,\nand pleasant manners; and there was some satisfaction in considering\nwith what self-denying, generous friendship she had always wished\nand promoted the match; but it was a black morning's work for her.",
 'The want of Miss Taylor would be felt every hour of every day.',
 'She recalled her past kindness--the kindness, the affection of sixteen\nyears--how she had taught and how she had played with her from five\nyears old--how she had devoted all her powers to attach and amuse\nher in health--and how nursed her through the various illnesses\nof childhood.',
 "A large debt of gratitude was owing here; but the\nintercourse of the last seven years, the equal footing and perfect\nunreserve which had soon followed Isabella's marriage, on their\nbeing left to each other, was yet a dearer, tenderer recollection.",
 'She had been a friend and companion such as few possessed: intelligent,\nwell-informed, useful, gentle, knowing all the ways of the family,\ninterested in all its concerns, and peculiarly interested in herself,\nin every pleasure, every scheme of hers--one to whom she could speak\nevery thought as it arose, and who had such an affection for her\nas could never find fault.',
 'How was she to bear the change?--It was true that her friend was\ngoing only half a mile from them; but Emma was aware that great must\nbe the difference between a Mrs. Weston, only half a mile from them,\nand a Miss Taylor in the house; and with all her advantages,\nnatural and domestic, she was now in great danger of suffering\nfrom intellectual solitude.',
 'She dearly loved her father, but he\nwas no companion for her.',
 'He could not meet her in conversation,\nrational or playful.',
 'The evil of the actual disparity in their ages (and Mr. Woodhouse had\nnot married early) was much increased by his constitution and habits;\nfor having been a valetudinarian all his life, without activity\nof mind or body, he was a much older man in ways than in years;\nand though everywhere beloved for the friendliness of his heart\nand his amiable temper, his talents could not have recommended him\nat any time.',
 'Her sister, though comparatively but little removed by matrimony,\nbeing settled in London, only sixteen miles off, was much beyond\nher daily reach; and many a long October and November evening must\nbe struggled through at Hartfield, before Christmas brought the next\nvisit from Isabella and her husband, and their little children,\nto fill the house, and give her pleasant society again.',
 'Highbury, the large and populous village, almost amounting to a town,\nto which Hartfield, in spite of its separate lawn, and shrubberies,\nand name, did really belong, afforded her no equals.',
 'The Woodhouses\nwere first in consequence there.',
 'All looked up to them.',
 'She had\nmany acquaintance in the place, for her father was universally civil,\nbut not one among them who could be accepted in lieu of Miss\nTaylor for even half a day.',
 'It was a melancholy change; and Emma\ncould not but sigh over it, and wish for impossible things,\ntill her father awoke, and made it necessary to be cheerful.',
 'His spirits required support.',
 'He was a nervous man, easily depressed;\nfond of every body that he was used to, and hating to part with them;\nhating change of every kind.',
 "Matrimony, as the origin of change,\nwas always disagreeable; and he was by no means yet reconciled\nto his own daughter's marrying, nor could ever speak of her but\nwith compassion, though it had been entirely a match of affection,\nwhen he was now obliged to part with Miss Taylor too; and from\nhis habits of gentle selfishness, and of being never able to\nsuppose that other people could feel differently from himself,\nhe was very much disposed to think Miss Taylor had done as sad\na thing for herself as for them, and would have been a great deal\nhappier if she had spent all the rest of her life at Hartfield.",
 'Emma smiled and chatted as cheerfully as she could, to keep him\nfrom such thoughts; but when tea came, it was impossible for him\nnot to say exactly as he had said at dinner,\n\n"Poor Miss Taylor!--I wish she were here again.',
 'What a pity it\nis that Mr. Weston ever thought of her!"',
 '"I cannot agree with you, papa; you know I cannot.',
 'Mr. Weston is such\na good-humoured, pleasant, excellent man, that he thoroughly deserves\na good wife;--and you would not have had Miss Taylor live with us\nfor ever, and bear all my odd humours, when she might have a house of her own?"',
 '"A house of her own!--But where is the advantage of a house of her own?',
 'This is three times as large.--And you have never any odd humours,\nmy dear."',
 '"How often we shall be going to see them, and they coming to see\nus!--We shall be always meeting!',
 '_We_ must begin; we must go and pay\nwedding visit very soon."',
 '"My dear, how am I to get so far?',
 'Randalls is such a distance.',
 'I could not walk half so far."',
 '"No, papa, nobody thought of your walking.',
 'We must go in the carriage,\nto be sure."',
 '"The carriage!',
 'But James will not like to put the horses to for\nsuch a little way;--and where are the poor horses to be while we\nare paying our visit?"',
 '"They are to be put into Mr. Weston\'s stable, papa.',
 'You know we\nhave settled all that already.',
 'We talked it all over with Mr. Weston\nlast night.',
 "And as for James, you may be very sure he will always like\ngoing to Randalls, because of his daughter's being housemaid there.",
 'I only doubt whether he will ever take us anywhere else.',
 'That was\nyour doing, papa.',
 'You got Hannah that good place.',
 'Nobody thought\nof Hannah till you mentioned her--James is so obliged to you!"',
 '"I am very glad I did think of her.',
 'It was very lucky, for I would\nnot have had poor James think himself slighted upon any account;\nand I am sure she will make a very good servant: she is a civil,\npretty-spoken girl; I have a great opinion of her.',
 'Whenever I see her,\nshe always curtseys and asks me how I do, in a very pretty manner;\nand when you have had her here to do needlework, I observe she\nalways turns the lock of the door the right way and never bangs it.',
 'I am sure she will be an excellent servant; and it will be a great\ncomfort to poor Miss Taylor to have somebody about her that she is\nused to see.',
 'Whenever James goes over to see his daughter, you know,\nshe will be hearing of us.',
 'He will be able to tell her how we\nall are."',
 'Emma spared no exertions to maintain this happier flow of ideas,\nand hoped, by the help of backgammon, to get her father tolerably\nthrough the evening, and be attacked by no regrets but her own.',
 'The backgammon-table was placed; but a visitor immediately afterwards\nwalked in and made it unnecessary.',
 "Mr. Knightley, a sensible man about seven or eight-and-thirty, was not\nonly a very old and intimate friend of the family, but particularly\nconnected with it, as the elder brother of Isabella's husband.",
 'He lived about a mile from Highbury, was a frequent visitor,\nand always welcome, and at this time more welcome than usual,\nas coming directly from their mutual connexions in London.',
 "He had\nreturned to a late dinner, after some days' absence, and now walked\nup to Hartfield to say that all were well in Brunswick Square.",
 'It was a happy circumstance, and animated Mr. Woodhouse for some time.',
 'Mr. Knightley had a cheerful manner, which always did him good;\nand his many inquiries after "poor Isabella" and her children were\nanswered most satisfactorily.',
 'When this was over, Mr. Woodhouse\ngratefully observed, "It is very kind of you, Mr. Knightley, to come\nout at this late hour to call upon us.',
 'I am afraid you must have\nhad a shocking walk."',
 '"Not at all, sir.',
 'It is a beautiful moonlight night; and so mild\nthat I must draw back from your great fire."',
 '"But you must have found it very damp and dirty.',
 'I wish you may\nnot catch cold."',
 '"Dirty, sir!',
 'Look at my shoes.',
 'Not a speck on them."',
 '"Well!',
 'that is quite surprising, for we have had a vast deal\nof rain here.',
 'It rained dreadfully hard for half an hour\nwhile we were at breakfast.',
 'I wanted them to put off the wedding."',
 '"By the bye--I have not wished you joy.',
 'Being pretty well aware\nof what sort of joy you must both be feeling, I have been in no hurry\nwith my congratulations; but I hope it all went off tolerably well.',
 'How did you all behave?',
 'Who cried most?"',
 '"Ah!',
 'poor Miss Taylor!',
 '\'Tis a sad business."',
 '"Poor Mr. and Miss Woodhouse, if you please; but I cannot possibly\nsay `poor Miss Taylor.\'',
 'I have a great regard for you and Emma;\nbut when it comes to the question of dependence or independence!--At\nany rate, it must be better to have only one to please than two."',
 '"Especially when _one_ of those two is such a fanciful, troublesome creature!"',
 'said Emma playfully.',
 '"That is what you have in your head,\nI know--and what you would certainly say if my father were not by."',
 '"I believe it is very true, my dear, indeed," said Mr. Woodhouse,\nwith a sigh.',
 '"I am afraid I am sometimes very fanciful and troublesome."',
 '"My dearest papa!',
 'You do not think I could mean _you_, or suppose\nMr. Knightley to mean _you_.',
 'What a horrible idea!',
 'Oh no!',
 'I meant\nonly myself.',
 'Mr. Knightley loves to find fault with me, you know--\nin a joke--it is all a joke.',
 'We always say what we like to one another."',
 'Mr. Knightley, in fact, was one of the few people who could see\nfaults in Emma Woodhouse, and the only one who ever told her of them:\nand though this was not particularly agreeable to Emma herself,\nshe knew it would be so much less so to her father, that she would\nnot have him really suspect such a circumstance as her not being\nthought perfect by every body.',
 '"Emma knows I never flatter her," said Mr. Knightley, "but I\nmeant no reflection on any body.',
 'Miss Taylor has been used\nto have two persons to please; she will now have but one.',
 'The chances are that she must be a gainer."',
 '"Well," said Emma, willing to let it pass--"you want to hear\nabout the wedding; and I shall be happy to tell you, for we all\nbehaved charmingly.',
 'Every body was punctual, every body in their\nbest looks: not a tear, and hardly a long face to be seen.',
 'Oh no;\nwe all felt that we were going to be only half a mile apart,\nand were sure of meeting every day."',
 '"Dear Emma bears every thing so well," said her father.',
 '"But, Mr. Knightley, she is really very sorry to lose poor Miss Taylor,\nand I am sure she _will_ miss her more than she thinks for."',
 'Emma turned away her head, divided between tears and smiles.',
 '"It is impossible that Emma should not miss such a companion,"\nsaid Mr. Knightley.',
 '"We should not like her so well as we do, sir,\nif we could suppose it; but she knows how much the marriage is to\nMiss Taylor\'s advantage; she knows how very acceptable it must be,\nat Miss Taylor\'s time of life, to be settled in a home of her own,\nand how important to her to be secure of a comfortable provision,\nand therefore cannot allow herself to feel so much pain as pleasure.',
 'Every friend of Miss Taylor must be glad to have her so happily\nmarried."',
 '"And you have forgotten one matter of joy to me," said Emma,\n"and a very considerable one--that I made the match myself.',
 'I made the match, you know, four years ago; and to have it take place,\nand be proved in the right, when so many people said Mr. Weston would\nnever marry again, may comfort me for any thing."',
 'Mr. Knightley shook his head at her.',
 'Her father fondly replied,\n"Ah!',
 'my dear, I wish you would not make matches and foretell things,\nfor whatever you say always comes to pass.',
 'Pray do not make any\nmore matches."',
 '"I promise you to make none for myself, papa; but I must, indeed,\nfor other people.',
 'It is the greatest amusement in the world!',
 'And\nafter such success, you know!--Every body said that Mr. Weston would\nnever marry again.',
 'Oh dear, no!',
 'Mr. Weston, who had been a widower\nso long, and who seemed so perfectly comfortable without a wife,\nso constantly occupied either in his business in town or among his\nfriends here, always acceptable wherever he went, always cheerful--\nMr. Weston need not spend a single evening in the year alone if he did\nnot like it.',
 'Oh no!',
 'Mr. Weston certainly would never marry again.',
 'Some people even talked of a promise to his wife on her deathbed,\nand others of the son and the uncle not letting him.',
 'All manner\nof solemn nonsense was talked on the subject, but I believed none\nof it.',
 '"Ever since the day--about four years ago--that Miss Taylor and I\nmet with him in Broadway Lane, when, because it began to drizzle,\nhe darted away with so much gallantry, and borrowed two umbrellas\nfor us from Farmer Mitchell\'s, I made up my mind on the subject.',
 'I planned the match from that hour; and when such success has blessed\nme in this instance, dear papa, you cannot think that I shall leave\noff match-making."',
 '"I do not understand what you mean by `success,\'" said Mr. Knightley.',
 '"Success supposes endeavour.',
 'Your time has been properly and\ndelicately spent, if you have been endeavouring for the last four\nyears to bring about this marriage.',
 "A worthy employment for a young\nlady's mind!",
 "But if, which I rather imagine, your making the match,\nas you call it, means only your planning it, your saying to yourself\none idle day, `I think it would be a very good thing for Miss Taylor\nif Mr. Weston were to marry her,' and saying it again to yourself\nevery now and then afterwards, why do you talk of success?",
 'Where\nis your merit?',
 'What are you proud of?',
 'You made a lucky guess;\nand _that_ is all that can be said."',
 '"And have you never known the pleasure and triumph of a lucky guess?--\nI pity you.--I thought you cleverer--for, depend upon it a lucky\nguess is never merely luck.',
 'There is always some talent in it.',
 "And as to my poor word `success,' which you quarrel with, I do not\nknow that I am so entirely without any claim to it.",
 'You have drawn\ntwo pretty pictures; but I think there may be a third--a something\nbetween the do-nothing and the do-all.',
 "If I had not promoted Mr. Weston's\nvisits here, and given many little encouragements, and smoothed\nmany little matters, it might not have come to any thing after all.",
 'I think you must know Hartfield enough to comprehend that."',
 '"A straightforward, open-hearted man like Weston, and a rational,\nunaffected woman like Miss Taylor, may be safely left to manage their\nown concerns.',
 'You are more likely to have done harm to yourself,\nthan good to them, by interference."',
 '"Emma never thinks of herself, if she can do good to others,"\nrejoined Mr. Woodhouse, understanding but in part.',
 '"But, my dear,\npray do not make any more matches; they are silly things, and break up\none\'s family circle grievously."',
 '"Only one more, papa; only for Mr. Elton.',
 'Poor Mr. Elton!',
 'You\nlike Mr. Elton, papa,--I must look about for a wife for him.',
 'There is nobody in Highbury who deserves him--and he has been\nhere a whole year, and has fitted up his house so comfortably,\nthat it would be a shame to have him single any longer--and I thought\nwhen he was joining their hands to-day, he looked so very much as if\nhe would like to have the same kind office done for him!',
 'I think\nvery well of Mr. Elton, and this is the only way I have of doing\nhim a service."',
 '"Mr. Elton is a very pretty young man, to be sure, and a very\ngood young man, and I have a great regard for him.',
 'But if you\nwant to shew him any attention, my dear, ask him to come\nand dine with us some day.',
 'That will be a much better thing.',
 'I dare say Mr. Knightley will be so kind as to meet him."',
 '"With a great deal of pleasure, sir, at any time," said Mr. Knightley,\nlaughing, "and I agree with you entirely, that it will be a much\nbetter thing.',
 'Invite him to dinner, Emma, and help him to the best\nof the fish and the chicken, but leave him to chuse his own wife.',
 'Depend upon it, a man of six or seven-and-twenty can take care\nof himself."',
 'CHAPTER II\n\n\nMr. Weston was a native of Highbury, and born of a respectable family,\nwhich for the last two or three generations had been rising into\ngentility and property.',
 'He had received a good education, but,\non succeeding early in life to a small independence, had become\nindisposed for any of the more homely pursuits in which his brothers\nwere engaged, and had satisfied an active, cheerful mind and social\ntemper by entering into the militia of his county, then embodied.',
 'Captain Weston was a general favourite; and when the chances\nof his military life had introduced him to Miss Churchill,\nof a great Yorkshire family, and Miss Churchill fell in love\nwith him, nobody was surprized, except her brother and his wife,\nwho had never seen him, and who were full of pride and importance,\nwhich the connexion would offend.',
 'Miss Churchill, however, being of age, and with the full command\nof her fortune--though her fortune bore no proportion to the\nfamily-estate--was not to be dissuaded from the marriage, and it\ntook place, to the infinite mortification of Mr. and Mrs. Churchill,\nwho threw her off with due decorum.',
 'It was an unsuitable connexion,\nand did not produce much happiness.',

In [167]:
# Second approach:
# create a regex pattern to retain apostrophes and sentence periods
# add characters to be removed
pattern6 = r'[?|$|&|*|%|@|(|)|~]'

In [168]:
emma_f1 = [re.sub(pattern6, r'', sentence.strip()) for sentence in emma_sents]

In [169]:
emma_f1[0:500]

['[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; and had lived nearly twenty-one years in the world\nwith very little to distress or vex her.',
 "She was the youngest of the two daughters of a most affectionate,\nindulgent father; and had, in consequence of her sister's marriage,\nbeen mistress of his house from a very early period.",
 'Her mother\nhad died too long ago for her to have more than an indistinct\nremembrance of her caresses; and her place had been supplied\nby an excellent woman as governess, who had fallen little short\nof a mother in affection.',
 "Sixteen years had Miss Taylor been in Mr. Woodhouse's family,\nless as a governess than a friend, very fond of both daughters,\nbut particularly of Emma.",
 'Between _them_ it was more the intimacy\nof sisters.',
 "Even before Miss Taylor had ceased to hold the nominal\noffice of governess, the mildness of her temper had hardly allowed\nher to impose any restraint; and the shadow of authority being\nnow long passed away, they had been living together as friend and\nfriend very mutually attached, and Emma doing just what she liked;\nhighly esteeming Miss Taylor's judgment, but directed chiefly by\nher own.",
 "The real evils, indeed, of Emma's situation were the power of having\nrather too much her own way, and a disposition to think a little\ntoo well of herself; these were the disadvantages which threatened\nalloy to her many enjoyments.",
 'The danger, however, was at present\nso unperceived, that they did not by any means rank as misfortunes\nwith her.',
 'Sorrow came--a gentle sorrow--but not at all in the shape of any\ndisagreeable consciousness.--Miss Taylor married.',
 "It was Miss\nTaylor's loss which first brought grief.",
 'It was on the wedding-day\nof this beloved friend that Emma first sat in mournful thought\nof any continuance.',
 'The wedding over, and the bride-people gone,\nher father and herself were left to dine together, with no prospect\nof a third to cheer a long evening.',
 'Her father composed himself\nto sleep after dinner, as usual, and she had then only to sit\nand think of what she had lost.',
 'The event had every promise of happiness for her friend.',
 "Mr. Weston\nwas a man of unexceptionable character, easy fortune, suitable age,\nand pleasant manners; and there was some satisfaction in considering\nwith what self-denying, generous friendship she had always wished\nand promoted the match; but it was a black morning's work for her.",
 'The want of Miss Taylor would be felt every hour of every day.',
 'She recalled her past kindness--the kindness, the affection of sixteen\nyears--how she had taught and how she had played with her from five\nyears old--how she had devoted all her powers to attach and amuse\nher in health--and how nursed her through the various illnesses\nof childhood.',
 "A large debt of gratitude was owing here; but the\nintercourse of the last seven years, the equal footing and perfect\nunreserve which had soon followed Isabella's marriage, on their\nbeing left to each other, was yet a dearer, tenderer recollection.",
 'She had been a friend and companion such as few possessed: intelligent,\nwell-informed, useful, gentle, knowing all the ways of the family,\ninterested in all its concerns, and peculiarly interested in herself,\nin every pleasure, every scheme of hers--one to whom she could speak\nevery thought as it arose, and who had such an affection for her\nas could never find fault.',
 'How was she to bear the change--It was true that her friend was\ngoing only half a mile from them; but Emma was aware that great must\nbe the difference between a Mrs. Weston, only half a mile from them,\nand a Miss Taylor in the house; and with all her advantages,\nnatural and domestic, she was now in great danger of suffering\nfrom intellectual solitude.',
 'She dearly loved her father, but he\nwas no companion for her.',
 'He could not meet her in conversation,\nrational or playful.',
 'The evil of the actual disparity in their ages and Mr. Woodhouse had\nnot married early was much increased by his constitution and habits;\nfor having been a valetudinarian all his life, without activity\nof mind or body, he was a much older man in ways than in years;\nand though everywhere beloved for the friendliness of his heart\nand his amiable temper, his talents could not have recommended him\nat any time.',
 'Her sister, though comparatively but little removed by matrimony,\nbeing settled in London, only sixteen miles off, was much beyond\nher daily reach; and many a long October and November evening must\nbe struggled through at Hartfield, before Christmas brought the next\nvisit from Isabella and her husband, and their little children,\nto fill the house, and give her pleasant society again.',
 'Highbury, the large and populous village, almost amounting to a town,\nto which Hartfield, in spite of its separate lawn, and shrubberies,\nand name, did really belong, afforded her no equals.',
 'The Woodhouses\nwere first in consequence there.',
 'All looked up to them.',
 'She had\nmany acquaintance in the place, for her father was universally civil,\nbut not one among them who could be accepted in lieu of Miss\nTaylor for even half a day.',
 'It was a melancholy change; and Emma\ncould not but sigh over it, and wish for impossible things,\ntill her father awoke, and made it necessary to be cheerful.',
 'His spirits required support.',
 'He was a nervous man, easily depressed;\nfond of every body that he was used to, and hating to part with them;\nhating change of every kind.',
 "Matrimony, as the origin of change,\nwas always disagreeable; and he was by no means yet reconciled\nto his own daughter's marrying, nor could ever speak of her but\nwith compassion, though it had been entirely a match of affection,\nwhen he was now obliged to part with Miss Taylor too; and from\nhis habits of gentle selfishness, and of being never able to\nsuppose that other people could feel differently from himself,\nhe was very much disposed to think Miss Taylor had done as sad\na thing for herself as for them, and would have been a great deal\nhappier if she had spent all the rest of her life at Hartfield.",
 'Emma smiled and chatted as cheerfully as she could, to keep him\nfrom such thoughts; but when tea came, it was impossible for him\nnot to say exactly as he had said at dinner,\n\n"Poor Miss Taylor!--I wish she were here again.',
 'What a pity it\nis that Mr. Weston ever thought of her!"',
 '"I cannot agree with you, papa; you know I cannot.',
 'Mr. Weston is such\na good-humoured, pleasant, excellent man, that he thoroughly deserves\na good wife;--and you would not have had Miss Taylor live with us\nfor ever, and bear all my odd humours, when she might have a house of her own"',
 '"A house of her own!--But where is the advantage of a house of her own',
 'This is three times as large.--And you have never any odd humours,\nmy dear."',
 '"How often we shall be going to see them, and they coming to see\nus!--We shall be always meeting!',
 '_We_ must begin; we must go and pay\nwedding visit very soon."',
 '"My dear, how am I to get so far',
 'Randalls is such a distance.',
 'I could not walk half so far."',
 '"No, papa, nobody thought of your walking.',
 'We must go in the carriage,\nto be sure."',
 '"The carriage!',
 'But James will not like to put the horses to for\nsuch a little way;--and where are the poor horses to be while we\nare paying our visit"',
 '"They are to be put into Mr. Weston\'s stable, papa.',
 'You know we\nhave settled all that already.',
 'We talked it all over with Mr. Weston\nlast night.',
 "And as for James, you may be very sure he will always like\ngoing to Randalls, because of his daughter's being housemaid there.",
 'I only doubt whether he will ever take us anywhere else.',
 'That was\nyour doing, papa.',
 'You got Hannah that good place.',
 'Nobody thought\nof Hannah till you mentioned her--James is so obliged to you!"',
 '"I am very glad I did think of her.',
 'It was very lucky, for I would\nnot have had poor James think himself slighted upon any account;\nand I am sure she will make a very good servant: she is a civil,\npretty-spoken girl; I have a great opinion of her.',
 'Whenever I see her,\nshe always curtseys and asks me how I do, in a very pretty manner;\nand when you have had her here to do needlework, I observe she\nalways turns the lock of the door the right way and never bangs it.',
 'I am sure she will be an excellent servant; and it will be a great\ncomfort to poor Miss Taylor to have somebody about her that she is\nused to see.',
 'Whenever James goes over to see his daughter, you know,\nshe will be hearing of us.',
 'He will be able to tell her how we\nall are."',
 'Emma spared no exertions to maintain this happier flow of ideas,\nand hoped, by the help of backgammon, to get her father tolerably\nthrough the evening, and be attacked by no regrets but her own.',
 'The backgammon-table was placed; but a visitor immediately afterwards\nwalked in and made it unnecessary.',
 "Mr. Knightley, a sensible man about seven or eight-and-thirty, was not\nonly a very old and intimate friend of the family, but particularly\nconnected with it, as the elder brother of Isabella's husband.",
 'He lived about a mile from Highbury, was a frequent visitor,\nand always welcome, and at this time more welcome than usual,\nas coming directly from their mutual connexions in London.',
 "He had\nreturned to a late dinner, after some days' absence, and now walked\nup to Hartfield to say that all were well in Brunswick Square.",
 'It was a happy circumstance, and animated Mr. Woodhouse for some time.',
 'Mr. Knightley had a cheerful manner, which always did him good;\nand his many inquiries after "poor Isabella" and her children were\nanswered most satisfactorily.',
 'When this was over, Mr. Woodhouse\ngratefully observed, "It is very kind of you, Mr. Knightley, to come\nout at this late hour to call upon us.',
 'I am afraid you must have\nhad a shocking walk."',
 '"Not at all, sir.',
 'It is a beautiful moonlight night; and so mild\nthat I must draw back from your great fire."',
 '"But you must have found it very damp and dirty.',
 'I wish you may\nnot catch cold."',
 '"Dirty, sir!',
 'Look at my shoes.',
 'Not a speck on them."',
 '"Well!',
 'that is quite surprising, for we have had a vast deal\nof rain here.',
 'It rained dreadfully hard for half an hour\nwhile we were at breakfast.',
 'I wanted them to put off the wedding."',
 '"By the bye--I have not wished you joy.',
 'Being pretty well aware\nof what sort of joy you must both be feeling, I have been in no hurry\nwith my congratulations; but I hope it all went off tolerably well.',
 'How did you all behave',
 'Who cried most"',
 '"Ah!',
 'poor Miss Taylor!',
 '\'Tis a sad business."',
 '"Poor Mr. and Miss Woodhouse, if you please; but I cannot possibly\nsay `poor Miss Taylor.\'',
 'I have a great regard for you and Emma;\nbut when it comes to the question of dependence or independence!--At\nany rate, it must be better to have only one to please than two."',
 '"Especially when _one_ of those two is such a fanciful, troublesome creature!"',
 'said Emma playfully.',
 '"That is what you have in your head,\nI know--and what you would certainly say if my father were not by."',
 '"I believe it is very true, my dear, indeed," said Mr. Woodhouse,\nwith a sigh.',
 '"I am afraid I am sometimes very fanciful and troublesome."',
 '"My dearest papa!',
 'You do not think I could mean _you_, or suppose\nMr. Knightley to mean _you_.',
 'What a horrible idea!',
 'Oh no!',
 'I meant\nonly myself.',
 'Mr. Knightley loves to find fault with me, you know--\nin a joke--it is all a joke.',
 'We always say what we like to one another."',
 'Mr. Knightley, in fact, was one of the few people who could see\nfaults in Emma Woodhouse, and the only one who ever told her of them:\nand though this was not particularly agreeable to Emma herself,\nshe knew it would be so much less so to her father, that she would\nnot have him really suspect such a circumstance as her not being\nthought perfect by every body.',
 '"Emma knows I never flatter her," said Mr. Knightley, "but I\nmeant no reflection on any body.',
 'Miss Taylor has been used\nto have two persons to please; she will now have but one.',
 'The chances are that she must be a gainer."',
 '"Well," said Emma, willing to let it pass--"you want to hear\nabout the wedding; and I shall be happy to tell you, for we all\nbehaved charmingly.',
 'Every body was punctual, every body in their\nbest looks: not a tear, and hardly a long face to be seen.',
 'Oh no;\nwe all felt that we were going to be only half a mile apart,\nand were sure of meeting every day."',
 '"Dear Emma bears every thing so well," said her father.',
 '"But, Mr. Knightley, she is really very sorry to lose poor Miss Taylor,\nand I am sure she _will_ miss her more than she thinks for."',
 'Emma turned away her head, divided between tears and smiles.',
 '"It is impossible that Emma should not miss such a companion,"\nsaid Mr. Knightley.',
 '"We should not like her so well as we do, sir,\nif we could suppose it; but she knows how much the marriage is to\nMiss Taylor\'s advantage; she knows how very acceptable it must be,\nat Miss Taylor\'s time of life, to be settled in a home of her own,\nand how important to her to be secure of a comfortable provision,\nand therefore cannot allow herself to feel so much pain as pleasure.',
 'Every friend of Miss Taylor must be glad to have her so happily\nmarried."',
 '"And you have forgotten one matter of joy to me," said Emma,\n"and a very considerable one--that I made the match myself.',
 'I made the match, you know, four years ago; and to have it take place,\nand be proved in the right, when so many people said Mr. Weston would\nnever marry again, may comfort me for any thing."',
 'Mr. Knightley shook his head at her.',
 'Her father fondly replied,\n"Ah!',
 'my dear, I wish you would not make matches and foretell things,\nfor whatever you say always comes to pass.',
 'Pray do not make any\nmore matches."',
 '"I promise you to make none for myself, papa; but I must, indeed,\nfor other people.',
 'It is the greatest amusement in the world!',
 'And\nafter such success, you know!--Every body said that Mr. Weston would\nnever marry again.',
 'Oh dear, no!',
 'Mr. Weston, who had been a widower\nso long, and who seemed so perfectly comfortable without a wife,\nso constantly occupied either in his business in town or among his\nfriends here, always acceptable wherever he went, always cheerful--\nMr. Weston need not spend a single evening in the year alone if he did\nnot like it.',
 'Oh no!',
 'Mr. Weston certainly would never marry again.',
 'Some people even talked of a promise to his wife on her deathbed,\nand others of the son and the uncle not letting him.',
 'All manner\nof solemn nonsense was talked on the subject, but I believed none\nof it.',
 '"Ever since the day--about four years ago--that Miss Taylor and I\nmet with him in Broadway Lane, when, because it began to drizzle,\nhe darted away with so much gallantry, and borrowed two umbrellas\nfor us from Farmer Mitchell\'s, I made up my mind on the subject.',
 'I planned the match from that hour; and when such success has blessed\nme in this instance, dear papa, you cannot think that I shall leave\noff match-making."',
 '"I do not understand what you mean by `success,\'" said Mr. Knightley.',
 '"Success supposes endeavour.',
 'Your time has been properly and\ndelicately spent, if you have been endeavouring for the last four\nyears to bring about this marriage.',
 "A worthy employment for a young\nlady's mind!",
 "But if, which I rather imagine, your making the match,\nas you call it, means only your planning it, your saying to yourself\none idle day, `I think it would be a very good thing for Miss Taylor\nif Mr. Weston were to marry her,' and saying it again to yourself\nevery now and then afterwards, why do you talk of success",
 'Where\nis your merit',
 'What are you proud of',
 'You made a lucky guess;\nand _that_ is all that can be said."',
 '"And have you never known the pleasure and triumph of a lucky guess--\nI pity you.--I thought you cleverer--for, depend upon it a lucky\nguess is never merely luck.',
 'There is always some talent in it.',
 "And as to my poor word `success,' which you quarrel with, I do not\nknow that I am so entirely without any claim to it.",
 'You have drawn\ntwo pretty pictures; but I think there may be a third--a something\nbetween the do-nothing and the do-all.',
 "If I had not promoted Mr. Weston's\nvisits here, and given many little encouragements, and smoothed\nmany little matters, it might not have come to any thing after all.",
 'I think you must know Hartfield enough to comprehend that."',
 '"A straightforward, open-hearted man like Weston, and a rational,\nunaffected woman like Miss Taylor, may be safely left to manage their\nown concerns.',
 'You are more likely to have done harm to yourself,\nthan good to them, by interference."',
 '"Emma never thinks of herself, if she can do good to others,"\nrejoined Mr. Woodhouse, understanding but in part.',
 '"But, my dear,\npray do not make any more matches; they are silly things, and break up\none\'s family circle grievously."',
 '"Only one more, papa; only for Mr. Elton.',
 'Poor Mr. Elton!',
 'You\nlike Mr. Elton, papa,--I must look about for a wife for him.',
 'There is nobody in Highbury who deserves him--and he has been\nhere a whole year, and has fitted up his house so comfortably,\nthat it would be a shame to have him single any longer--and I thought\nwhen he was joining their hands to-day, he looked so very much as if\nhe would like to have the same kind office done for him!',
 'I think\nvery well of Mr. Elton, and this is the only way I have of doing\nhim a service."',
 '"Mr. Elton is a very pretty young man, to be sure, and a very\ngood young man, and I have a great regard for him.',
 'But if you\nwant to shew him any attention, my dear, ask him to come\nand dine with us some day.',
 'That will be a much better thing.',
 'I dare say Mr. Knightley will be so kind as to meet him."',
 '"With a great deal of pleasure, sir, at any time," said Mr. Knightley,\nlaughing, "and I agree with you entirely, that it will be a much\nbetter thing.',
 'Invite him to dinner, Emma, and help him to the best\nof the fish and the chicken, but leave him to chuse his own wife.',
 'Depend upon it, a man of six or seven-and-twenty can take care\nof himself."',
 'CHAPTER II\n\n\nMr. Weston was a native of Highbury, and born of a respectable family,\nwhich for the last two or three generations had been rising into\ngentility and property.',
 'He had received a good education, but,\non succeeding early in life to a small independence, had become\nindisposed for any of the more homely pursuits in which his brothers\nwere engaged, and had satisfied an active, cheerful mind and social\ntemper by entering into the militia of his county, then embodied.',
 'Captain Weston was a general favourite; and when the chances\nof his military life had introduced him to Miss Churchill,\nof a great Yorkshire family, and Miss Churchill fell in love\nwith him, nobody was surprized, except her brother and his wife,\nwho had never seen him, and who were full of pride and importance,\nwhich the connexion would offend.',
 'Miss Churchill, however, being of age, and with the full command\nof her fortune--though her fortune bore no proportion to the\nfamily-estate--was not to be dissuaded from the marriage, and it\ntook place, to the infinite mortification of Mr. and Mrs. Churchill,\nwho threw her off with due decorum.',
 'It was an unsuitable connexion,\nand did not produce much happiness.',

In [170]:
## expanding contractions ##
# e.g., isn't to is not and won't to will not

contraction_map = {
    "ain't": "am not",
    "aren't": "are not",
    "can't": "cannot",
    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'll": "he will",
    "he's": "he is",
    "i'd": "i would",
    "i'll": "i will",
    "i'm": "i am",
    "i've": "i have",
    "isn't": "is not",
    "it'd": "it would",
    "it'll": "it will",
    "it's": "it is",
    "let's": "let us",
    "mightn't": "might not",
    "mustn't": "must not",
    "shan't": "shall not",
    "she'd": "she would",
    "she'll": "she will",
    "she's": "she is",
    "shouldn't": "should not",
    "that's": "that is",
    "there's": "there is",
    "they'd": "they would",
    "they'll": "they will",
    "they're": "they are",
    "they've": "they have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'll": "we will",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what's": "what is",
    "where's": "where is",
    "who's": "who is",
    "won't": "will not",
    "wouldn't": "would not",
    "you'd": "you would",
    "you'll": "you will",
    "you're": "you are",
    "you've": "you have"
}

In [171]:
# write a function to expand contractions in the text

def expand_contractions(sent, mapping):

# pattern for matching contractions with their expansions
    pattern = re.compile('({})'.format('|'.join(mapping.keys())), flags=re. IGNORECASE|re.DOTALL)

    def expand_map(contraction):
        # using group method to access subgroups of the match
        match = contraction.group(0)

        # to retain the correct case of the word
        first_char = match[0]

        # find out the expansion
        expansion = mapping.get(match) if mapping.get(match) else mapping.get(match.lower())
        
        expansion = first_char + expansion[1:]
        return expansion

    # using sub method to replace all contractions with their expansions for a sentence
    # function expand map will be called for every non-overlapping occurrence of the pattern
    expand_sent = pattern.sub(expand_map, sent)
    return expand_sent

In [172]:
test = "The young man wasn't fast enough and he couldn't win the race"
test_e = expand_contractions(test, contraction_map)
test_e

'The young man was not fast enough and he could not win the race'

In [173]:
# using user-defined expand_contractions function on cleaned text
emma_fe = [expand_contractions(sentence, contraction_map) for sentence in emma_f]

In [174]:
emma_fe[0:500]

['Emma by Jane Austen 1816VOLUME ICHAPTER IEmma Woodhouse handsome clever and rich with a comfortable homeand happy disposition seemed to unite some of the best blessingsof existence and had lived nearly twentyone years in the worldwith very little to distress or vex her',
 'She was the youngest of the two daughters of a most affectionateindulgent father and had in consequence of her sisters marriagebeen mistress of his house from a very early period',
 'Her motherhad died too long ago for her to have more than an indistinctremembrance of her caresses and her place had been suppliedby an excellent woman as governess who had fallen little shortof a mother in affection',
 'Sixteen years had Miss Taylor been in Mr Woodhouses familyless as a governess than a friend very fond of both daughtersbut particularly of Emma',
 'Between them it was more the intimacyof sisters',
 'Even before Miss Taylor had ceased to hold the nominaloffice of governess the mildness of her temper had hardly allowedher to impose any restraint and the shadow of authority beingnow long passed away they had been living together as friend andfriend very mutually attached and Emma doing just what she likedhighly esteeming Miss Taylors judgment but directed chiefly byher own',
 'The real evils indeed of Emmas situation were the power of havingrather too much her own way and a disposition to think a littletoo well of herself these were the disadvantages which threatenedalloy to her many enjoyments',
 'The danger however was at presentso unperceived that they did not by any means rank as misfortuneswith her',
 'Sorrow camea gentle sorrowbut not at all in the shape of anydisagreeable consciousnessMiss Taylor married',
 'It was MissTaylors loss which first brought grief',
 'It was on the weddingdayof this beloved friend that Emma first sat in mournful thoughtof any continuance',
 'The wedding over and the bridepeople goneher father and herself were left to dine together with no prospectof a third to cheer a long evening',
 'Her father composed himselfto sleep after dinner as usual and she had then only to sitand think of what she had lost',
 'The event had every promise of happiness for her friend',
 'Mr Westonwas a man of unexceptionable character easy fortune suitable ageand pleasant manners and there was some satisfaction in consideringwith what selfdenying generous friendship she had always wishedand promoted the match but it was a black mornings work for her',
 'The want of Miss Taylor would be felt every hour of every day',
 'She recalled her past kindnessthe kindness the affection of sixteenyearshow she had taught and how she had played with her from fiveyears oldhow she had devoted all her powers to attach and amuseher in healthand how nursed her through the various illnessesof childhood',
 'A large debt of gratitude was owing here but theintercourse of the last seven years the equal footing and perfectunreserve which had soon followed Isabellas marriage on theirbeing left to each other was yet a dearer tenderer recollection',
 'She had been a friend and companion such as few possessed intelligentwellinformed useful gentle knowing all the ways of the familyinterested in all its concerns and peculiarly interested in herselfin every pleasure every scheme of hersone to whom she could speakevery thought as it arose and who had such an affection for heras could never find fault',
 'How was she to bear the changeIt was true that her friend wasgoing only half a mile from them but Emma was aware that great mustbe the difference between a Mrs Weston only half a mile from themand a Miss Taylor in the house and with all her advantagesnatural and domestic she was now in great danger of sufferingfrom intellectual solitude',
 'She dearly loved her father but hewas no companion for her',
 'He could not meet her in conversationrational or playful',
 'The evil of the actual disparity in their ages and Mr Woodhouse hadnot married early was much increased by his constitution and habitsfor having been a valetudinarian all his life without activityof mind or body he was a much older man in ways than in yearsand though everywhere beloved for the friendliness of his heartand his amiable temper his talents could not have recommended himat any time',
 'Her sister though comparatively but little removed by matrimonybeing settled in London only sixteen miles off was much beyondher daily reach and many a long October and November evening mustbe struggled through at Hartfield before Christmas brought the nextvisit from Isabella and her husband and their little childrento fill the house and give her pleasant society again',
 'Highbury the large and populous village almost amounting to a townto which Hartfield in spite of its separate lawn and shrubberiesand name did really belong afforded her no equals',
 'The Woodhouseswere first in consequence there',
 'All looked up to them',
 'She hadmany acquaintance in the place for her father was universally civilbut not one among them who could be accepted in lieu of MissTaylor for even half a day',
 'It was a melancholy change and Emmacould not but sigh over it and wish for impossible thingstill her father awoke and made it necessary to be cheerful',
 'His spirits required support',
 'He was a nervous man easily depressedfond of every body that he was used to and hating to part with themhating change of every kind',
 'Matrimony as the origin of changewas always disagreeable and he was by no means yet reconciledto his own daughters marrying nor could ever speak of her butwith compassion though it had been entirely a match of affectionwhen he was now obliged to part with Miss Taylor too and fromhis habits of gentle selfishness and of being never able tosuppose that other people could feel differently from himselfhe was very much disposed to think Miss Taylor had done as sada thing for herself as for them and would have been a great dealhappier if she had spent all the rest of her life at Hartfield',
 'Emma smiled and chatted as cheerfully as she could to keep himfrom such thoughts but when tea came it was impossible for himnot to say exactly as he had said at dinnerPoor Miss TaylorI wish she were here again',
 'What a pity itis that Mr Weston ever thought of her',
 'I cannot agree with you papa you know I cannot',
 'Mr Weston is sucha goodhumoured pleasant excellent man that he thoroughly deservesa good wifeand you would not have had Miss Taylor live with usfor ever and bear all my odd humours when she might have a house of her own',
 'A house of her ownBut where is the advantage of a house of her own',
 'This is three times as largeAnd you have never any odd humoursmy dear',
 'How often we shall be going to see them and they coming to seeusWe shall be always meeting',
 'We must begin we must go and paywedding visit very soon',
 'My dear how am I to get so far',
 'Randalls is such a distance',
 'I could not walk half so far',
 'No papa nobody thought of your walking',
 'We must go in the carriageto be sure',
 'The carriage',
 'But James will not like to put the horses to forsuch a little wayand where are the poor horses to be while weare paying our visit',
 'They are to be put into Mr Westons stable papa',
 'You know wehave settled all that already',
 'We talked it all over with Mr Westonlast night',
 'And as for James you may be very sure he will always likegoing to Randalls because of his daughters being housemaid there',
 'I only doubt whether he will ever take us anywhere else',
 'That wasyour doing papa',
 'You got Hannah that good place',
 'Nobody thoughtof Hannah till you mentioned herJames is so obliged to you',
 'I am very glad I did think of her',
 'It was very lucky for I wouldnot have had poor James think himself slighted upon any accountand I am sure she will make a very good servant she is a civilprettyspoken girl I have a great opinion of her',
 'Whenever I see hershe always curtseys and asks me how I do in a very pretty mannerand when you have had her here to do needlework I observe shealways turns the lock of the door the right way and never bangs it',
 'I am sure she will be an excellent servant and it will be a greatcomfort to poor Miss Taylor to have somebody about her that she isused to see',
 'Whenever James goes over to see his daughter you knowshe will be hearing of us',
 'He will be able to tell her how weall are',
 'Emma spared no exertions to maintain this happier flow of ideasand hoped by the help of backgammon to get her father tolerablythrough the evening and be attacked by no regrets but her own',
 'The backgammontable was placed but a visitor immediately afterwardswalked in and made it unnecessary',
 'Mr Knightley a sensible man about seven or eightandthirty was notonly a very old and intimate friend of the family but particularlyconnected with it as the elder brother of Isabellas husband',
 'He lived about a mile from Highbury was a frequent visitorand always welcome and at this time more welcome than usualas coming directly from their mutual connexions in London',
 'He hadreturned to a late dinner after some days absence and now walkedup to Hartfield to say that all were well in Brunswick Square',
 'It was a happy circumstance and animated Mr Woodhouse for some time',
 'Mr Knightley had a cheerful manner which always did him goodand his many inquiries after poor Isabella and her children wereanswered most satisfactorily',
 'When this was over Mr Woodhousegratefully observed It is very kind of you Mr Knightley to comeout at this late hour to call upon us',
 'I am afraid you must havehad a shocking walk',
 'Not at all sir',
 'It is a beautiful moonlight night and so mildthat I must draw back from your great fire',
 'But you must have found it very damp and dirty',
 'I wish you maynot catch cold',
 'Dirty sir',
 'Look at my shoes',
 'Not a speck on them',
 'Well',
 'that is quite surprising for we have had a vast dealof rain here',
 'It rained dreadfully hard for half an hourwhile we were at breakfast',
 'I wanted them to put off the wedding',
 'By the byeI have not wished you joy',
 'Being pretty well awareof what sort of joy you must both be feeling I have been in no hurrywith my congratulations but I hope it all went off tolerably well',
 'How did you all behave',
 'Who cried most',
 'Ah',
 'poor Miss Taylor',
 'Tis a sad business',
 'Poor Mr and Miss Woodhouse if you please but I cannot possiblysay poor Miss Taylor',
 'I have a great regard for you and Emmabut when it comes to the question of dependence or independenceAtany rate it must be better to have only one to please than two',
 'Especially when one of those two is such a fanciful troublesome creature',
 'said Emma playfully',
 'That is what you have in your headI knowand what you would certainly say if my father were not by',
 'I believe it is very true my dear indeed said Mr Woodhousewith a sigh',
 'I am afraid I am sometimes very fanciful and troublesome',
 'My dearest papa',
 'You do not think I could mean you or supposeMr Knightley to mean you',
 'What a horrible idea',
 'Oh no',
 'I meantonly myself',
 'Mr Knightley loves to find fault with me you knowin a jokeit is all a joke',
 'We always say what we like to one another',
 'Mr Knightley in fact was one of the few people who could seefaults in Emma Woodhouse and the only one who ever told her of themand though this was not particularly agreeable to Emma herselfshe knew it would be so much less so to her father that she wouldnot have him really suspect such a circumstance as her not beingthought perfect by every body',
 'Emma knows I never flatter her said Mr Knightley but Imeant no reflection on any body',
 'Miss Taylor has been usedto have two persons to please she will now have but one',
 'The chances are that she must be a gainer',
 'Well said Emma willing to let it passyou want to hearabout the wedding and I shall be happy to tell you for we allbehaved charmingly',
 'Every body was punctual every body in theirbest looks not a tear and hardly a long face to be seen',
 'Oh nowe all felt that we were going to be only half a mile apartand were sure of meeting every day',
 'Dear Emma bears every thing so well said her father',
 'But Mr Knightley she is really very sorry to lose poor Miss Taylorand I am sure she will miss her more than she thinks for',
 'Emma turned away her head divided between tears and smiles',
 'It is impossible that Emma should not miss such a companionsaid Mr Knightley',
 'We should not like her so well as we do sirif we could suppose it but she knows how much the marriage is toMiss Taylors advantage she knows how very acceptable it must beat Miss Taylors time of life to be settled in a home of her ownand how important to her to be secure of a comfortable provisionand therefore cannot allow herself to feel so much pain as pleasure',
 'Every friend of Miss Taylor must be glad to have her so happilymarried',
 'And you have forgotten one matter of joy to me said Emmaand a very considerable onethat I made the match myself',
 'I made the match you know four years ago and to have it take placeand be proved in the right when so many people said Mr Weston wouldnever marry again may comfort me for any thing',
 'Mr Knightley shook his head at her',
 'Her father fondly repliedAh',
 'my dear I wish you would not make matches and foretell thingsfor whatever you say always comes to pass',
 'Pray do not make anymore matches',
 'I promise you to make none for myself papa but I must indeedfor other people',
 'It is the greatest amusement in the world',
 'Andafter such success you knowEvery body said that Mr Weston wouldnever marry again',
 'Oh dear no',
 'Mr Weston who had been a widowerso long and who seemed so perfectly comfortable without a wifeso constantly occupied either in his business in town or among hisfriends here always acceptable wherever he went always cheerfulMr Weston need not spend a single evening in the year alone if he didnot like it',
 'Oh no',
 'Mr Weston certainly would never marry again',
 'Some people even talked of a promise to his wife on her deathbedand others of the son and the uncle not letting him',
 'All mannerof solemn nonsense was talked on the subject but I believed noneof it',
 'Ever since the dayabout four years agothat Miss Taylor and Imet with him in Broadway Lane when because it began to drizzlehe darted away with so much gallantry and borrowed two umbrellasfor us from Farmer Mitchells I made up my mind on the subject',
 'I planned the match from that hour and when such success has blessedme in this instance dear papa you cannot think that I shall leaveoff matchmaking',
 'I do not understand what you mean by success said Mr Knightley',
 'Success supposes endeavour',
 'Your time has been properly anddelicately spent if you have been endeavouring for the last fouryears to bring about this marriage',
 'A worthy employment for a youngladys mind',
 'But if which I rather imagine your making the matchas you call it means only your planning it your saying to yourselfone idle day I think it would be a very good thing for Miss Taylorif Mr Weston were to marry her and saying it again to yourselfevery now and then afterwards why do you talk of success',
 'Whereis your merit',
 'What are you proud of',
 'You made a lucky guessand that is all that can be said',
 'And have you never known the pleasure and triumph of a lucky guessI pity youI thought you clevererfor depend upon it a luckyguess is never merely luck',
 'There is always some talent in it',
 'And as to my poor word success which you quarrel with I do notknow that I am so entirely without any claim to it',
 'You have drawntwo pretty pictures but I think there may be a thirda somethingbetween the donothing and the doall',
 'If I had not promoted Mr Westonsvisits here and given many little encouragements and smoothedmany little matters it might not have come to any thing after all',
 'I think you must know Hartfield enough to comprehend that',
 'A straightforward openhearted man like Weston and a rationalunaffected woman like Miss Taylor may be safely left to manage theirown concerns',
 'You are more likely to have done harm to yourselfthan good to them by interference',
 'Emma never thinks of herself if she can do good to othersrejoined Mr Woodhouse understanding but in part',
 'But my dearpray do not make any more matches they are silly things and break upones family circle grievously',
 'Only one more papa only for Mr Elton',
 'Poor Mr Elton',
 'Youlike Mr Elton papaI must look about for a wife for him',
 'There is nobody in Highbury who deserves himand he has beenhere a whole year and has fitted up his house so comfortablythat it would be a shame to have him single any longerand I thoughtwhen he was joining their hands today he looked so very much as ifhe would like to have the same kind office done for him',
 'I thinkvery well of Mr Elton and this is the only way I have of doinghim a service',
 'Mr Elton is a very pretty young man to be sure and a verygood young man and I have a great regard for him',
 'But if youwant to shew him any attention my dear ask him to comeand dine with us some day',
 'That will be a much better thing',
 'I dare say Mr Knightley will be so kind as to meet him',
 'With a great deal of pleasure sir at any time said Mr Knightleylaughing and I agree with you entirely that it will be a muchbetter thing',
 'Invite him to dinner Emma and help him to the bestof the fish and the chicken but leave him to chuse his own wife',
 'Depend upon it a man of six or sevenandtwenty can take careof himself',
 'CHAPTER IIMr Weston was a native of Highbury and born of a respectable familywhich for the last two or three generations had been rising intogentility and property',
 'He had received a good education buton succeeding early in life to a small independence had becomeindisposed for any of the more homely pursuits in which his brotherswere engaged and had satisfied an active cheerful mind and socialtemper by entering into the militia of his county then embodied',
 'Captain Weston was a general favourite and when the chancesof his military life had introduced him to Miss Churchillof a great Yorkshire family and Miss Churchill fell in lovewith him nobody was surprized except her brother and his wifewho had never seen him and who were full of pride and importancewhich the connexion would offend',
 'Miss Churchill however being of age and with the full commandof her fortunethough her fortune bore no proportion to thefamilyestatewas not to be dissuaded from the marriage and ittook place to the infinite mortification of Mr and Mrs Churchillwho threw her off with due decorum',
 'It was an unsuitable connexionand did not produce much happiness',
 'Mrs Weston ought to have foundmore in it for she had a husband whose warm heart and sweet tempermade him think every thing due to her in return for the great goodnessof being in love with him but though she had one sort of spiritshe had not the best',
 'She had resolution enough to pursueher own will in spite of her brother but not enough to refrainfrom unreasonable regrets at that brothers unreasonable angernor from missing the luxuries of her former home',
 'They lived beyondtheir income but still it was nothing in comparison of Enscombeshe did not cease to love her husband but she wanted at onceto be the wife of Captain Weston and Miss Churchill of Enscombe',
 'Captain Weston who had been considered especially by the Churchillsas making such an amazing match was proved to have much the worstof the bargain for when his wife died after a three years marriagehe was rather a poorer man than at first and with a child to maintain',
 'From the expense of the child however he was soon relieved',

In [175]:
## Text Mining & Modeling Part II

In [176]:
## case conversions ##

# Lower case
emma_sents[0].lower()

'[emma by jane austen 1816]\n\nvolume i\n\nchapter i\n\n\nemma woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; and had lived nearly twenty-one years in the world\nwith very little to distress or vex her.'

In [177]:
emma_sents[0]

'[Emma by Jane Austen 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEmma Woodhouse, handsome, clever, and rich, with a comfortable home\nand happy disposition, seemed to unite some of the best blessings\nof existence; and had lived nearly twenty-one years in the world\nwith very little to distress or vex her.'

In [178]:
# upper case
emma_sents[0].upper()

'[EMMA BY JANE AUSTEN 1816]\n\nVOLUME I\n\nCHAPTER I\n\n\nEMMA WOODHOUSE, HANDSOME, CLEVER, AND RICH, WITH A COMFORTABLE HOME\nAND HAPPY DISPOSITION, SEEMED TO UNITE SOME OF THE BEST BLESSINGS\nOF EXISTENCE; AND HAD LIVED NEARLY TWENTY-ONE YEARS IN THE WORLD\nWITH VERY LITTLE TO DISTRESS OR VEX HER.'

In [179]:
## removing stopwords ##
# e.g., stopwords: a, the , me etc.
# stopwords: Langauage and domain dependent; no universal or exhaustive list

# removing stopwords after tokenization
# write a function to filter stopwords from tokens

def remove_stopwords(tokens):
    
    # using English Language stopwords
    seq_sw = nltk.corpus.stopwords.words('english')
    
    tokens_f = [tn for tn in tokens if tn not in seq_sw]
    
    return tokens_f

In [180]:
# using user-defined remove_stopwords function on tokens
emma_words_fs = remove_stopwords(emma_words)

In [181]:
emma_words_fs[0:500]

['[',
 'Emma',
 'Jane',
 'Austen',
 '1816',
 ']',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Emma',
 'Woodhouse',
 ',',
 'handsome',
 ',',
 'clever',
 ',',
 'rich',
 ',',
 'comfortable',
 'home',
 'happy',
 'disposition',
 ',',
 'seemed',
 'unite',
 'best',
 'blessings',
 'existence',
 ';',
 'lived',
 'nearly',
 'twenty-one',
 'years',
 'world',
 'little',
 'distress',
 'vex',
 '.',
 'She',
 'youngest',
 'two',
 'daughters',
 'affectionate',
 ',',
 'indulgent',
 'father',
 ';',
 ',',
 'consequence',
 'sister',
 "'s",
 'marriage',
 ',',
 'mistress',
 'house',
 'early',
 'period',
 '.',
 'Her',
 'mother',
 'died',
 'long',
 'ago',
 'indistinct',
 'remembrance',
 'caresses',
 ';',
 'place',
 'supplied',
 'excellent',
 'woman',
 'governess',
 ',',
 'fallen',
 'little',
 'short',
 'mother',
 'affection',
 '.',
 'Sixteen',
 'years',
 'Miss',
 'Taylor',
 'Mr.',
 'Woodhouse',
 "'s",
 'family',
 ',',
 'less',
 'governess',
 'friend',
 ',',
 'fond',
 'daughters',
 ',',
 'particularly',
 'Emma',
 '.',
 'Between',
 '_them_',
 'intimacy',
 'sisters',
 '.',
 'Even',
 'Miss',
 'Taylor',
 'ceased',
 'hold',
 'nominal',
 'office',
 'governess',
 ',',
 'mildness',
 'temper',
 'hardly',
 'allowed',
 'impose',
 'restraint',
 ';',
 'shadow',
 'authority',
 'long',
 'passed',
 'away',
 ',',
 'living',
 'together',
 'friend',
 'friend',
 'mutually',
 'attached',
 ',',
 'Emma',
 'liked',
 ';',
 'highly',
 'esteeming',
 'Miss',
 'Taylor',
 "'s",
 'judgment',
 ',',
 'directed',
 'chiefly',
 '.',
 'The',
 'real',
 'evils',
 ',',
 'indeed',
 ',',
 'Emma',
 "'s",
 'situation',
 'power',
 'rather',
 'much',
 'way',
 ',',
 'disposition',
 'think',
 'little',
 'well',
 ';',
 'disadvantages',
 'threatened',
 'alloy',
 'many',
 'enjoyments',
 '.',
 'The',
 'danger',
 ',',
 'however',
 ',',
 'present',
 'unperceived',
 ',',
 'means',
 'rank',
 'misfortunes',
 '.',
 'Sorrow',
 'came',
 '--',
 'gentle',
 'sorrow',
 '--',
 'shape',
 'disagreeable',
 'consciousness.',
 '--',
 'Miss',
 'Taylor',
 'married',
 '.',
 'It',
 'Miss',
 'Taylor',
 "'s",
 'loss',
 'first',
 'brought',
 'grief',
 '.',
 'It',
 'wedding-day',
 'beloved',
 'friend',
 'Emma',
 'first',
 'sat',
 'mournful',
 'thought',
 'continuance',
 '.',
 'The',
 'wedding',
 ',',
 'bride-people',
 'gone',
 ',',
 'father',
 'left',
 'dine',
 'together',
 ',',
 'prospect',
 'third',
 'cheer',
 'long',
 'evening',
 '.',
 'Her',
 'father',
 'composed',
 'sleep',
 'dinner',
 ',',
 'usual',
 ',',
 'sit',
 'think',
 'lost',
 '.',
 'The',
 'event',
 'every',
 'promise',
 'happiness',
 'friend',
 '.',
 'Mr.',
 'Weston',
 'man',
 'unexceptionable',
 'character',
 ',',
 'easy',
 'fortune',
 ',',
 'suitable',
 'age',
 ',',
 'pleasant',
 'manners',
 ';',
 'satisfaction',
 'considering',
 'self-denying',
 ',',
 'generous',
 'friendship',
 'always',
 'wished',
 'promoted',
 'match',
 ';',
 'black',
 'morning',
 "'s",
 'work',
 '.',
 'The',
 'want',
 'Miss',
 'Taylor',
 'would',
 'felt',
 'every',
 'hour',
 'every',
 'day',
 '.',
 'She',
 'recalled',
 'past',
 'kindness',
 '--',
 'kindness',
 ',',
 'affection',
 'sixteen',
 'years',
 '--',
 'taught',
 'played',
 'five',
 'years',
 'old',
 '--',
 'devoted',
 'powers',
 'attach',
 'amuse',
 'health',
 '--',
 'nursed',
 'various',
 'illnesses',
 'childhood',
 '.',
 'A',
 'large',
 'debt',
 'gratitude',
 'owing',
 ';',
 'intercourse',
 'last',
 'seven',
 'years',
 ',',
 'equal',
 'footing',
 'perfect',
 'unreserve',
 'soon',
 'followed',
 'Isabella',
 "'s",
 'marriage',
 ',',
 'left',
 ',',
 'yet',
 'dearer',
 ',',
 'tenderer',
 'recollection',
 '.',
 'She',
 'friend',
 'companion',
 'possessed',
 ':',
 'intelligent',
 ',',
 'well-informed',
 ',',
 'useful',
 ',',
 'gentle',
 ',',
 'knowing',
 'ways',
 'family',
 ',',
 'interested',
 'concerns',
 ',',
 'peculiarly',
 'interested',
 ',',
 'every',
 'pleasure',
 ',',
 'every',
 'scheme',
 '--',
 'one',
 'could',
 'speak',
 'every',
 'thought',
 'arose',
 ',',
 'affection',
 'could',
 'never',
 'find',
 'fault',
 '.',
 'How',
 'bear',
 'change',
 '?',
 '--',
 'It',
 'true',
 'friend',
 'going',
 'half',
 'mile',
 ';',
 'Emma',
 'aware',
 'great',
 'must',
 'difference',
 'Mrs.',
 'Weston',
 ',',
 'half',
 'mile',
 ',',
 'Miss',
 'Taylor',
 'house',
 ';',
 'advantages',
 ',',
 'natural',
 'domestic',
 ',',
 'great',
 'danger',
 'suffering',
 'intellectual',
 'solitude',
 '.',
 'She',
 'dearly',
 'loved',
 'father',
 ',',
 'companion',
 '.',
 'He',
 'could',
 'meet',
 'conversation',
 ',',
 'rational',
 'playful',
 '.',
 'The',
 'evil',
 'actual',
 'disparity',
 'ages',
 '(',
 'Mr.',
 'Woodhouse',
 'married',
 'early',
 ')',
 'much',
 'increased',
 'constitution',
 'habits',
 ';',
 'valetudinarian',
 'life',
 ',',
 'without',
 'activity',
 'mind',
 'body',
 ',',
 'much',
 'older',
 'man',
 'ways',
 'years',
 ';',
 'though',
 'everywhere',
 'beloved',
 'friendliness',
 'heart',
 'amiable',
 'temper',
 ',',
 'talents',
 'could',
 'recommended',
 'time',
 '.',
 'Her',
 'sister',
 ',',
 'though',
 'comparatively',
 'little',
 'removed',
 'matrimony',
 ',',
 'settled']

In [182]:
# no. of tokens after removal process
len(emma_words_fs)

112702

In [183]:
len(emma_words)

191855

In [184]:
# List of all English stopwords
# however, negations Like not and no might be important, e.g., sentiment analysis
nltk.corpus.stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [185]:
## correcting words ##
# example: spelling mistakes, repeated characters

# repeated characters

# using a regex pattern and match groups (groups 1, 2, and 3) with the pattern r'\1\2\3'
# using wordnet corpus to check for valid words

# write a function to eliminate repeated characters from tokens
from nltk.corpus import wordnet

def remove_repeated_characters(tokens):
    # characters that occur twice among other characters
    pattern = re.compile(r'(\w*)(\w)\2(\w*)')
    
    # using backreferences to construct the replacement for the pattern
    # e.g., \1 will be replaced with the substring matched by group 1 in the pattern
    # keep one insatnce of the repeating character in group 2
    repl = r'\1\2\3'
    
    def replace(tkn):
        # check for semantically correct word
        if wordnet.synsets(tkn):
            return tkn
        # replace the pattern
        tkn_c = pattern.sub(repl, tkn)
        
        # recursive call
        return replace(tkn_c) if tkn_c != tkn else tkn_c
        
    # correct each token
    tokens_c = [replace(tn) for tn in tokens]
    return tokens_c

In [186]:
# e.g.,
test1 = "hmmmmmmmmmm, ohhh, thanks..., reallllyyy, woooooow"

test1_tokens = nltk.word_tokenize(test1)

remove_repeated_characters(test1_tokens)

['hm', ',', 'oh', ',', 'thanks', '...', ',', 'really', ',', 'wow']

In [187]:
# using user-defined remove_repeated_characters function on tokens
emma_words_r = remove_repeated_characters(emma_words_fs)

In [188]:
emma_words_r[0:500]

['[',
 'Ema',
 'Jane',
 'Austen',
 '1816',
 ']',
 'VOLUME',
 'I',
 'CHAPTER',
 'I',
 'Ema',
 'Wodhouse',
 ',',
 'handsome',
 ',',
 'clever',
 ',',
 'rich',
 ',',
 'comfortable',
 'home',
 'happy',
 'disposition',
 ',',
 'seemed',
 'unite',
 'best',
 'blessings',
 'existence',
 ';',
 'lived',
 'nearly',
 'twenty-one',
 'years',
 'world',
 'little',
 'distress',
 'vex',
 '.',
 'She',
 'youngest',
 'two',
 'daughters',
 'affectionate',
 ',',
 'indulgent',
 'father',
 ';',
 ',',
 'consequence',
 'sister',
 "'s",
 'marriage',
 ',',
 'mistress',
 'house',
 'early',
 'period',
 '.',
 'Her',
 'mother',
 'died',
 'long',
 'ago',
 'indistinct',
 'remembrance',
 'caresses',
 ';',
 'place',
 'supplied',
 'excellent',
 'woman',
 'governess',
 ',',
 'fallen',
 'little',
 'short',
 'mother',
 'affection',
 '.',
 'Sixteen',
 'years',
 'Miss',
 'Taylor',
 'Mr.',
 'Wodhouse',
 "'s",
 'family',
 ',',
 'less',
 'governess',
 'friend',
 ',',
 'fond',
 'daughters',
 ',',
 'particularly',
 'Ema',
 '.',
 'Between',
 '_them_',
 'intimacy',
 'sisters',
 '.',
 'Even',
 'Miss',
 'Taylor',
 'ceased',
 'hold',
 'nominal',
 'office',
 'governess',
 ',',
 'mildness',
 'temper',
 'hardly',
 'allowed',
 'impose',
 'restraint',
 ';',
 'shadow',
 'authority',
 'long',
 'passed',
 'away',
 ',',
 'living',
 'together',
 'friend',
 'friend',
 'mutually',
 'attached',
 ',',
 'Ema',
 'liked',
 ';',
 'highly',
 'esteeming',
 'Miss',
 'Taylor',
 "'s",
 'judgment',
 ',',
 'directed',
 'chiefly',
 '.',
 'The',
 'real',
 'evils',
 ',',
 'indeed',
 ',',
 'Ema',
 "'s",
 'situation',
 'power',
 'rather',
 'much',
 'way',
 ',',
 'disposition',
 'think',
 'little',
 'well',
 ';',
 'disadvantages',
 'threatened',
 'alloy',
 'many',
 'enjoyments',
 '.',
 'The',
 'danger',
 ',',
 'however',
 ',',
 'present',
 'unperceived',
 ',',
 'means',
 'rank',
 'misfortunes',
 '.',
 'Sorrow',
 'came',
 '--',
 'gentle',
 'sorrow',
 '--',
 'shape',
 'disagreeable',
 'consciousnes.',
 '--',
 'Miss',
 'Taylor',
 'married',
 '.',
 'It',
 'Miss',
 'Taylor',
 "'s",
 'loss',
 'first',
 'brought',
 'grief',
 '.',
 'It',
 'weding-day',
 'beloved',
 'friend',
 'Ema',
 'first',
 'sat',
 'mournful',
 'thought',
 'continuance',
 '.',
 'The',
 'wedding',
 ',',
 'bride-people',
 'gone',
 ',',
 'father',
 'left',
 'dine',
 'together',
 ',',
 'prospect',
 'third',
 'cheer',
 'long',
 'evening',
 '.',
 'Her',
 'father',
 'composed',
 'sleep',
 'dinner',
 ',',
 'usual',
 ',',
 'sit',
 'think',
 'lost',
 '.',
 'The',
 'event',
 'every',
 'promise',
 'happiness',
 'friend',
 '.',
 'Mr.',
 'Weston',
 'man',
 'unexceptionable',
 'character',
 ',',
 'easy',
 'fortune',
 ',',
 'suitable',
 'age',
 ',',
 'pleasant',
 'manners',
 ';',
 'satisfaction',
 'considering',
 'self-denying',
 ',',
 'generous',
 'friendship',
 'always',
 'wished',
 'promoted',
 'match',
 ';',
 'black',
 'morning',
 "'s",
 'work',
 '.',
 'The',
 'want',
 'Miss',
 'Taylor',
 'would',
 'felt',
 'every',
 'hour',
 'every',
 'day',
 '.',
 'She',
 'recalled',
 'past',
 'kindness',
 '--',
 'kindness',
 ',',
 'affection',
 'sixteen',
 'years',
 '--',
 'taught',
 'played',
 'five',
 'years',
 'old',
 '--',
 'devoted',
 'powers',
 'attach',
 'amuse',
 'health',
 '--',
 'nursed',
 'various',
 'illnesses',
 'childhood',
 '.',
 'A',
 'large',
 'debt',
 'gratitude',
 'owing',
 ';',
 'intercourse',
 'last',
 'seven',
 'years',
 ',',
 'equal',
 'footing',
 'perfect',
 'unreserve',
 'soon',
 'followed',
 'Isabella',
 "'s",
 'marriage',
 ',',
 'left',
 ',',
 'yet',
 'dearer',
 ',',
 'tenderer',
 'recollection',
 '.',
 'She',
 'friend',
 'companion',
 'possessed',
 ':',
 'intelligent',
 ',',
 'well-informed',
 ',',
 'useful',
 ',',
 'gentle',
 ',',
 'knowing',
 'ways',
 'family',
 ',',
 'interested',
 'concerns',
 ',',
 'peculiarly',
 'interested',
 ',',
 'every',
 'pleasure',
 ',',
 'every',
 'scheme',
 '--',
 'one',
 'could',
 'speak',
 'every',
 'thought',
 'arose',
 ',',
 'affection',
 'could',
 'never',
 'find',
 'fault',
 '.',
 'How',
 'bear',
 'change',
 '?',
 '--',
 'It',
 'true',
 'friend',
 'going',
 'half',
 'mile',
 ';',
 'Ema',
 'aware',
 'great',
 'must',
 'difference',
 'Mrs.',
 'Weston',
 ',',
 'half',
 'mile',
 ',',
 'Miss',
 'Taylor',
 'house',
 ';',
 'advantages',
 ',',
 'natural',
 'domestic',
 ',',
 'great',
 'danger',
 'suffering',
 'intellectual',
 'solitude',
 '.',
 'She',
 'dearly',
 'loved',
 'father',
 ',',
 'companion',
 '.',
 'He',
 'could',
 'meet',
 'conversation',
 ',',
 'rational',
 'playful',
 '.',
 'The',
 'evil',
 'actual',
 'disparity',
 'ages',
 '(',
 'Mr.',
 'Wodhouse',
 'married',
 'early',
 ')',
 'much',
 'increased',
 'constitution',
 'habits',
 ';',
 'valetudinarian',
 'life',
 ',',
 'without',
 'activity',
 'mind',
 'body',
 ',',
 'much',
 'older',
 'man',
 'ways',
 'years',
 ';',
 'though',
 'everywhere',
 'beloved',
 'friendliness',
 'heart',
 'amiable',
 'temper',
 ',',
 'talents',
 'could',
 'recommended',
 'time',
 '.',
 'Her',
 'sister',
 ',',
 'though',
 'comparatively',
 'little',
 'removed',
 'matrimony',
 ',',
 'settled']

In [189]:
## stemming ##

# stems or word stem: the base or root form of a word
# used to create new words by attaching affixes (this process is called inflection)
# e.g., texts, texting, texted

# stemming is reverse of inflection
# useful in classifying or clustering text, and even in information retrieval

# using different NLTK interfaces

# First approach: Porter stemmer
# most popular
# phase-wise rules for reduction of inflections to their stems

from nltk.stem import PorterStemmer

# create an instance of PorterStemmer class
# using PorterStemmer function
pstem = PorterStemmer()

In [190]:
pstem

In [191]:
# using stem method to obtain the stem of a word
pstem.stem('texts')

'text'

In [192]:
pstem.stem('texted')

'text'

In [193]:
pstem. stem( 'texting')

'text'

In [194]:
pstem.stem('flying')

'fli'

In [195]:
pstem.stem('strangulate')

'strangul'

In [196]:
# Second approach: Lancaster stemmer
# iterative, rule-based steps for removal/replacement of affixes to their stems

from nltk.stem import LancasterStemmer

# create an instance of LancasterStemmer class
# using LancasterStemmer function
lstem = LancasterStemmer()

In [197]:
lstem

In [198]:
# using stem method to obtain the root form of a word
lstem.stem('texts')

'text'

In [199]:
lstem.stem('texted')

'text'

In [200]:
lstem.stem('texting')

'text'

In [201]:
lstem.stem('flying')

'fly'

In [202]:
lstem.stem('strangulate')

'strangulate'

In [203]:
## Lemmatization ##

# similar to stemming
# Note: in stemming, root or base form of a word may not always be a Lexicographically correct word
# (may not be present in the dictionary)
# however, in lemmatization, root or base form of a word will always be present in the dictionary

# root form or Lemma is formed by removing the affixes from the word if and only if the Lemma is present in the dictionary

from nltk.stem import WordNetLemmatizer

# using an instance of WordNetLemmatizer class
# using WordNetLemmatizer function
wnl = WordNetLemmatizer()

In [204]:
wnl

In [205]:
# using lemmatize function to obtain the Lemma of a word
# it uses word and its part of speech
# e.g., nouns
# using second argument to indicate noun as 'n'
wnl.lemmatize('bikes', 'n')

'bike'

In [206]:
wnl.lemmatize('trains', 'n')

'train'

In [207]:
# e.g., verbs
# using second argument to indicate verb as 'v'
wnl.lemmatize('writing', 'v')

'write'

In [208]:
wnl.lemmatize('typing', 'v')

'type'

In [209]:
wnl.lemmatize('spoken', 'v')

'speak'

In [210]:
# e.g., adjectives
# using second argument to indicate adjective as 'a'
wnl.lemmatize('better', 'a')

'good'

In [211]:
wnl.lemmatize('hotter', 'a')

'hot'

In [213]:
## PoS tagging ##

# main PoS: noun, verb, adjective, and adverb
# Labeling words with their PoS tags

# using the Penn Treebank notation for POS tagging
# contains most widely used PoS tag set

# using nltk 's recommended pos_tag() function

# tokenize text into tokens using tokenize_text function
#emma_tokens = tokenize_text(emma_sents[0])#not worked for me
emma_tokens = nltk.word_tokenize(emma_sents[0])

# using pos_tag function to annotate POS tags
emma_tokens_t = nltk.pos_tag(emma_tokens, tagset='universal')

In [214]:
emma_tokens_t

[('[', 'NOUN'),
 ('Emma', 'NOUN'),
 ('by', 'ADP'),
 ('Jane', 'NOUN'),
 ('Austen', 'NOUN'),
 ('1816', 'NUM'),
 (']', 'NOUN'),
 ('VOLUME', 'NOUN'),
 ('I', 'PRON'),
 ('CHAPTER', 'VERB'),
 ('I', 'PRON'),
 ('Emma', 'NOUN'),
 ('Woodhouse', 'NOUN'),
 (',', '.'),
 ('handsome', 'NOUN'),
 (',', '.'),
 ('clever', 'NOUN'),
 (',', '.'),
 ('and', 'CONJ'),
 ('rich', 'ADJ'),
 (',', '.'),
 ('with', 'ADP'),
 ('a', 'DET'),
 ('comfortable', 'ADJ'),
 ('home', 'NOUN'),
 ('and', 'CONJ'),
 ('happy', 'ADJ'),
 ('disposition', 'NOUN'),
 (',', '.'),
 ('seemed', 'VERB'),
 ('to', 'PRT'),
 ('unite', 'VERB'),
 ('some', 'DET'),
 ('of', 'ADP'),
 ('the', 'DET'),
 ('best', 'ADJ'),
 ('blessings', 'NOUN'),
 ('of', 'ADP'),
 ('existence', 'NOUN'),
 (';', '.'),
 ('and', 'CONJ'),
 ('had', 'VERB'),
 ('lived', 'VERB'),
 ('nearly', 'ADV'),
 ('twenty-one', 'NUM'),
 ('years', 'NOUN'),
 ('in', 'ADP'),
 ('the', 'DET'),
 ('world', 'NOUN'),
 ('with', 'ADP'),
 ('very', 'ADV'),
 ('little', 'ADJ'),
 ('to', 'PRT'),
 ('distress', 'VERB'),
 ('or', 'CONJ'),
 ('vex', 'VERB'),
 ('her', 'PRON'),
 ('.', '.')]

In [219]:
## write a function to combine or chain all the transformation steps for a text corpus
#includes expanding contractions, PoS tagging, Lemmatization,
#special character removal, stopword removal, tokenization

import re
import nltk
import string

# Load all the English stopwords
seq_sw1 = nltk.corpus.stopwords.words('english')

# Load contraction mappings
# contraction_map

# Load the Lemmatizer
from nltk.stem import WordNetLemmatizer
wnl1 = WordNetLemmatizer()

# define a function to tokenize text into tokens
def tokenize_text(text):
    tokens = nltk.word_tokenize(text)
    tokens = [tn.strip() for tn in tokens]
    return tokens

# define a function for expanding contractions
def expand_contractions(text, mapping):

    # pattern for matching contractions with their expansions
    pattern = re.compile('({})'.format('|'.join(mapping.keys())), flags=re. IGNORECASE|re.DOTALL)
    
    def expand_map(contraction):
        # using group method to access subgroups of the match
        match = contraction.group(0)

        # to retain the correct case of the word
        first_char = match[0]
        
        # find out the expansion
        expansion = mapping.get(match) if mapping.get(match) else mapping.get(match.lower())
        expansion = first_char + expansion[1:]
        return expansion
        
    # using sub method to replace all contractions with their expansions for a sentence
    # function expand_map will be called for every non-overlapping occurrence of the pattern
    expand_text = pattern.sub(expand_map, text)
    return expand_text


# define a function for lemmatization of text based on POS tags

from nltk.corpus import wordnet as wn

# Annotate text tokens with POS tags
def pos_tag_text(text):

    # convert Penn treebank tag to wordnet tag
    # since the WordNetLemmatizer checks for POS tag annotations based on WordNet formats
    def penn_to_wn_tags(pos_tag):
        if pos_tag.startswith(')'):
            return wn.ADJ
        elif pos_tag.startswith('V'):
            return wn. VERB
        elif pos_tag.startswith('N'):
            return wn. NOUN
        elif pos_tag.startswith('R'):
            return wn.ADV
        else:
            return None
    
    # tokenize text into tokens using tokenize_text function
    tokens = tokenize_text(text)
    
    # using pos_tag function to annotate POS tags
    tokens_t = nltk.pos_tag(tokens, tagset='universal')

    # convert the POS tags from the Penn treebank syntax to WordNet syntax
    tokens_p = [(word.lower(), penn_to_wn_tags(pos_tag)) for word, pos_tag in tokens_t]
    
    return tokens_p

# Lemmatize text based on POS tags
def lemmatize_text(text):

    # PoS tagging
    tokens_p = pos_tag_text(text)
    
    # Lemmatize the text
    tokens_lm = [wnl1. lemmatize(word, pos_tag) if pos_tag else word for word, pos_tag in tokens_p]
    
    # concatenate tokens
    text_lm = ''.join(tokens_lm)
    
    return text_lm

# define a function to remove special symbols and characters
def remove_special_characters(text):

    # tokenize text into tokens using tokenize_text function
    tokens = tokenize_text(text)

    pattern = re.compile('[{}]' .format(re.escape(string.punctuation)))
    tokens_f = filter(None, [pattern.sub('', tn) for tn in tokens])
    
    text_f = ''.join(tokens_f)
    
    return text_f

# define a function to remove stopwords from our text data
def remove_stopwords(text):

    # tokenize text into tokens using tokenize_text function
    tokens = tokenize_text(text)
    
    # using English stopwords list for removal
    tokens_f = [tn for tn in tokens if tn not in seq_sw1]
    
    text_f = ' '.join(tokens_f)
    
    return text_f

# define a function to chain all the transformation steps
def transform_corpus(corpus, tokenize=False):

    corpus_t = []

    for text in corpus:
        text = expand_contractions(text, contraction_map)
        text = lemmatize_text(text)
        text = remove_special_characters(text)
        text = remove_stopwords(text)
        
        corpus_t.append(text)
        
        if tokenize:
            text = tokenize_text(text)
            corpus_t.append(text)

    return corpus_t

In [220]:
# using transform_corpus function to transform or normlaize the text corpus
emma_t = transform_corpus(emma_sents)

In [221]:
emma_t

['emmabyjaneausten1816volumeichapteriemmawoodhousehandsomecleverandrichwithacomfortablehomeandhappydispositionseemtounitesomeofthebestblessingofexistenceandhavelivenearlytwentyoneyearintheworldwithverylittletodistressorvexher',
 'shebetheyoungestofthetwodaughterofamostaffectionateindulgentfatherandhaveinconsequenceofhersistersmarriagebemistressofhishousefromaveryearlyperiod',
 'hermotherhavedietoolongagoforhertohavemorethananindistinctremembranceofhercaressandherplacehavebesupplybyanexcellentwomanasgovernesswhohavefalllittleshortofamotherinaffection',
 'sixteenyearhavemisstaylorbeinmrwoodhousesfamilylessasagovernessthanafriendveryfondofbothdaughterbutparticularlyofemma',
 'betweenthemitbemoretheintimacyofsister',
 'evenbeforemisstaylorhaveceasetoholdthenominalofficeofgovernessthemildnessofhertemperhavehardlyallowhertoimposeanyrestraintandtheshadowofauthoritybenowlongpassawaytheyhavebelivetogetherasfriendandfriendverymutuallyattachandemmadojustwhatshelikehighlyesteemmisstaylorsjudgmentbutdirectchieflybyherown',
 'therealevilindeedofemmassituationbethepowerofhaverathertoomuchherownwayandadispositiontothinkalittletoowellofherselfthesebethedisadvantagewhichthreatenalloytohermanyenjoyment',
 'thedangerhoweverbeatpresentsounperceivedthattheydonotbyanymeanrankasmisfortunewithher',
 'sorrowcomeagentlesorrowbutnotatallintheshapeofanydisagreeableconsciousnessmisstaylormarry',
 'itbemisstaylorslosswhichfirstbringgrief',
 'itbeontheweddingdayofthisbelovedfriendthatemmafirstsitinmournfulthoughtofanycontinuance',
 'theweddingoverandthebridepeoplegoherfatherandherselfbeleavetodinetogetherwithnoprospectofathirdtocheeralongevening',
 'herfathercomposehimselftosleepafterdinnerasusualandshehavethenonlytositandthinkofwhatshehavelose',
 'theeventhaveeverypromiseofhappinessforherfriend',
 'mrwestonbeamanofunexceptionablecharactereasyfortunesuitableageandpleasantmannerandtherebesomesatisfactioninconsiderwithwhatselfdenyinggenerousfriendshipshehavealwayswishandpromotethematchbutitbeablackmorningsworkforher',
 'thewantofmisstaylorwouldbefelteveryhourofeveryday',
 'sherecallherpastkindnessthekindnesstheaffectionofsixteenyearhowshehaveteachandhowshehaveplaywithherfromfiveyearoldhowshehavedevoteallherpowertoattachandamuseherinhealthandhownursedherthroughthevariousillnessofchildhood',
 'alargedebtofgratitudebeoweherebuttheintercourseofthelastsevenyeartheequalfootingandperfectunreservewhichhavesoonfollowisabellasmarriageontheirbeleavetoeachotherbeyetadearertendererrecollection',
 'shehavebeafriendandcompanionsuchasfewpossessintelligentwellinformedusefulgentleknowallthewayofthefamilyinterestedinallitsconcernandpeculiarlyinterestedinherselfineverypleasureeveryschemeofhersonetowhomshecouldspeakeverythoughtasitariseandwhohavesuchanaffectionforheracouldneverfindfault',
 'howbeshetobearthechangeitbetruethatherfriendbegoonlyhalfamilefromthembutemmabeawarethatgreatmustbethedifferencebetweenamrswestononlyhalfamilefromthemandamisstaylorinthehouseandwithallheradvantagenaturalanddomesticshebenowingreatdangerofsufferfromintellectualsolitude',
 'shedearlyloveherfatherbuthebenocompanionforher',
 'hecouldnotmeetherinconversationrationalorplayful',
 'theeviloftheactualdisparityintheirageandmrwoodhousehavenotmarryearlybemuchincreasebyhisconstitutionandhabitforhavebeavaletudinarianallhislifewithoutactivityofmindorbodyhebeamucholdermaninwaythaninyearandthougheverywherebelovedforthefriendlinessofhisheartandhisamiabletemperhistalentcouldnothaverecommendhimatanytime',
 'hersisterthoughcomparativelybutlittleremovebymatrimonybesettleinlondononlysixteenmileoffbemuchbeyondherdailyreachandmanyalongoctoberandnovembereveningmustbestrugglethroughathartfieldbeforechristmasbringthenextvisitfromisabellaandherhusbandandtheirlittlechildtofillthehouseandgiveherpleasantsocietyagain',
 'highburythelargeandpopulousvillagealmostamounttoatowntowhichhartfieldinspiteofitsseparatelawnandshrubberyandnamedoreallybelongaffordhernoequal',
 'thewoodhousesbefirstinconsequencethere',
 'alllookuptothem',
 'shehavemanyacquaintanceintheplaceforherfatherbeuniversallycivilbutnotoneamongthemwhocouldbeacceptinlieuofmisstaylorforevenhalfaday',
 'itbeamelancholychangeandemmacouldnotbutsighoveritandwishforimpossiblethingtillherfatherawokeandmakeitnecessarytobecheerful',
 'hisspiritrequiresupport',
 'hebeanervousmaneasilydepressfondofeverybodythathebeusetoandhattopartwiththemhatchangeofeverykind',
 'matrimonyastheoriginofchangebealwaysdisagreeableandhebebynomeanyetreconciletohisowndaughtersmarryingnorcouldeverspeakofherbutwithcompassionthoughithavebeentirelyamatchofaffectionwhenhebenowobligetopartwithmisstaylortooandfromhishabitofgentleselfishnessandofbeneverabletosupposethatotherpeoplecouldfeeldifferentlyfromhimselfhebeverymuchdisposetothinkmisstaylorhavedoassadathingforherselfasforthemandwouldhavebeagreatdealhappierifshehavespendalltherestofherlifeathartfield',
 'emmasmileandchatascheerfullyasshecouldtokeephimfromsuchthoughtbutwhenteacomeitbeimpossibleforhimnottosayexactlyashehavesayatdinnerpoormisstayloriwishshebehereagain',
 'whatapityitbethatmrwestoneverthinkofher',
 'icannotagreewithyoupapayouknowicannot',
 'mrwestonbesuchagoodhumouredpleasantexcellentmanthathethoroughlydeserveagoodwifeandyouwouldnothavehavemisstaylorlivewithusforeverandbearallmyoddhumourwhenshemighthaveahouseofherown',
 'ahouseofherownbutwherebetheadvantageofahouseofherown',
 'thisbethreetimeaslargeandyouhaveneveranyoddhumourmydear',
 'howoftenweshallbegotoseethemandtheycometoseeusweshallbealwaysmeeting',
 'wemustbeginwemustgoandpaywedvisitverysoon',
 'mydearhowbeitogetsofar',
 'randallsbesuchadistance',
 'icouldnotwalkhalfsofar',
 'nopapanobodythoughtofyourwalking',
 'wemustgointhecarriagetobesure',
 'thecarriage',
 'butjameswillnotliketoputthehorsetoforsuchalittlewayandwherebethepoorhorsetobewhilewebepayourvisit',
 'theybetobeputintomrwestonsstablepapa',
 'youknowwehavesettleallthatalready',
 'wetalkitalloverwithmrwestonlastnight',
 'andasforjamesyoumaybeverysurehewillalwayslikegotorandallsbecauseofhisdaughtersbehousemaidthere',
 'ionlydoubtwhetherhewillevertakeusanywhereelse',
 'thatbeyourdopapa',
 'yougethannahthatgoodplace',
 'nobodythoughtofhannahtillyoumentionherjamesbesoobligedtoyou',
 'ibeverygladidothinkofher',
 'itbeveryluckyforiwouldnothavehavepoorjamesthinkhimselfslightuponanyaccountandibesureshewillmakeaverygoodservantshebeacivilprettyspokengirlihaveagreatopinionofher',
 'wheneveriseehershealwayscurtseyandasksmehowidoinaveryprettymannerandwhenyouhavehaveherheretodoneedleworkiobserveshealwaysturnthelockofthedoortherightwayandneverbangit',
 'ibesureshewillbeanexcellentservantanditwillbeagreatcomforttopoormisstaylortohavesomebodyaboutherthatshebeusetosee',
 'wheneverjamesgoovertoseehisdaughteryouknowshewillbehearingofus',
 'hewillbeabletotellherhowweallbe',
 'emmasparnoexertiontomaintainthishappierflowofideaandhopbythehelpofbackgammontogetherfathertolerablythroughtheeveningandbeattackbynoregretbutherown',
 'thebackgammontablebeplacebutavisitorimmediatelyafterwardswalkinandmakeitunnecessary',
 'mrknightleyasensiblemanaboutsevenoreightandthirtybenotonlyaveryoldandintimatefriendofthefamilybutparticularlyconnectwithitastheelderbrotherofisabellashusband',
 'heliveaboutamilefromhighburybeafrequentvisitorandalwayswelcomeandatthistimemorewelcomethanusualascomedirectlyfromtheirmutualconnexioninlondon',
 'hehavereturntoalatedinneraftersomedayabsenceandnowwalkuptohartfieldtosaythatallbewellinbrunswicksquare',
 'itbeahappycircumstanceandanimatemrwoodhouseforsometime',
 'mrknightleyhaveacheerfulmannerwhichalwaysdohimgoodandhismanyinquiryafterpoorisabellaandherchildbeanswermostsatisfactorily',
 'whenthisbeovermrwoodhousegratefullyobserveitbeverykindofyoumrknightleytocomeoutatthislatehourtocalluponus',
 'ibeafraidyoumusthavehaveashockingwalk',
 'notatallsir',
 'itbeabeautifulmoonlightnightandsomildthatimustdrawbackfromyourgreatfire',
 'butyoumusthavefinditverydampanddirty',
 'iwishyoumaynotcatchcold',
 'dirtysir',
 'lookatmyshoe',
 'notaspeckonthem',
 'well',
 'thatbequitesurprisingforwehavehaveavastdealofrainhere',
 'itraindreadfullyhardforhalfanhourwhilewebeatbreakfast',
 'iwantthemtoputoffthewedding',
 'bythebyeihavenotwishyoujoy',
 'beprettywellawareofwhatsortofjoyyoumustbothbefeelingihavebeinnohurrywithmycongratulationbutihopeitallgoofftolerablywell',
 'howdoyouallbehave',
 'whocrymost',
 'ah',
 'poormisstaylor',
 'tbeasadbusiness',
 'poormrandmisswoodhouseifyoupleasebuticannotpossiblysaypoormisstaylor',
 'ihaveagreatregardforyouandemmabutwhenitcometothequestionofdependenceorindependenceatanyrateitmustbebettertohaveonlyonetopleasethantwo',
 'especiallywhenoneofthosetwobesuchafancifultroublesomecreature',
 'sayemmaplayfully',
 'thatbewhatyouhaveinyourheadiknowandwhatyouwouldcertainlysayifmyfatherbenotby',
 'ibelieveitbeverytruemydearindeedsaymrwoodhousewithasigh',
 'ibeafraidibesometimesveryfancifulandtroublesome',
 'mydearestpapa',
 'youdonotthinkicouldmeanyouorsupposemrknightleytomeanyou',
 'whatahorribleidea',
 'ohno',
 'imeanonlymyself',
 'mrknightleylovetofindfaultwithmeyouknowinajokeitbeallajoke',
 'wealwayssaywhatweliketooneanother',
 'mrknightleyinfactbeoneofthefewpeoplewhocouldseefaultinemmawoodhouseandtheonlyonewhoevertellherofthemandthoughthisbenotparticularlyagreeabletoemmaherselfsheknowitwouldbesomuchlesssotoherfatherthatshewouldnothavehimreallysuspectsuchacircumstanceashernotbethinkperfectbyeverybody',
 'emmaknowineverflatterhersaymrknightleybutimeannoreflectiononanybody',
 'misstaylorhavebeusetohavetwopersontopleaseshewillnowhavebutone',
 'thechancebethatshemustbeagainer',
 'wellsayemmawillingtoletitpassyouwanttohearabouttheweddingandishallbehappytotellyouforweallbehavecharmingly',
 'everybodybepunctualeverybodyintheirbestlooknotatearandhardlyalongfacetobesee',
 'ohnoweallfeltthatwebegotobeonlyhalfamileapartandbesureofmeetingeveryday',
 'dearemmabeareverythingsowellsayherfather',
 'butmrknightleyshebereallyverysorrytolosepoormisstaylorandibesureshewillmisshermorethanshethinkfor',
 'emmaturnawayherheaddividebetweentearandsmile',
 'itbeimpossiblethatemmashouldnotmisssuchacompanionsaymrknightley',
 'weshouldnotlikehersowellaswedosirifwecouldsupposeitbutsheknowhowmuchthemarriagebetomisstaylorsadvantagesheknowhowveryacceptableitmustbeatmisstaylorstimeoflifetobesettleinahomeofherownandhowimportanttohertobesecureofacomfortableprovisionandthereforecannotallowherselftofeelsomuchpainaspleasure',
 'everyfriendofmisstaylormustbegladtohavehersohappilymarry',
 'andyouhaveforgetonematterofjoytomesayemmaandaveryconsiderableonethatimakethematchmyself',
 'imakethematchyouknowfouryearagoandtohaveittakeplaceandbeproveintherightwhensomanypeoplesaymrwestonwouldnevermarryagainmaycomfortmeforanything',
 'mrknightleyshakehisheadather',
 'herfatherfondlyreplyah',
 'mydeariwishyouwouldnotmakematchandforetellthingforwhateveryousayalwayscometopass',
 'praydonotmakeanymorematch',
 'ipromiseyoutomakenoneformyselfpapabutimustindeedforotherpeople',
 'itbethegreatestamusementintheworld',
 'andaftersuchsuccessyouknoweverybodysaythatmrwestonwouldnevermarryagain',
 'ohdearno',
 'mrwestonwhohavebeawidowersolongandwhoseemsoperfectlycomfortablewithoutawifesoconstantlyoccupyeitherinhisbusinessintownoramonghisfriendherealwaysacceptablewhereverhegoalwayscheerfulmrwestonneednotspendasingleeveningintheyearaloneifhedonotlikeit',
 'ohno',
 'mrwestoncertainlywouldnevermarryagain',
 'somepeopleeventalkofapromisetohiswifeonherdeathbedandothersofthesonandtheunclenotlethim',
 'allmannerofsolemnnonsensebetalkonthesubjectbutibelievenoneofit',
 'eversincethedayaboutfouryearagothatmisstaylorandimeetwithhiminbroadwaylanewhenbecauseitbegintodrizzlehedartawaywithsomuchgallantryandborrowtwoumbrellaforusfromfarmermitchellsimakeupmymindonthesubject',
 'iplanthematchfromthathourandwhensuchsuccesshaveblessmeinthisinstancedearpapayoucannotthinkthatishallleaveoffmatchmaking',
 'idonotunderstandwhatyoumeanbysuccesssaymrknightley',
 'successsupposeendeavour',
 'yourtimehavebeproperlyanddelicatelyspendifyouhavebeendeavourforthelastfouryeartobringaboutthismarriage',
 'aworthyemploymentforayoungladysmind',
 'butifwhichiratherimagineyourmakethematchasyoucallitmeanonlyyourplanningityoursaytoyourselfoneidledayithinkitwouldbeaverygoodthingformisstaylorifmrwestonbetomarryherandsayitagaintoyourselfeverynowandthenafterwardswhydoyoutalkofsuccess',
 'wherebeyourmerit',
 'whatbeyouproudof',
 'youmakealuckyguessandthatbeallthatcanbesay',
 'andhaveyouneverknowthepleasureandtriumphofaluckyguessipityyouithinkyouclevererfordependuponitaluckyguessbenevermerelyluck',
 'therebealwayssometalentinit',
 'andastomypoorwordsuccesswhichyouquarrelwithidonotknowthatibesoentirelywithoutanyclaimtoit',
 'youhavedrawtwoprettypicturebutithinktheremaybeathirdasomethingbetweenthedonothingandthedoall',
 'ifihavenotpromotemrwestonsvisithereandgivemanylittleencouragementandsmoothmanylittlematteritmightnothavecometoanythingafterall',
 'ithinkyoumustknowhartfieldenoughtocomprehendthat',
 'astraightforwardopenheartedmanlikewestonandarationalunaffectedwomanlikemisstaylormaybesafelyleavetomanagetheirownconcern',
 'youbemorelikelytohavedoharmtoyourselfthangoodtothembyinterference',
 'emmaneverthinkofherselfifshecandogoodtoothersrejoinmrwoodhouseunderstandbutinpart',
 'butmydearpraydonotmakeanymorematchtheybesillythingandbreakuponesfamilycirclegrievously',
 'onlyonemorepapaonlyformrelton',
 'poormrelton',
 'youlikemreltonpapaimustlookaboutforawifeforhim',
 'therebenobodyinhighburywhodeservehimandhehavebehereawholeyearandhavefituphishousesocomfortablythatitwouldbeashametohavehimsingleanylongerandithinkwhenhebejointheirhandtodayhelooksoverymuchasifhewouldliketohavethesamekindofficedoforhim',
 'ithinkverywellofmreltonandthisbetheonlywayihaveofdohimaservice',
 'mreltonbeaveryprettyyoungmantobesureandaverygoodyoungmanandihaveagreatregardforhim',
 'butifyouwanttoshewhimanyattentionmydearaskhimtocomeanddinewithussomeday',
 'thatwillbeamuchbetterthing',
 'idaresaymrknightleywillbesokindastomeethim',
 'withagreatdealofpleasuresiratanytimesaymrknightleylaughingandiagreewithyouentirelythatitwillbeamuchbetterthing',
 'invitehimtodinneremmaandhelphimtothebestofthefishandthechickenbutleavehimtochusehisownwife',
 'dependuponitamanofsixorsevenandtwentycantakecareofhimself',
 'chapteriimrwestonbeanativeofhighburyandbornofarespectablefamilywhichforthelasttwoorthreegenerationhaveberiseintogentilityandproperty',
 'hehavereceiveagoodeducationbutonsucceedearlyinlifetoasmallindependencehavebecomeindisposedforanyofthemorehomelypursuitinwhichhisbrotherbeengageandhavesatisfyanactivecheerfulmindandsocialtemperbyenterintothemilitiaofhiscountythenembody',
 'captainwestonbeageneralfavouriteandwhenthechanceofhismilitarylifehaveintroducehimtomisschurchillofagreatyorkshirefamilyandmisschurchillfellinlovewithhimnobodybesurprizedexceptherbrotherandhiswifewhohaveneverseehimandwhobefullofprideandimportancewhichtheconnexionwouldoffend',
 'misschurchillhoweverbeofageandwiththefullcommandofherfortunethoughherfortuneborenoproportiontothefamilyestatebenottobedissuadefromthemarriageandittakeplacetotheinfinitemortificationofmrandmrschurchillwhothrowheroffwithduedecorum',
 'itbeanunsuitableconnexionanddonotproducemuchhappiness',
 'mrswestonoughttohavefindmoreinitforshehaveahusbandwhosewarmheartandsweettempermakehimthinkeverythingduetoherinreturnforthegreatgoodnessofbeinlovewithhimbutthoughshehaveonesortofspiritshehavenotthebest',
 'shehaveresolutionenoughtopursueherownwillinspiteofherbrotherbutnotenoughtorefrainfromunreasonableregretatthatbrothersunreasonableangernorfrommisstheluxuryofherformerhome',
 'theylivebeyondtheirincomebutstillitbenothingincomparisonofenscombeshedonotceasetoloveherhusbandbutshewantatoncetobethewifeofcaptainwestonandmisschurchillofenscombe',
 'captainwestonwhohavebeconsiderespeciallybythechurchillasmakesuchanamazingmatchbeprovetohavemuchtheworstofthebargainforwhenhiswifedieafterathreeyearmarriageheberatherapoorermanthanatfirstandwithachildtomaintain',
 'fromtheexpenseofthechildhoweverhebesoonrelieve',
 'theboyhavewiththeadditionalsofteningclaimofalingerillnessofhismothersbethemeanofasortofreconciliationandmrandmrschurchillhavenochildoftheirownnoranyotheryoungcreatureofequalkindredtocareforoffertotakethewholechargeofthelittlefranksoonafterherdecease',
 'somescrupleandsomereluctancethewidowerfathermaybesupposetohavefeltbutastheybeovercomebyotherconsiderationthechildbegiveuptothecareandthewealthofthechurchillandhehaveonlyhisowncomforttoseekandhisownsituationtoimproveashecould',
 'acompletechangeoflifebecomedesirable',
 'hequitthemilitiaandengageintradehavebrotheralreadyestablishinagoodwayinlondonwhichaffordhimafavourableopening',
 'itbeaconcernwhichbringjustemploymentenough',
 'hehavestillasmallhouseinhighburywheremostofhisleisuredaybespendandbetweenusefuloccupationandthepleasureofsocietythenexteighteenortwentyyearofhislifepasscheerfullyaway',
 'hehavebythattimerealiseaneasycompetenceenoughtosecurethepurchaseofalittleestateadjoinhighburywhichhehavealwayslongforenoughtomarryawomanasportionlessevenasmisstaylorandtoliveaccordtothewishofhisownfriendlyandsocialdisposition',
 'itbenowsometimesincemisstaylorhavebegintoinfluencehisschemebutasitbenotthetyrannicinfluenceofyouthonyouthithavenotshakehisdeterminationofneversettletillhecouldpurchaserandallsandthesaleofrandallsbelonglookedforwardtobuthehavegosteadilyonwiththeseobjectinviewtilltheybeaccomplish',
 'hehavemakehisfortunebuyhishouseandobtainhiswifeandbebeginanewperiodofexistencewitheveryprobabilityofgreaterhappinessthaninanyyetpassthrough',
 'hehaveneverbeanunhappymanhisowntemperhavesecurehimfromthateveninhisfirstmarriagebuthissecondmustshewhimhowdelightfulawelljudgingandtrulyamiablewomancouldbeandmustgivehimthepleasantestproofofitsbeagreatdealbettertochoosethantobechoosetoexcitegratitudethantofeelit',
 'hehaveonlyhimselftopleaseinhischoicehisfortunebehisownforastofrankitbemorethanbetacitlybringupashisunclesheirithavebecomesoavowedanadoptionastohavehimassumethenameofchurchilloncomeofage',
 'itbemostunlikelythereforethatheshouldeverwanthisfathersassistance',
 'hisfatherhavenoapprehensionofit',
 'theauntbeacapriciouswomanandgovernherhusbandentirelybutitbenotinmrwestonsnaturetoimaginethatanycapricecouldbestrongenoughtoaffectonesodearandashebelievesodeservedlydear',
 'hesawhissoneveryyearinlondonandbeproudofhimandhisfondreportofhimasaveryfineyoungmanhavemakehighburyfeelasortofprideinhimtoo',
 'hebelookonassufficientlybelongtotheplacetomakehismeritandprospectakindofcommonconcern',
 'mrfrankchurchillbeoneoftheboastofhighburyandalivelycuriositytoseehimprevailthoughthecomplimentbesolittlereturnthathehaveneverbethereinhislife',
 'hiscometovisithisfatherhavebeoftentalkofbutneverachieve',
 'nowuponhisfathersmarriageitbeverygenerallyproposeasamostproperattentionthatthevisitshouldtakeplace',
 'therebenotadissentientvoiceonthesubjecteitherwhenmrsperrydrinkteawithmrsandmissbatesorwhenmrsandmissbatesreturnthevisit',
 'nowbethetimeformrfrankchurchilltocomeamongthemandthehopestrengthenwhenitbeunderstoodthathehavewritetohisnewmotherontheoccasion',
 'forafewdayeverymorningvisitinhighburyincludesomementionofthehandsomelettermrswestonhavereceive',
 'isupposeyouhavehearofthehandsomelettermrfrankchurchillhavewritetomrsweston',
 'iunderstanditbeaveryhandsomeletterindeed',
 'mrwoodhousetellmeofit',
 'mrwoodhousesawtheletterandhesayheneversawsuchahandsomeletterinhislife',
 'itbeindeedahighlyprizedletter',
 'mrswestonhaveofcourseformaveryfavourableideaoftheyoungmanandsuchapleaseattentionbeanirresistibleproofofhisgreatgoodsenseandamostwelcomeadditiontoeverysourceandeveryexpressionofcongratulationwhichhermarriagehavealreadysecure',
 'shefeltherselfamostfortunatewomanandshehavelivelongenoughtoknowhowfortunateshemightwellbethinkwheretheonlyregretbeforapartialseparationfromfriendwhosefriendshipforherhavenevercoolandwhocouldillbeartopartwithher',

In [222]:
## feature extraction ##
# Vector Space Model (or Term Vector Model):
# transforming and representing text documents as numeric vectors of specific terms that form the vector dimensions

# training dataset
corpus = ['the clouds are dark brown today', 'clouds are brown and heavy rainfall is expected',
'heavy rainfall is due to brown clouds', 'i like heavy rains']

# test dataset
unseen_doc = ['like the brown clouds yesterday']

In [225]:
## bag of words model
# simplest vectorization model

# define a function to create a bag of words feature extraction or vectorization model

from sklearn.feature_extraction. text import CountVectorizer

def bow_extractor(corpus, ngram_range=(1,1)):

    # using an instance of CountVectorizer class to define the type of features to be extracted
    # first argument: terms having a minimum frequency of 1 (default)
    # second argument: default unigrams only: 1 means uni, 2 means bi, 3 means tri and
    #                  range of (1,3) would mean uni to tri (uni, bi, tri)
    vectorizer = CountVectorizer(min_df=1, ngram_range=ngram_range)
    
    # using fit_transform method to extarct the features from corpus (term-document matrix)
    features = vectorizer.fit_transform(corpus)
    
    return vectorizer, features
    
    #

In [226]:
# using bow_extractor function to build vectorizer and get features
vectorizer_c, features_c = bow_extractor(corpus)

In [227]:
features_c

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 24 stored elements and shape (4, 15)>

In [228]:
# obtain feature vectors in a matrix form
features_cm = features_c.todense()

In [229]:
features_cm

matrix([[0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
        [1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0]])

In [230]:
# using transform method to extract features from unseen document
features_u = vectorizer_c.transform(unseen_doc)

In [231]:
features_um = features_u.todense()

In [233]:
features_um

matrix([[0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]])

In [236]:
# feature names
# using get_feature_names method
#feature_names = vectorizer_c.get_feature_names()
#not worked for me bcz that code for older version
feature_names = vectorizer_c.get_feature_names_out()

In [237]:
feature_names

array(['and', 'are', 'brown', 'clouds', 'dark', 'due', 'expected',
       'heavy', 'is', 'like', 'rainfall', 'rains', 'the', 'to', 'today'],
      dtype=object)

In [238]:
#combine feature vectors into a dataframe

import pandas as pd

df = pd.DataFrame(data=features_cm, columns=feature_names)
df

,and,are,brown,clouds,dark,due,expected,heavy,is,like,rainfall,rains,the,to,today
0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,1
1,1,1,1,1,0,0,1,1,1,0,1,0,0,0,0
2,0,0,1,1,0,1,0,1,1,0,1,0,0,1,0
3,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0

In [239]:
df1 = pd.DataFrame(data=features_um, columns=feature_names)
df1

,and,are,brown,clouds,dark,due,expected,heavy,is,like,rainfall,rains,the,to,today
0,0,0,1,1,0,0,0,0,0,1,0,0,1,0,0

In [245]:
## TF-IDF model
# solves the potential problem of bow model:
# words with higher frequencies across documents might dominate
# more relevant words (w.r.t classes to be predicted) with Lower frequencies

# define a function to create a tf-idf feature extraction or vectorization model based on bow features

from sklearn.feature_extraction.text import TfidfTransformer

def tfidf_transformer(bow_features):

    # using an instance of TfidfTransformer class to define the type of features to be extracted
    # first argument: Euclidean normalization (default: 'L2')
    # second argument: adding one to document frequencies to prevent zero divisions
    transformer = TfidfTransformer(norm='l2', smooth_idf=True, use_idf=True)
    
    # using fit_transform method to extract the features from bow features (term-document matrix)
    features = transformer.fit_transform(bow_features)
    
    return transformer, features

In [246]:
# using tfidf_transformer function to build transformer and get features from bow features
transformer_c, features_ct = tfidf_transformer(features_c)

# obtain feature vectors in a matrix form
import numpy as np
features_ctm = np.round(features_ct.todense(), 2)

# combine feature vectors into a dataframe
df2 = pd.DataFrame(data=features_ctm, columns=feature_names)
df2

,and,are,brown,clouds,dark,due,expected,heavy,is,like,rainfall,rains,the,to,today
0,0.00,0.37,0.30,0.30,0.47,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.47,0.00,0.47
1,0.44,0.35,0.28,0.28,0.00,0.00,0.44,0.28,0.35,0.00,0.35,0.00,0.00,0.00,0.00
2,0.00,0.00,0.30,0.30,0.00,0.47,0.00,0.30,0.37,0.00,0.37,0.00,0.00,0.47,0.00
3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.41,0.00,0.64,0.00,0.64,0.00,0.00,0.00

In [247]:
# using transform method to extract features from unseen document's bow features

features_ut = transformer_c. transform(features_u)

features_utm = np.round(features_ut. todense(), 2)

df3 = pd.DataFrame(data=features_utm, columns=feature_names)
df3

,and,are,brown,clouds,dark,due,expected,heavy,is,like,rainfall,rains,the,to,today
0,0.0,0.0,0.38,0.38,0.0,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.6,0.0,0.0

In [248]:
# define a function to create a tf-idf feature extraction or vectorization model based on raw docs

from sklearn. feature_extraction. text import TfidfVectorizer

def tfidf_extractor(corpus, ngram_range=(1,1)):

    # using an instance of TfidfVectorizer class to define the type of features to be extracted
    vectorizer = TfidfVectorizer(min_df=1, norm='l2', smooth_idf=True, use_idf=True, ngram_range=ngram_range)
    
    # using fit_transform method to extarct the features from corpus (term-document matrix)
    features = vectorizer.fit_transform(corpus)
    
    return vectorizer, features

In [249]:
# using tfidf_extractor function to build vectorizer and get features
vectorizer_ct, features_ct2 = tfidf_extractor(corpus)

In [250]:
features_ct2m = np.round(features_ct2.todense(), 2)

df4 = pd.DataFrame(data=features_ct2m, columns=feature_names)
df4

,and,are,brown,clouds,dark,due,expected,heavy,is,like,rainfall,rains,the,to,today
0,0.00,0.37,0.30,0.30,0.47,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.47,0.00,0.47
1,0.44,0.35,0.28,0.28,0.00,0.00,0.44,0.28,0.35,0.00,0.35,0.00,0.00,0.00,0.00
2,0.00,0.00,0.30,0.30,0.00,0.47,0.00,0.30,0.37,0.00,0.37,0.00,0.00,0.47,0.00
3,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.41,0.00,0.64,0.00,0.64,0.00,0.00,0.00

In [251]:
# using transform method to extract features from unseen document

features_ut2 = vectorizer_ct.transform(unseen_doc)

features_ut2m = np.round(features_ut2.todense(), 2)

df5 = pd.DataFrame(data=features_ut2m, columns=feature_names)
df5

,and,are,brown,clouds,dark,due,expected,heavy,is,like,rainfall,rains,the,to,today
0,0.0,0.0,0.38,0.38,0.0,0.0,0.0,0.0,0.0,0.6,0.0,0.0,0.6,0.0,0.0

In [252]:
## text classification problem ##

# 20 newsgroups dataset: around 18,000 newsgroups posts spread across 20 different categories or topics

# 20-class classification problem

# Load the dataset using scikit-Learn
from sklearn.datasets import fetch_20newsgroups

# define a function to obtain data
def get_data():

    # remove the headers, footers, and quotes from the text
    data = fetch_20newsgroups(subset='all', shuffle=True, remove=('headers', 'footers', 'quotes'))
    
    return data

In [253]:
# obtain the data
dataset = get_data()

In [255]:
type(dataset)

sklearn.utils._bunch.Bunch

In [256]:
# print all the classes
dataset.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [257]:
# obtain corpus of documents and their corresponding labels
corpus, labels = dataset.data, dataset.target

In [260]:
# define a function to remove empty text documents

def remove_empty_docs(corpus, labels):
    
    corpus_f = []
    labels_f = []
    
    for doc, lbl in zip(corpus, labels):
        if doc.strip():
            corpus_f.append(doc)
            labels_f.append(lbl)
    
    return corpus_f, labels_f

In [261]:
# remove empty documents
corpus, labels = remove_empty_docs(corpus, labels)

In [262]:
corpus

["\n\nI am sure some bashers of Pens fans are pretty confused about the lack\nof any kind of posts about the recent Pens massacre of the Devils. Actually,\nI am  bit puzzled too and a bit relieved. However, I am going to put an end\nto non-PIttsburghers' relief with a bit of praise for the Pens. Man, they\nare killing those Devils worse than I thought. Jagr just showed you why\nhe is much better than his regular season stats. He is also a lot\nfo fun to watch in the playoffs. Bowman should let JAgr have a lot of\nfun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final\nregular season game.          PENS RULE!!!\n\n",
 'My brother is in the market for a high-performance video card that supports\nVESA local bus with 1-2MB RAM.  Does anyone have suggestions/ideas on:\n\n  - Diamond Stealth Pro Local Bus\n\n  - Orchid Farenheit 1280\n\n  - ATI Graphics Ultra Pro\n\n  - Any other high-performance VLB card\n\n\nPlease post or email.  Thank you!\n\n  - Matt\n',
 '\n\n\n\n\tFinally you said what you dream about. Mediterranean???? That was new....\n\tThe area will be "greater" after some years, like your "holocaust" numbers......\n\n\n\n\n\t\t*****\n\tIs\'t July in USA now????? Here in Sweden it\'s April and still cold.\n\tOr have you changed your calendar???\n\n\n\t\t\t\t\t\t    ****************\n\t\t\t\t\t\t    ******************\n\t\t\t    ***************\n\n\n\tNOTHING OF THE MENTIONED IS TRUE, BUT LET SAY IT\'s TRUE.\n\t\n\tSHALL THE AZERI WOMEN AND CHILDREN GOING TO PAY THE PRICE WITH\n\t\t\t\t\t\t    **************\n\tBEING RAPED, KILLED AND TORTURED BY THE ARMENIANS??????????\n\t\n\tHAVE YOU HEARDED SOMETHING CALLED: "GENEVA CONVENTION"???????\n\tYOU FACIST!!!!!\n\n\n\n\tOhhh i forgot, this is how Armenians fight, nobody has forgot\n\tyou killings, rapings and torture against the Kurds and Turks once\n\tupon a time!\n      \n       \n\n\nOhhhh so swedish RedCross workers do lie they too? What ever you say\n"regional killer", if you don\'t like the person then shoot him that\'s your policy.....l\n\n\n\t\t\t\t\t\t\t\t\t\ti\n\t\t\t\t\t\t\t\t\t\ti\n\t\t\t\t\t\t\t\t\t\ti\n\tConfused?????\t\t\t\t\t\t\t\ti\n\t\t\t\t\t\t\t\t\t\ti\n        Search Turkish planes? You don\'t know what you are talking about.\ti\n        Turkey\'s government has announced that it\'s giving weapons  <-----------i\n        to Azerbadjan since Armenia started to attack Azerbadjan\t\t\n        it self, not the Karabag province. So why search a plane for weapons\t\n        since it\'s content is announced to be weapons?   \n\n\tIf there is one that\'s confused then that\'s you! We have the right (and we do)\n\tto give weapons to the Azeris, since Armenians started the fight in Azerbadjan!\n \n\n\n\tShoot down with what? Armenian bread and butter? Or the arms and personel \n\tof the Russian army?\n\n\n',
 "\nThink!\n\nIt's the SCSI card doing the DMA transfers NOT the disks...\n\nThe SCSI card can do DMA transfers containing data from any of the SCSI devices\nit is attached when it wants to.\n\nAn important feature of SCSI is the ability to detach a device. This frees the\nSCSI bus for other devices. This is typically used in a multi-tasking OS to\nstart transfers on several devices. While each device is seeking the data the\nbus is free for other commands and data transfers. When the devices are\nready to transfer the data they can aquire the bus and send the data.\n\nOn an IDE bus when you start a transfer the bus is busy until the disk has seeked\nthe data and transfered it. This is typically a 10-20ms second lock out for other\nprocesses wanting the bus irrespective of transfer time.\n",
 '1)    I have an old Jasmine drive which I cannot use with my new system.\n My understanding is that I have to upsate the driver with a more modern\none in order to gain compatability with system 7.0.1.  does anyone know\nof an inexpensive program to do this?  ( I have seen formatters for <$20\nbuit have no idea if they will work)\n \n2)     I have another ancient device, this one a tape drive for which\nthe back utility freezes the system if I try to use it.  THe drive is a\njasmine direct tape (bought used for $150 w/ 6 tapes, techmar\nmechanism).  Essentially I have the same question as above, anyone know\nof an inexpensive beckup utility I can use with system 7.0.1',
 '\n\nBack in high school I worked as a lab assistant for a bunch of experimental\npsychologists at Bell Labs.  When they were doing visual perception and\nmemory experiments, they used vector-type displays, with 1-millisecond\nrefresh rates common.\n\nSo your case of 1/200th sec is quite practical, and the experimenters were\nprobably sure that it was 5 milliseconds, not 4 or 6 either.\n\n\nSteve',
 '\n\nAE is in Dallas...try 214/241-6060 or 214/241-0055.  Tech support may be on\ntheir own line, but one of these should get you started.',
 "\n[stuff deleted]\n\nOk, here's the solution to your problem.  Move to Canada.  Yesterday I was able\nto watch FOUR games...the NJ-PITT at 1:00 on ABC, LA-CAL at 3:00 (CBC), \nBUFF-BOS at 7:00 (TSN and FOX), and MON-QUE at 7:30 (CBC).  I think that if\neach series goes its max I could be watching hockey playoffs for 40-some odd\nconsecutive nights (I haven't counted so that's a pure guess).\n\nI have two tv's in my house, and I set them up side-by-side to watch MON-QUE\nand keep an eye on BOS-BUFF at the same time.  I did the same for the two\nafternoon games.\n\nBtw, those ABC commentaters were great!  I was quite impressed; they seemed\nto know that their audience wasn't likely to be well-schooled in hockey lore\nand they did an excellent job.  They were quite impartial also, IMO.\n\n",
 "\n\n\nYeah, it's the second one.  And I believe that price too.  I've been trying\nto get a good look at it on the Bruin-Sabre telecasts, and wow! does it ever\nlook good.  Whoever did that paint job knew what they were doing.  And given\nFuhr's play since he got it, I bet the Bruins are wishing he didn't have it:)\n",
 '\nIf a Christian means someone who believes in the divinity of Jesus, it is safe\nto say that Jesus was a Christian.\n--\n"On the first day after Christmas my truelove served to me...  Leftover Turkey!\nOn the second day after Christmas my truelove served to me...  Turkey Casserole\n    that she made from Leftover Turkey.\n[days 3-4 deleted] ...  Flaming Turkey Wings! ...\n   -- Pizza Hut commercial (and M*tlu/A*gic bait)',
 'the blood of the lamb.\n\nThis will be a hard task, because most cultures used most animals\nfor blood sacrifices. It has to be something related to our current\npost-modernism state. Hmm, what about used computers?\n\nCheers,\nKent',
 ' >say they have a "history of untrustworthy behavoir[sic]"? ',
 '930418\n\nDo what thou wilt shall be the whole of the Law. [Honestly.]\nThe word of Sin is Restriction. [Would I kid you?]\n\n\nDoes one man\'s words encompass the majestic vision of thousands\nof individuals?  Quoting a man is not the same as quoting the\nOrder.  Taken out of context, words can be interpreted much\ndifferently than had one applied them within the confines of\ntheir original expression.\n\nI think this is the case regarding Hymenaeus Beta, Frater Superior \nof the Order to which I belong.  When he included that bit\nfrom Merlinus X\' he did us all a service.  He showed us the extremes\nto which Order members have been known to go in their fervor.\nI have little knowledge regarding Reuss\' background, but surely\nhe was an unusual man, and he was an important force in the Order \nfor many years.\n\nYet as people change so do Orders change, and while we look back\nso carefully at the dirty laundry of O.T.O. remember that this is\nonly the surface skim and that many perspectives are now encompassed\nwhich extend beyond any one individual.  I hope to show that there\nwas and is much room for a difference of opinion within the Order\nitself, perhaps by testing the limits myself.\n\n\nLet us examine this issue a bit more closely....\n\n"In 1895, Karl Kellner (1850-1905), a wealthy Austrian industrialist\nand paper chemist, as well as a high-grade Mason, founded the Ordo\nTempli Orientis.  Kellner had traveled widely in the East, where he\nmet three adepts who instructed him specific magical practices.  \nKellner\'s efforts to develop the Order were later assisted by Franz\nHartmann, Heinrich Klein and Theodore Reuss, who had worked together\nprior to joining the O.T.O.  The Order was first proclaimed in 1902\nin Reuss\'s Masonic publication, \'Oriflamme\'.  On Kellner\'s death,\nReuss succeeded him as Outer Head [O.H.O.].  The \'Jubilee\' edition of\nthe \'Oriflamme\', published in 1912, announced that the Order taught\nsecret of sexual magic.\n \n"Theodore Reuss was an interesting character.  Born June 28, 1855 in\nAugsburg, he entered Masonry in 1876.  He was a singer, journalist and\npossibly a spy for the Prussian political police, infiltrating the Socialist\nLeague founded by Karl Marx\'s daughter and her husband.  Reuss was\nlater associated with William Wynn Westcott, a leader of the Golden\nDawn, who later introduced him to John Yarker.  Yarker chartered Reuss to\nfound the Rites of Memphis and Mizraim in Germany.  After several\nattempts to concretize various Masonic Rites, Reuss settled on the\ndevelopment of the O.T.O.\n\n"The Order experienced reasonably steady growth under Reuss\' leadership.\nFor example, he chartered Papus in France, Rudolph Steiner in Berlin\nand H. Spencer Lewis in the USA.  In 1912, the historic meeting between\nReuss and Crowley occurred.  Crowley wrote that Reuss came to him and\naccused him of revealing Order secrets.  When Crowley looked at it afresh,\nthe initiated interpretation of sexual magick unfolded itself to him for\nthe first time.  Reuss appointed Crowley as Supreme and Holy King of all\nthe English speaking world, and it was this authorization that he invoked\nwhen publishing the material of the Equinox.\n\n"Reuss resigned as Outer Head of the Order in 1922 after suffering a\nstroke and named Crowley his successor.  All was well until 1925 when\n_The Book of the Law_ was translated into German.  There was a break\nin the continuity of the Order.  Manyk members split with the new O.H.O.\nover the book, which Crowley was actively promulgating through the Order.\nHe had earlier revise dthe Order rituals at Reuss\'s request, deeply\ninfusing the doctrines of the New Aeon revelation."\n\n_An Introduction to the History of the O.T.O._, by Ad Veritatem IX\'\n\nWithin _Equinox III:10_, Edited by \n  Hymenaeus Beta, Frater Superior, Rex Summus Sanctissimus,\n    Caliph of the United States of America,\n      Published by Samuel Weiser, 1990.\n\n\n\nThere are many possible reasons that our Frater Superior included this\nmaterial in _Equinox III:10_.  And this is the real point, is it not?\nWhy did he wish to publish such things about the history of his own\norganization?  Does he represent a dogmatic threat to the principle\nof Thelema?  Or is he exercising his True Will and putting forth very\ncomplex pictures with no easy answers?  A picture which leaves room\nfor very many interpretations.\n\nIt is quite easy for me to see, for example, that all of O.T.O. derived\nout of the dribble of faltering Masonry, purchased by clever hucksters\nwith an ounce of courage and some writing ability to aid them.  And I\ncan take that all the way down to our present Caliph, whose feeble\nsupport of the \'Law of Thelema\' is laughable at best.\n\nWould I be thrown out of the Order for speaking in this way?  \nWill I?  \nI think not.\nWhy?  Because my Frater will see it as a perspective, an interjection\nI am using as an example.  My illustration shows that we may express things\nin the context of a larger work and the true significance of this may be\nquite difficult to apprehend at first.\n\nSo it may be with OTO and Merlinus X\'.  Please look O.T.O. more carefully.\nI do not support Reuss\'s words myself, as I am not qualified to assess\nthem, and I am critical of their pomposity.  If I who am a member of\nthe Order take such a stand and am allowed to continue doing so, then\nwhat can this say about the health of the Order?  Does it mean that\nthe Order has \'gone soft\' and abandoned its moral principles?  Or\ndoes it mean that it is strong in its ability to let the will of\nuniversal kinship arise on its own, not shackled by some dogmatic\nrequirement?  How shall we resolve these two possibilities?\n\n\nI find a high calibre of individual associated with Ordo Templi Orientis.\nThey are often quite intelligent and sometimes very well versed in arcane\nor usual information.  They are quite often artists and geniuses.  \nHaving met some 20 longstanding members in the SF Bay Area (many who are or\nwere very heavily involved with the Order), I can vouch for the integrity\nof the organization as it stands.\n\nI have sometimes questioned the policy of Hymenaeus Beta.  In these moments \nI followed my intuition, and I\'ve found little to stop me from requesting\na Second initiation from a different O.T.O. body.  I\'m happily participating\nin social groups (Feasts or Initiations) and have come to know the Gnostic\nMass well enough for my tastes.\n \n\nThis doesn\'t make me an authority on Order politics and explanations, however.\nI can only hypothesize and relay to you what I understand based on my\nlimited contact with other members.\n\nI urge you not to take the words of Merlinus X too far.  There are many\nways to interpret words, and many people who have become involved with\nthe Order feel very strongly about the sanctity of personal freedom\nand the preservation of individual vision.\n\nI welcome other comment on this issue and will be writing more in response\nto other posts in this thread.\n\n\nInvoke me under my stars.  Love is the law, love under will.\n\nI am I!',
 ' How about Kirlian imaging ? I believe the FAQ for sci.skeptics (sp?)\n has a nice write-up on this. They would certainly be most supportive\n on helping you to build such a device and connect to a 120Kvolt\n supply so that you can take a serious look at your "aura"... :-)',
 '\n\n\tThere is no notion of heliocentric, or even galacticentric either.\n\n\n\n--------------------------------------------------------------------------------',
 'In the following report: _Turkey Eyes Regional Role_ ANKARA, Turkey (AP)\nApril 27, 1993, we find in the last paragraph:\n\n[Turanist] Although Premier Suleyman Demirel criticized Ozal\'s often\n[Turanist] brash calls for more Turkish influence, he also has spoken\n[Turanist] of a swath of Turkic peoples "stretching from the Adriatic\n[Turanist] Sea to the Great Wall of China."\n\nWho does Demirel think he is fooling? It seems at both ends of his envisioned \npan-Turkic Empire -- the Balkans and the Caucasus -- Turkey\'s fascist boasts\nare being pre-empted.\n\nI would suggest Turkey let the world feel some of their "Grey Wolf Teeth", and\nattempt to stretch from the Adriatic to China! Turkey will have cried "wolf"\njust once too much! \n\n',
 'Many thanks to those who replied to my appeal for info on a drive I have\nwhich is 3.5" 600RPM!!\n\nI now have some information on how to modify this for use with a BBC B \ncomputer. Not only do you have to change the speed from 600 to 300 rpm\n(tried that) but also change 8 components in the Rec/Play section to allow\nfor the lower data rate (250kbit, not 500kbit as it was designed for) and also\nchange the Recording Current to allow for the low data rate/rev speed!\n\nHopefully this should sort it all out .... not bad for 9 quid (normally 32 \nquid and upwards ....)\n\nThe drive is a JVC MDP series drive ...',
 '.........\nI, some years ago, almost became a victim of this.  Squirted a fair amount in\nan old model 15 Teletype which was acting up, then turned it on.  The eruption\nwhen the motor starting contacts broke was mighty spectacular... I almost got\nmy eyebrows singed, the plastic (old ones had safety glass) cover over the\nplaten, etc flew across the room, and several people in the room almost had\nheart attacks.  Beware the explosive properties of WD40 vapor.\n',

In [263]:
labels

[np.int64(10),
 np.int64(3),
 np.int64(17),
 np.int64(3),
 np.int64(4),
 np.int64(12),
 np.int64(4),
 np.int64(10),
 np.int64(10),
 np.int64(19),
 np.int64(19),
 np.int64(11),
 np.int64(19),
 np.int64(13),
 np.int64(0),
 np.int64(17),
 np.int64(12),
 np.int64(12),
 np.int64(11),
 np.int64(8),
 np.int64(7),
 np.int64(5),
 np.int64(1),
 np.int64(8),
 np.int64(10),
 np.int64(14),
 np.int64(16),
 np.int64(1),
 np.int64(6),
 np.int64(0),
 np.int64(7),
 np.int64(16),
 np.int64(5),
 np.int64(9),
 np.int64(13),
 np.int64(4),
 np.int64(4),
 np.int64(18),
 np.int64(8),
 np.int64(8),
 np.int64(19),
 np.int64(1),
 np.int64(12),
 np.int64(7),
 np.int64(10),
 np.int64(5),
 np.int64(2),
 np.int64(6),
 np.int64(11),
 np.int64(2),
 np.int64(12),
 np.int64(7),
 np.int64(18),
 np.int64(11),
 np.int64(7),
 np.int64(8),
 np.int64(0),
 np.int64(4),
 np.int64(19),
 np.int64(8),
 np.int64(9),
 np.int64(4),
 np.int64(1),
 np.int64(1),
 np.int64(17),
 np.int64(11),
 np.int64(10),
 np.int64(11),
 np.int64(5),
 np.int64(1),
 np.int64(3),
 np.int64(17),
 np.int64(6),
 np.int64(14),
 np.int64(19),
 np.int64(14),
 np.int64(10),
 np.int64(2),
 np.int64(15),
 np.int64(10),
 np.int64(12),
 np.int64(7),
 np.int64(5),
 np.int64(12),
 np.int64(4),
 np.int64(15),
 np.int64(16),
 np.int64(13),
 np.int64(8),
 np.int64(15),
 np.int64(9),
 np.int64(15),
 np.int64(2),
 np.int64(17),
 np.int64(3),
 np.int64(2),
 np.int64(10),
 np.int64(16),
 np.int64(5),
 np.int64(17),
 np.int64(1),
 np.int64(2),
 np.int64(17),
 np.int64(10),
 np.int64(4),
 np.int64(18),
 np.int64(6),
 np.int64(2),
 np.int64(4),
 np.int64(7),
 np.int64(14),
 np.int64(5),
 np.int64(17),
 np.int64(17),
 np.int64(12),
 np.int64(11),
 np.int64(9),
 np.int64(4),
 np.int64(3),
 np.int64(12),
 np.int64(2),
 np.int64(12),
 np.int64(16),
 np.int64(4),
 np.int64(2),
 np.int64(12),
 np.int64(1),
 np.int64(17),
 np.int64(15),
 np.int64(16),
 np.int64(10),
 np.int64(3),
 np.int64(2),
 np.int64(11),
 np.int64(3),
 np.int64(8),
 np.int64(0),
 np.int64(2),
 np.int64(7),
 np.int64(5),
 np.int64(13),
 np.int64(11),
 np.int64(4),
 np.int64(1),
 np.int64(9),
 np.int64(6),
 np.int64(8),
 np.int64(8),
 np.int64(3),
 np.int64(3),
 np.int64(18),
 np.int64(4),
 np.int64(8),
 np.int64(18),
 np.int64(14),
 np.int64(4),
 np.int64(1),
 np.int64(12),
 np.int64(15),
 np.int64(1),
 np.int64(4),
 np.int64(15),
 np.int64(14),
 np.int64(4),
 np.int64(13),
 np.int64(4),
 np.int64(13),
 np.int64(3),
 np.int64(0),
 np.int64(5),
 np.int64(2),
 np.int64(9),
 np.int64(15),
 np.int64(8),
 np.int64(10),
 np.int64(7),
 np.int64(9),
 np.int64(18),
 np.int64(12),
 np.int64(4),
 np.int64(17),
 np.int64(17),
 np.int64(17),
 np.int64(19),
 np.int64(6),
 np.int64(15),
 np.int64(0),
 np.int64(19),
 np.int64(15),
 np.int64(17),
 np.int64(6),
 np.int64(13),
 np.int64(1),
 np.int64(19),
 np.int64(4),
 np.int64(15),
 np.int64(5),
 np.int64(1),
 np.int64(7),
 np.int64(6),
 np.int64(15),
 np.int64(12),
 np.int64(0),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(3),
 np.int64(8),
 np.int64(16),
 np.int64(2),
 np.int64(17),
 np.int64(14),
 np.int64(10),
 np.int64(15),
 np.int64(3),
 np.int64(7),
 np.int64(11),
 np.int64(0),
 np.int64(11),
 np.int64(8),
 np.int64(8),
 np.int64(10),
 np.int64(8),
 np.int64(3),
 np.int64(14),
 np.int64(3),
 np.int64(9),
 np.int64(5),
 np.int64(15),
 np.int64(10),
 np.int64(10),
 np.int64(5),
 np.int64(12),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(15),
 np.int64(0),
 np.int64(3),
 np.int64(12),
 np.int64(1),
 np.int64(3),
 np.int64(16),
 np.int64(5),
 np.int64(12),
 np.int64(16),
 np.int64(4),
 np.int64(1),
 np.int64(3),
 np.int64(12),
 np.int64(14),
 np.int64(13),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(14),
 np.int64(8),
 np.int64(3),
 np.int64(1),
 np.int64(13),
 np.int64(2),
 np.int64(13),
 np.int64(19),
 np.int64(17),
 np.int64(5),
 np.int64(11),
 np.int64(15),
 np.int64(13),
 np.int64(19),
 np.int64(19),
 np.int64(9),
 np.int64(5),
 np.int64(17),
 np.int64(13),
 np.int64(4),
 np.int64(3),
 np.int64(2),
 np.int64(16),
 np.int64(18),
 np.int64(5),
 np.int64(1),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(11),
 np.int64(15),
 np.int64(0),
 np.int64(1),
 np.int64(18),
 np.int64(7),
 np.int64(5),
 np.int64(4),
 np.int64(18),
 np.int64(10),
 np.int64(14),
 np.int64(4),
 np.int64(7),
 np.int64(0),
 np.int64(12),
 np.int64(7),
 np.int64(1),
 np.int64(13),
 np.int64(17),
 np.int64(0),
 np.int64(16),
 np.int64(3),
 np.int64(15),
 np.int64(2),
 np.int64(3),
 np.int64(9),
 np.int64(14),
 np.int64(9),
 np.int64(2),
 np.int64(8),
 np.int64(11),
 np.int64(2),
 np.int64(3),
 np.int64(9),
 np.int64(1),
 np.int64(5),
 np.int64(19),
 np.int64(14),
 np.int64(2),
 np.int64(14),
 np.int64(1),
 np.int64(18),
 np.int64(5),
 np.int64(0),
 np.int64(18),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(0),
 np.int64(13),
 np.int64(3),
 np.int64(16),
 np.int64(13),
 np.int64(6),
 np.int64(17),
 np.int64(15),
 np.int64(10),
 np.int64(5),
 np.int64(13),
 np.int64(2),
 np.int64(1),
 np.int64(7),
 np.int64(0),
 np.int64(10),
 np.int64(18),
 np.int64(10),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(3),
 np.int64(1),
 np.int64(10),
 np.int64(7),
 np.int64(16),
 np.int64(0),
 np.int64(10),
 np.int64(19),
 np.int64(19),
 np.int64(3),
 np.int64(12),
 np.int64(11),
 np.int64(15),
 np.int64(5),
 np.int64(13),
 np.int64(14),
 np.int64(10),
 np.int64(9),
 np.int64(5),
 np.int64(7),
 np.int64(7),
 np.int64(14),
 np.int64(15),
 np.int64(7),
 np.int64(9),
 np.int64(9),
 np.int64(18),
 np.int64(5),
 np.int64(1),
 np.int64(15),
 np.int64(5),
 np.int64(2),
 np.int64(19),
 np.int64(10),
 np.int64(0),
 np.int64(13),
 np.int64(12),
 np.int64(19),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(9),
 np.int64(3),
 np.int64(15),
 np.int64(8),
 np.int64(11),
 np.int64(14),
 np.int64(16),
 np.int64(16),
 np.int64(6),
 np.int64(15),
 np.int64(12),
 np.int64(12),
 np.int64(3),
 np.int64(12),
 np.int64(16),
 np.int64(15),
 np.int64(12),
 np.int64(10),
 np.int64(11),
 np.int64(8),
 np.int64(17),
 np.int64(9),
 np.int64(13),
 np.int64(8),
 np.int64(19),
 np.int64(2),
 np.int64(4),
 np.int64(3),
 np.int64(16),
 np.int64(8),
 np.int64(1),
 np.int64(13),
 np.int64(15),
 np.int64(4),
 np.int64(13),
 np.int64(11),
 np.int64(4),
 np.int64(7),
 np.int64(1),
 np.int64(6),
 np.int64(13),
 np.int64(15),
 np.int64(14),
 np.int64(0),
 np.int64(2),
 np.int64(3),
 np.int64(8),
 np.int64(10),
 np.int64(4),
 np.int64(10),
 np.int64(6),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(6),
 np.int64(4),
 np.int64(2),
 np.int64(15),
 np.int64(4),
 np.int64(6),
 np.int64(18),
 np.int64(1),
 np.int64(5),
 np.int64(9),
 np.int64(19),
 np.int64(4),
 np.int64(0),
 np.int64(1),
 np.int64(19),
 np.int64(0),
 np.int64(3),
 np.int64(11),
 np.int64(4),
 np.int64(2),
 np.int64(4),
 np.int64(9),
 np.int64(0),
 np.int64(12),
 np.int64(19),
 np.int64(7),
 np.int64(7),
 np.int64(2),
 np.int64(6),
 np.int64(11),
 np.int64(14),
 np.int64(7),
 np.int64(18),
 np.int64(9),
 np.int64(3),
 np.int64(15),
 np.int64(2),
 np.int64(1),
 np.int64(1),
 np.int64(8),
 np.int64(14),
 np.int64(3),
 np.int64(6),
 np.int64(11),
 np.int64(7),
 np.int64(1),
 np.int64(14),
 np.int64(19),
 np.int64(9),
 np.int64(10),
 np.int64(5),
 np.int64(12),
 np.int64(12),
 np.int64(4),
 np.int64(8),
 np.int64(12),
 np.int64(17),
 np.int64(14),
 np.int64(1),
 np.int64(16),
 np.int64(9),
 np.int64(0),
 np.int64(9),
 np.int64(13),
 np.int64(9),
 np.int64(14),
 np.int64(13),
 np.int64(7),
 np.int64(16),
 np.int64(2),
 np.int64(5),
 np.int64(13),
 np.int64(4),
 np.int64(8),
 np.int64(8),
 np.int64(9),
 np.int64(3),
 np.int64(15),
 np.int64(16),
 np.int64(1),
 np.int64(8),
 np.int64(15),
 np.int64(16),
 np.int64(5),
 np.int64(17),
 np.int64(8),
 np.int64(9),
 np.int64(5),
 np.int64(10),
 np.int64(8),
 np.int64(15),
 np.int64(8),
 np.int64(7),
 np.int64(17),
 np.int64(0),
 np.int64(10),
 np.int64(3),
 np.int64(12),
 np.int64(8),
 np.int64(11),
 np.int64(5),
 np.int64(8),
 np.int64(18),
 np.int64(6),
 np.int64(5),
 np.int64(18),
 np.int64(8),
 np.int64(11),
 np.int64(9),
 np.int64(15),
 np.int64(17),
 np.int64(8),
 np.int64(13),
 np.int64(12),
 np.int64(8),
 np.int64(0),
 np.int64(19),
 np.int64(2),
 np.int64(17),
 np.int64(14),
 np.int64(10),
 np.int64(7),
 np.int64(18),
 np.int64(16),
 np.int64(17),
 np.int64(10),
 np.int64(12),
 np.int64(16),
 np.int64(1),
 np.int64(10),
 np.int64(11),
 np.int64(1),
 np.int64(14),
 np.int64(16),
 np.int64(1),
 np.int64(2),
 np.int64(17),
 np.int64(12),
 np.int64(11),
 np.int64(6),
 np.int64(4),
 np.int64(14),
 np.int64(6),
 np.int64(15),
 np.int64(6),
 np.int64(15),
 np.int64(12),
 np.int64(11),
 np.int64(19),
 np.int64(12),
 np.int64(6),
 np.int64(16),
 np.int64(1),
 np.int64(6),
 np.int64(9),
 np.int64(5),
 np.int64(13),
 np.int64(17),
 np.int64(14),
 np.int64(5),
 np.int64(10),
 np.int64(9),
 np.int64(16),
 np.int64(14),
 np.int64(0),
 np.int64(6),
 np.int64(0),
 np.int64(0),
 np.int64(18),
 np.int64(19),
 np.int64(16),
 np.int64(6),
 np.int64(18),
 np.int64(18),
 np.int64(3),
 np.int64(14),
 np.int64(13),
 np.int64(13),
 np.int64(2),
 np.int64(19),
 np.int64(10),
 np.int64(8),
 np.int64(2),
 np.int64(19),
 np.int64(5),
 np.int64(18),
 np.int64(15),
 np.int64(5),
 np.int64(14),
 np.int64(5),
 np.int64(5),
 np.int64(12),
 np.int64(6),
 np.int64(7),
 np.int64(6),
 np.int64(19),
 np.int64(18),
 np.int64(9),
 np.int64(19),
 np.int64(18),
 np.int64(4),
 np.int64(10),
 np.int64(3),
 np.int64(0),
 np.int64(5),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(0),
 np.int64(11),
 np.int64(13),
 np.int64(15),
 np.int64(3),
 np.int64(5),
 np.int64(2),
 np.int64(8),
 np.int64(7),
 np.int64(9),
 np.int64(10),
 np.int64(18),
 np.int64(13),
 np.int64(5),
 np.int64(0),
 np.int64(14),
 np.int64(6),
 np.int64(4),
 np.int64(3),
 np.int64(3),
 np.int64(14),
 np.int64(1),
 np.int64(11),
 np.int64(9),
 np.int64(3),
 np.int64(1),
 np.int64(1),
 np.int64(19),
 np.int64(13),
 np.int64(10),
 np.int64(17),
 np.int64(5),
 np.int64(9),
 np.int64(3),
 np.int64(11),
 np.int64(7),
 np.int64(11),
 np.int64(16),
 np.int64(3),
 np.int64(12),
 np.int64(12),
 np.int64(4),
 np.int64(13),
 np.int64(14),
 np.int64(17),
 np.int64(14),
 np.int64(1),
 np.int64(2),
 np.int64(16),
 np.int64(12),
 np.int64(1),
 np.int64(2),
 np.int64(19),
 np.int64(17),
 np.int64(19),
 np.int64(13),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(9),
 np.int64(6),
 np.int64(14),
 np.int64(2),
 np.int64(10),
 np.int64(17),
 np.int64(9),
 np.int64(8),
 np.int64(8),
 np.int64(10),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(12),
 np.int64(5),
 np.int64(4),
 np.int64(0),
 np.int64(3),
 np.int64(5),
 np.int64(13),
 np.int64(13),
 np.int64(10),
 np.int64(18),
 np.int64(13),
 np.int64(10),
 np.int64(1),
 np.int64(16),
 np.int64(19),
 np.int64(15),
 np.int64(2),
 np.int64(18),
 np.int64(18),
 np.int64(2),
 np.int64(12),
 np.int64(7),
 np.int64(11),
 np.int64(10),
 np.int64(10),
 np.int64(3),
 np.int64(12),
 np.int64(15),
 np.int64(0),
 np.int64(13),
 np.int64(5),
 np.int64(6),
 np.int64(14),
 np.int64(7),
 np.int64(14),
 np.int64(11),
 np.int64(3),
 np.int64(4),
 np.int64(9),
 np.int64(15),
 np.int64(9),
 np.int64(3),
 np.int64(6),
 np.int64(8),
 np.int64(18),
 np.int64(2),
 np.int64(12),
 np.int64(11),
 np.int64(7),
 np.int64(3),
 np.int64(15),
 np.int64(8),
 np.int64(4),
 np.int64(8),
 np.int64(2),
 np.int64(11),
 np.int64(3),
 np.int64(1),
 np.int64(14),
 np.int64(19),
 np.int64(10),
 np.int64(3),
 np.int64(12),
 np.int64(11),
 np.int64(5),
 np.int64(12),
 np.int64(7),
 np.int64(10),
 np.int64(0),
 np.int64(5),
 np.int64(3),
 np.int64(1),
 np.int64(10),
 np.int64(15),
 np.int64(1),
 np.int64(9),
 np.int64(0),
 np.int64(15),
 np.int64(1),
 np.int64(12),
 np.int64(2),
 np.int64(15),
 np.int64(11),
 np.int64(1),
 np.int64(7),
 np.int64(14),
 np.int64(18),
 np.int64(3),
 np.int64(4),
 np.int64(13),
 np.int64(3),
 np.int64(0),
 np.int64(14),
 np.int64(6),
 np.int64(11),
 np.int64(18),
 np.int64(4),
 np.int64(16),
 np.int64(15),
 np.int64(14),
 np.int64(5),
 np.int64(10),
 np.int64(15),
 np.int64(17),
 np.int64(16),
 np.int64(10),
 np.int64(5),
 np.int64(12),
 np.int64(4),
 np.int64(7),
 np.int64(6),
 np.int64(6),
 np.int64(13),
 np.int64(19),
 np.int64(15),
 np.int64(16),
 np.int64(18),
 np.int64(4),
 np.int64(4),
 np.int64(4),
 np.int64(3),
 np.int64(13),
 np.int64(4),
 np.int64(10),
 np.int64(5),
 np.int64(13),
 np.int64(0),
 np.int64(1),
 np.int64(3),
 np.int64(19),
 np.int64(15),
 np.int64(0),
 np.int64(0),
 np.int64(7),
 np.int64(14),
 np.int64(13),
 np.int64(12),
 np.int64(14),
 np.int64(2),
 np.int64(19),
 np.int64(5),
 np.int64(11),
 np.int64(14),
 np.int64(9),
 np.int64(11),
 np.int64(9),
 np.int64(15),
 np.int64(8),
 np.int64(12),
 np.int64(14),
 np.int64(17),
 np.int64(14),
 np.int64(17),
 np.int64(13),
 np.int64(16),
 np.int64(2),
 np.int64(15),
 np.int64(1),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(19),
 np.int64(0),
 np.int64(2),
 np.int64(8),
 np.int64(17),
 np.int64(4),
 np.int64(8),
 np.int64(10),
 np.int64(3),
 np.int64(2),
 np.int64(11),
 np.int64(2),
 np.int64(9),
 np.int64(9),
 np.int64(5),
 np.int64(5),
 np.int64(4),
 np.int64(3),
 np.int64(17),
 np.int64(8),
 np.int64(10),
 np.int64(5),
 np.int64(3),
 np.int64(5),
 np.int64(5),
 np.int64(19),
 np.int64(6),
 np.int64(17),
 np.int64(4),
 np.int64(19),
 np.int64(9),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(15),
 np.int64(11),
 np.int64(5),
 np.int64(8),
 np.int64(4),
 np.int64(13),
 np.int64(10),
 np.int64(7),
 np.int64(4),
 np.int64(0),
 np.int64(10),
 np.int64(5),
 np.int64(15),
 np.int64(0),
 np.int64(9),
 np.int64(0),
 np.int64(4),
 np.int64(12),
 np.int64(2),
 np.int64(9),
 np.int64(8),
 np.int64(4),
 np.int64(12),
 np.int64(10),
 np.int64(5),
 np.int64(16),
 np.int64(8),
 np.int64(10),
 np.int64(6),
 np.int64(2),
 np.int64(9),
 np.int64(5),
 np.int64(12),
 np.int64(0),
 np.int64(19),
 np.int64(4),
 np.int64(2),
 np.int64(17),
 np.int64(9),
 np.int64(13),
 np.int64(6),
 np.int64(3),
 np.int64(17),
 np.int64(13),
 np.int64(2),
 np.int64(12),
 np.int64(13),
 np.int64(15),
 np.int64(4),
 np.int64(10),
 np.int64(3),
 np.int64(11),
 np.int64(18),
 np.int64(8),
 np.int64(17),
 np.int64(1),
 np.int64(0),
 np.int64(16),
 np.int64(0),
 np.int64(19),
 np.int64(15),
 np.int64(7),
 np.int64(7),
 np.int64(9),
 np.int64(12),
 np.int64(3),
 np.int64(17),
 np.int64(8),
 np.int64(9),
 np.int64(2),
 np.int64(3),
 np.int64(10),
 np.int64(4),
 ...]

In [264]:
# see a sample document, its Label index and class name
# e.g., document with index value 10
corpus [3]

"\nThink!\n\nIt's the SCSI card doing the DMA transfers NOT the disks...\n\nThe SCSI card can do DMA transfers containing data from any of the SCSI devices\nit is attached when it wants to.\n\nAn important feature of SCSI is the ability to detach a device. This frees the\nSCSI bus for other devices. This is typically used in a multi-tasking OS to\nstart transfers on several devices. While each device is seeking the data the\nbus is free for other commands and data transfers. When the devices are\nready to transfer the data they can aquire the bus and send the data.\n\nOn an IDE bus when you start a transfer the bus is busy until the disk has seeked\nthe data and transfered it. This is typically a 10-20ms second lock out for other\nprocesses wanting the bus irrespective of transfer time.\n"

In [265]:
labels[3]

np.int64(3)

In [266]:
dataset.target_names[labels[3]]

'comp.sys.ibm.pc.hardware'

In [267]:
# define a function to partition the dataset into training and test

from sklearn.model_selection import train_test_split

def prepare_datasets(corpus, labels, test_proportion=0.2):

    train_c, test_c, train_1, test_1 = train_test_split(corpus, labels, test_size=test_proportion, random_state=18)
    
    return train_c, test_c, train_1, test_1

In [268]:
# create training and test partitions
train_c, test_c, train_1, test_1 = prepare_datasets(corpus, labels, test_proportion=0.3)

In [269]:
train_c

['\n\nSorry, I still don\'t buy it.  You\'re certainly right that the runner is\nnot out merely for running out of the baseline: he must interfere with\nthe play.  But the argument here is over what constitutes interference.\nYou certainly cannot infer from what you\'ve quoted that the batter-runner\nmust be hit by the ball to be guilty of interference: you haven\'t posted\na definition of interference at all.\n\nIMO this calls for one of the "approved ruling[s]" that go in small print\nin the rulebook.  Something like:\n\nAPPROVED RULING:\nIf in the judgement of the umpire the runner, by running to the left\nof the allowed path, caused the fielder to make a bad throw, blocks the\nvision of the fielder receiving the throw, or otherwise impedes the\ndefensive team\'s making a play on him, the batter-runner shall be\njudeged guilty of interference.\n\nor\n\nAPPROVED RULING:\nThe runner cannot be judged guilty of interference in the unless he makes\ncontact with a fielder or is hit by the thrown ball.\n\n--\nIn the absence of such an approved ruling I claim that this is a poor\nrules trivia question--since it cannot be authoritatively answered.',
 "being a mere female, I have often found I can't really take the big offensive line with asshole car drivers, so I found a more subtle and nastly\nooops I mean nasty way to get back at them. If somebody cuts you up, just wait till they have pulled out past you, and then gently lean over and\nbend their aerial, every time I have done that it has eventually snapped\noff near the base - which tends to go undetected for a while and is a bummer to replace.\n",
 "I'm writting letters to my Congresscritters and was wondering if\n there is any reason(s) why I should NOT support the following\n Bills, other than the previous comments about S.458.  Just checking\n before I mail the letter to make sure I don't support something\n that I really shouldn't.\n\n -----------------\n I strongly SUPPORT the following laws currently being considered in Congress\n as they would either have a positive effect towards reducing crime, or re-\n enforce our Constitutional right under the 2nd amendment.\n\n * S. 441 (Campbell)\tTo amend title 18, United States Code, to provide a\n\t\t\tmandatory minimum sentence for the unlawful possession\n\t\t\tof a firearm by a convicted felon, a fugitive from\n\t\t\tjustice, a person who is addicted to, or an unlawful\n\t\t\tuser of, a controlled substance, or a transferor or\n\t\t\treceiver of a stolen firearm, to increase the general\n\t\t\tpenalty for violation of Federal firearms laws,\n\t\t\tand to increase the enhanced penalties provided for the \n\t\t\tpossession of a firearm in connection with a crime of \n\t\t\tviolence or drug trafficking crime, and for other\n\t\t\tpurposes.\n\n * S.458  (Smith) \tTo restore the second Amendment Rights of all Americans.\n\n * S.488  (Specter)\tTo provide Federal penalties for drive-by shootings.\n\n * S.504  (Kohl)\tTo amend section 924 of title 18, United States Code to\n\t\t\tmake it a Federal crime to steal a firearm or explosives\n\t\t\tin interstate or foreign commerce.\n\n\n                                Bill Vojak\n                                vojak@icebucket.stortek.com\n\t\t\t\tNRA, ILA,\n                                Colorado Firearms Coalition\n-----------------------------------------------------------------\n Here's a story, bout a man named Brady, who took a .22 bullet\n in his head.  Even though he can act perfectly normal, he\n prefers to pretend he's brain dead.\n\n Here's a story, bout a woman named Brady, who had nothing to\n do but sit around all day.  Then her husband became a media\n martyr, now she wants to take all your guns away.\n\n The Brady Bunch, The Brady Bunch, This is how we got stuck\n with the Brady Bunch. . . . .",
 ": \n:   Nut or not, he was clearly a liar.  He said he would surrender after\n:   local radio stations broadcast his message, but he didn't.  Then he\n:   said he would surrender after Passover, but he didn't.\n: ",
 "I'm looking for a better method to back up files.  Currently using a MaynStream\n250Q that uses DC 6250 tapes.  I will need to have a capacity of 600 Mb to 1Gb\nfor future backups.  Only DOS files.\n\nI would be VERY appreciative of information about backup devices or\nmanufacturers of these products.  Flopticals, DAT, tape, anything.  \nIf possible, please include price, backup speed, manufacturer (phone #?), \nand opinions about the quality/reliability.\n\nPlease E-Mail, I'll send summaries to those interested.\n\nThanx in advance,",
 "\nDo you have Weitek's address/phone number?  I'd like to get some information\nabout this chip.\n",
 "The Microsoft Windows Device Driver Kit (DDK) documentation (blurb)\nstates that the user must separately acquire the Microsoft Windows\nSoftware Development Kit (SDK), which contains the Windows tools\nto build the drivers. If we are using Borland C++ with Application\nFrameworks, is this necessary? We also have a copy of the Microsoft\nPress Programmer's Reference Library (books) which normally comes\nwith the SDK, and Microsoft Macro Assembler 6.0. Why is the SDK\nneccessary for development of Virtual Device Drivers?",
 'Ugliest swing..I am not sure. I think the ugliset stance is\nJolio Franco of the Ranger. I wonder how that bat comes around in time\nto hit the ball. It looks bad but hey.it get the job done. ',
 "\nGeez, what happened?  She got a ticket for driving too slow???\n\n\nOh, are you saying you're not an edu.breath, then?  Okay.\n",
 'ites:',
 '\n\t...or centerstands, or weasel squeezers, or ....\n\nLater,',
 'I participated in a promotion by a company called Visual Images.\nI attempted to cancel my order before the package arrived. I was\nnot able to stop them and now I have a package which I do not need.\n\nNishika 3D camera, wide angle flesh, film, carring case, instruction\ntapes, and some jewelrys.\n\n3 vacation vouchers to Bahama, Cancun, Las Vegas, Orlando.\n\nI paid $697 for the promotion package, and the vacation vouchers\ncame as gift. I really want to sell them, so make me an offer for\nthe whole package. If you are participating in a award, $697 is how\nmuch you would end up paying. And I strongly believe that you would\nget the same award as I do. If you are interested in those items,\nyou could get them from me for a cheaper price.\n\nLet me know, and make me an offer. No flames please, I have got enough.\n\nYou could reach me at koutd@hirama.hiram.edu',
 "\nActually, the story goes that Lucifer refused to bow before MAN as \nGod commanded him to.  Lucifer was devoted to God.\n\nOh yeah, there is nothing in Genesis that says the snake was anything\nmore than a snake (well, a talking one...had legs at the time, too).\n\nI don't think pointing out contradictions in STORIES is the best way\nto show the error in theology:  if they think a supernatural entity\nkicked the first humans out of paradise because they bit into a\nfruit that gave them special powers...well, they might not respond\nwell to reason and logic.  :^)",
 '\nTwo safeguards:\n\n1. The FBI could be asked to produce the law enforcement block to the escrow\nagencies, and associate it with a particular court order;\n\n2. If the thing comes to trial the defense attorneys can probe this issue\nclosely. It is not too different from proving that the speaker on a legal\nwiretap is the person the court order covered.\n\nPutting it another way, this question is not very different from the\npre-clipper question "What\'s to prevent the FBI from getting a court order\nto tap Al Capone and then using it to tap Jonathan Livingstone Seagull\ninstead?"\n\nDavid',
 '\nWhy all the quote marks, Roy?  I can see that they might be appropriate where\nthere is a legitimate concern that the words are being distorted by context, \nor that they have been appropriated Newspeak-style, but, reading your comments above,\none might be excused if they assumed that you were claiming that "child abuse",\n"forced" sexual activity, and "damage" caused by this is non-existant or\ngreatly overblown.\n\n"Positive experiences", indeed!\n\n-Paul Elliott\n(Member in good standing of the Optilink Mafia)\n\n\n',
 "Hi there, I can't seem to get mail to you. Can you tell me your entire\nadress, or even your dotted decimal address?\n\n   (ie. 131.202.3.10)\n\n   Thanks,\n           rocket@calvin.cs.unb.ca \n\n-- ",
 'Ah yes, I see a few liberal weenies have come out of the woodwork\nto defend the burning of the children. Probably drooled all over themselves\nwhile watching the TV coverage.\n\nProbably had a few like that in Nazi Germany, as well.',
 '\nNot to mention that the G-men believed the children didn\'t have gas masks.\n\nBut that was not, with respect to the children, the point of the gassing.\nThe feds *knew* that the children\'s health would be in danger and proceeded\nunder the assumption that the "motherly instinct" of the Davidian women\nwould remove them from harm\'s way. I busted a gut on that one.\n\nSomeone else on the net observed that the administration\'s appeal to a\nwoman\'s "motherly instinct" would never wash with feminists and liberals\nif a republican were in the White House. I say that such an justification\ncould *only* come from a feminist mindset. \n\nBTW - I\'d read in the paper yesterday that the type of gas used was CS2.\nThe paper didn\'t provide any specifics about it.',
 '\nRemember the armor of God?  The sword that Christians wield is the\nWord of God, the Bible.\n\nGod be with you,\n\nMalcolm Lee  :)\n',
 "\nJulie, it doesn't necessarily follow that you should use it (MSG or\nsomething else for that matter) simply because you are not allergic\nto it. For example you might not be allergic to (animal) fats, and\nlike their taste, yet it doesn't follow that you should be using them\n(regularly). MSG might have other bad (or good, I am not up on \nknowledge of MSG) effects on your body in the long run, maybe that's\nreason enough not to use it. \n\nAltho' your example of the ulcer is funny, it isn't an\nappropriate comparison at all.",
 "I've been running a daily summary of the Randy Weaver/Kevin\nHarris trial from here in Boise.  These summaries are sent\nprimarily to mailing lists.  However, I was wondering if\npeople would be interested in seeing them here.  Post or\nemail.\n\nDrew ",
 "\n\n\nYou should read the history. It was Hoover who stopped Nixon's COINTELPRO\ndead in its tracks because he said it was unconstitutional. They tried to\nget around him every way they could.\n\nDespite other things he may have done, for this alone, Hoover saved the\nConstitution.\n\nDavid\n",

In [270]:
test_c

["From: payne@crl.dec.com (Andrew Payne)\nMessage-ID: <1993Apr20.004418.11548@crl.dec.com>\nOrganization: DEC Cambridge Research Lab\nDate: Tue, 20 Apr 1993 00:44:18 GMT\n\n\nDoes anyone know if a source for the TCM3105 modem chips (as used in the\nBaycom and my PMP modems)?  Ideally, something that is geared toward \nhobbyists:  small quantity, mail order, etc.\n\nFor years, we've been buying them from a distributor (Marshall) by the\nhundreds for PMP kits.  But orders have dropped to the point where we can\nno longer afford to offer this service.  And all of the distributors I've\nchecked have some crazy minimum order ($100, or so).\n\nI'd like to find a source for those still interested in building PMP kits.\nAny suggestions?\n\n-- \nAndrew C. Payne\nDEC Cambridge Research Lab\n---\n . R110B:Wnet HAL_9000\n                                                                                                                             ",
 '\nThat includes suicides.  Since it has been shown in other countries that\nsuicide rates are pretty much independent of the means available for\ndoing oneself in (studies include some done/published in Japan, Canada,\nAustria, Norway), suicides ought not be included in the count.\n\nIf this is done, the number of vehicle-related deaths greatly exceeds that\nof firearms-related deaths in Texas.\n\n\nCertainly not.\n\n\nWhy?  Unless it\'s doing something that directly hurts someone else, what\'s\nthe point?  (Otherwise, you\'d better stop operating all motor vehicles, since\nthe price of operating them *greatly* exceeds the cost in lives of firearms.\n\n\nWEll, it\'s been done at least twice.  South (North?) Carolina did it a few\nyears back...and watched its crime rate relative to the rest of the country\nrise quite a bit.\n\nVirginia just passed the law...no word yet on what the results will be, but\nI\'d be willing ot bet that a reduction in crime rates won\'t be one of them.\n\n\nSelf-defense doesn\'t "inflict" on other people (except perhaps the criminal\nwho\'s tried to do you damage, and maybe indirectly on future potential victims\nwho might not become victims).\n\n\n\n-- ',
 "Sounds as though his heart's in the right place, but he is not adept at\nexpressing it.  What you received was _meant_ to be a profound apology.\nApologies delivered by overworked shy people often come out like that...\n",
 "HELP!!!\nmy wife has informed me that she wants a convertible for her next car.\nWe live in South Fla., so we are definitely in the right are for one.\nMy wife has mentioned the Miata, but I think it is too small.\nI would like to wait for the new Mustangs ( Dec. '93 I think).\nAnyone have any opinions on any/all convertibles in a reasonable price range.",
 "\n<looking around>  Who?  Where?\nDon't look at me.  I want to send aid to Russia.  Many other\nconservatives do as well.  ",
 'I am looking for information on infra red based position encoders.\n\nThe idea would be to bounce the infrared source off a wall and the device would\nread out the distance.\n\npreferable it would be rs-232 addressable.\n\n\n\nAny leads?\n\n',
 'I assume that can only be guessed at by the assumed energy of the\nevent and the 1/r^2 law.  So, if the 1/r^2 law is incorrect (assume\nsome unknown material [dark matter??] inhibits Gamma Ray propagation),\ncould it be possible that we are actually seeing much less energetic\nevents happening much closer to us?  The even distribution could\nbe caused by the characteristic propagation distance of gamma rays \nbeing shorter then 1/2 the thickness of the disk of the galaxy.\n\nJust some idle babbling,\n-- \n\n   Jim Batka  | Work Email:  BATKAJ@CCMAIL.DAYTON.SAIC.COM | Elvis is\n              | Home Email:  JBATKA@DESIRE.WRIGHT.EDU      |   DEAD!',
 "\nSorry, but *neither* 'dictates' the cost. It's a negotiation.\nWhether it's up front at a honda dealership in an all out \ndickering war, or more removed on a larger economic scale\n(ie, if saturn can't sell at it's price, the price drops,\nor the company stops building them), it remains a negotiated\nvalue controlled by market forces. To think that the consumer \ncontrols price is ludicrous. If the consumer controled\nprice, then cars would be *free*...And no one would build \ncars.\n\nRegards, Charles",
 "\nHMMM... that brings up a neat idea.  \n\nUnfortunately, it's SOOO neat, I think I ought to patent it.\n\nSo I can't tell you about it.\n\nSorry.  :-)\n\n\t-Bill\n\nCopyright 1993 William S. Yerazunis (aka Crah the Merciless)\nAll rights reserved, no responsibility taken.",
 "In response to: Whitten@Fwva.Saic.Com (David Whitten):\n\n\n\nAnd you responded:\n\n\nOf course.  The feast WAS the Seder, and the accounts of it are very clear\non this point.\n\nThe difference is the connection between the bread and wine and the body\nand blood of god.  This is an old association of the Tammuz/Osiris/Mithras\nline, and not really related to Judaism.  In any case, I didn't really\nintend to argue the point.  I saw a possible association and pointed it\nout, but I haven't the foggiest notion what really happened.\n",
 'Hi I am a Sociology student and I am currently researching into \nyoung offenders.  I am looking at the way various groups of \nchildren are raised at home.  At the moment I am formlulating \ninformation on discipline within the Christian home.\n\nPlease, if you are a parent in this catagory can you email me \nyour response to the following questionaire.  All responses \nwill be treated confidentially and will only be used to prepare \nstats.\n\n1.  Ages & sexes of children\n\n2.  Do you spank your kids?\n\n3.  If so how often?\n\n4.  Do you use an implement to spank with? \n\n\n5. If you do not spank, what method of discipline do you use?\n\n6.  Your age?\n\n7.  Your location\n\n8.  While under the age of 16 did you ever commit a criminal \noffence?\n\n9.  How ere you disciplined as a kid\n\n\nThank you in advance for any reply you can make.  Please e-mail \nyour replies rather than post them on the newsgroup',
 '\n\nI have got an Adaptec SCSI card, that comes with its own version of FDISK.\nThe problem with DOS is that it will only see two hard disks, any more need to be\ndone by device drivers.\n',
 '\n\nWell, I\'ve provided examples to show that the trend was general, and you\n(or others) have provided some counterexamples, mostly ones surrounding\nmating practices, etc.  I don\'t think that these few cases are enough to\ndisprove the general trend of natural morality.  And, again, the mating\npractices need to be reexamined...\n\n\nNo, but mating practices are a special case.  I\'ll have to think about it\nsome more.\n\n\nIndeed.  But, while the natural system is objective, all objective systems\nare not the natural one.  So, the terms can not be equated.  The natural\nsystem is a subset of the objective ones.\n\n\nI don\'t claim that homosexuality is immoral.  It isn\'t harmful, although\nit isn\'t helpful either (to the mating process).  And, when you say that\nhomosexuality is observed in the animal kingdom, don\'t you mean "bisexuality?"\n\n\nThis is standard jargon.  Read any textbook.  The "we" forms are used\nthroughout.\n\n\nThat\'s right.  The goals themselves aren\'t inherent.\n\n\nYou could, but such would contradict observations.\n\n\nBut a postulate is something that is generally (or always) found to be\ntrue.  I don\'t think your postulate would be valid.\n\n\nYes, and I think the goals of survival and happiness *do* work.  You think\nthey don\'t?  Or are they not good goals?',
 '...\n\n\tNearly all of them.  Witness LA>  Firemen are among our real\n\theroes most of the time.  I wonder when they were actually\n\taasked to come, or if they found out about the fire over the\n\tTV ....\n\n\n\tShot at by whom?  prove it!\n\n\n\tWhen "law" replaces "justice" the system is dying or dead.\n\tNote that we had a small revolution 216 years ago on this\n\tpoint.\n\n\n\tOr perhaps just wait.\n\tOr maybeeven send in a few agents who are Christian to\n\t\tsit down and pray outside the line?  Try affinity\n\t\trather than subversion?\n\n\n\n\tChuckle.  SO would you if someone points a gun at you.\n\tAt that point you can die or live; and if living means\n\tstayng in a building to keep badge carrying nuts off your\n\tkids, I suspect you might as well.\n\nBOTH sides were wrong.\n\n\n\tTry again:  go see the movie Sophie\'s CHoice.\n\tGrow up.\n',
 "\n\n\nI've even seen pictures of an installation where the ham pulled a little \ntrailer behind his car with a 4KW generator, and ran the full legal limit \nwhile mobile. I don't know what his gas mileage was like, though, or \nwhere he found resonators able to stand the gaff.\n",
 '\n\nCNN just claimed he bought 104 "semi-automatic assault rifles".  And\nthey say Koresh wasn\'t god-like...  He managed to buy or build a\ncollection of fully-automatic semi-automatic rifles...  Quite a feat,\nI would say.  ;-)\n\nThey\'re still making charges of "sexual abuse" and such, or course.\nNobody seems to have noticed that the Treasury department has nothing\nto do with sex crimes.  Or maybe the feds have recently instituted a\nTAX on sex crimes...  Yeah, that\'s why the BATF was there, looking for\nunregistered *guns* ("this is my weapon, this is my gun, this is for\nfighting, this is for...").\n\n\nI also heard that they\'re claiming to be cautious because of Koresh\'s\n"heated ammunition stockpile".  I seem to recall that smokeless powder\ntends to decompose at even moderate temperatures.  I would be rather\nsurprised, after a fire of that nature, if *any* of his "stockpile" is\nunexploded, or unburned.\n\n\nI seem to recall that aluminum powder is a common component of\nfireworks...  The folks on rec.pyro could probably tell you.\n\n\nI think *anything* is legal if you have the proper license.  If he had\na "curios and relics" permit, I believe he could legally own\nhandgrenades to go with his launcher.\n\n--\nCharles Scripter   *   cescript@phy.mtu.edu\nDept of Physics, Michigan Tech, Houghton, MI 49931',
 "Sony D-22 portable Diskman forsale\n      \n      Good condition, flawless.\n      \n      Costomer AC adapter : 6v DC power supply ( tested 9v DC)\n       \n       * The factory adapter was tested 12v DC (AC 110v input) at the \n         time I bought it three years ago. When using it, a lot of heat \n         was generated inside the CD machine. Of course I wouldn't use \n         it to risk this baby's life. Maybe that's why so many owners \n         always complain about their portable machine going kaput after \n         a short time usage. \n\n       * 9v DC factory suggested\n      \n      LED display\n",
 "Let's look at the effects of inflation on 1930's superstars' salaries.\n\nI read once that the Babe made $80,000 one year and that was about as good \nas it got for him.\n\nLet's assume he made that in 1928 (I'm not sure of the figures, but I know\nI'm in the ballpark--pun intended). :-)\n\nToday, assuming a 4% yearly inflation rate, which is an understatement if\nnot accurate, his measly $80,000 salary would be worth.\n\nFV = $80,000 x (1+4%)^(1993-1928)\n   = $80,000 x (1.04)^65\n   = just over $1,000,000.\n\nAssuming inflation is average of around 5%.\n\nFV = $80,000 x (1+5%)^65\n   = almost 2,000,000.\n\n(I didn't crunch these numbers beforehand).\n\nThese numbers might lead one to believe that today's players are slightly \noverpaid.  The Babe appears to have made then what today's average to above\naverage players make now.  Perfectly accurate salary, year of salary, and \naverage inflation rate would make this analysis more accurate, but I don`t \nthink I'm off by much.\n\nChop Chop\n\nMichael Mule' \n\n\n",
 '\nGood - now let\'s look at those sections.  They\'ll prove my point.\n\n\nNote that this doesn\'t affect all concealed carry.  (Look after the\nword "except".)  It always helps to read the law before commenting on\nit.\n\nWould a prudent storekeeper carry concealed?  How about someone at\nhome?  Note that both are legal, and a lot of "common" people qualify\nfor one or the other.\n\n-andy',
 'Sorry, I did`nt tell exactly what I need.\n\nI need a utility for automatic updating (deleting, adding, changing) of *.ini files for Windows. \nThe program should run from Dos batchfile or the program run a script under Windows.\n\nI will use the utility for updating the win.ini (and other files) on meny PC`s.  \n\nDo I find it on any FTP host?',
 'The Colorado Daily recently reprinted the Wall Street Journal\'s article\non Paxton Quigley, including the nefarious little paragraph the Journal\ntacked onto the end.  After recieving much assistance from various T.P.G.\ntype folks, I wrote a letter to the editor criticizing this last paragraph,\nand surprise, surprise, surprise, they published it.  The text follows.\nThe Colorado Daily, btw, is the University of Colorado (Boulder) student\n(I think) newspaper... not exactly a big coup, but every little bit, i guess...\n\n(The title was the only thing they changed/added)\n\n"Gun Stats"\n\nThe Daily recently reprinted an article from the\nWall Street Journal, primarily concerned with Paxton\nQuigley, author of "Armed and Female."  The article,\nin turn, cites a misleading statistic that was originally\nreported in the New England Journal of Medicine.  The\narticle states, "A study... found that a gun in the home\nwas 43 times more likely to be used to kill its owner,\nspouse, a friend, or child than to kill an intruder."  This\nis an often-quoted statistic, and it is misleading for sev-\neral reasons, outlined below:\n\nThe study gives the impression that, if you own a \ngun, the likelihood that you will successfully use it to \ndefend yourself is less than that of the gun being turned\nagainst you.  The study, however, fails to take into\naccount cases where a law-abiding citizen uses a gun \nto thwart a crime, without actually killing the perpe-\ntrator.\n\nThe study actually refers to \'acquaintances\' rather\nthan \'friend\'.  This would include the friendly neigh-\nborhood thug who shows up like clockwork, every\nmonth, the second your grandmother cashes her social\nsecurity check.  Possibly an acquaintance, but hardly a\nfriend.\n\nThe NEJM study is based on the immediate dis-\nposition of cases and fails to take into account cases\noriginally filed as homicides that were later ruled to be\nself-defense.  Especially considering the small sample \nsize (396), taking these events into account has a sub-\nstantial effect on the 43:1 ratio quoted.\n\nCriminologist Gary Kleck gives us a slightly dif-\nerent statistic: a gun is 33 times more likely to be \nused, successfully, by a private citizen against an \naggressor than it is to kill anyone at all.  Further, per-\nsons defending themselves from aggression by using a \ngun fare better than those who resist vicimization by\nsome other means, or who offer no resistance at all.\nStatistics available from the FBI and other agencies \nalso show that a gun is 245 times more likely to be\nused by a non-criminal to defend against criminal threat\nthan to be used to commit criminal homicide, 535 times\nmore likely to be used to defend against a criminal\nthreat than to accidentally kill anybody, and 50 times\nmore likely to defend against criminal threat than to be\nused to commit suicide.\n\nIt is well to keep in mind that nearly anything can \nbe proved by uncritical quotation of statistics.  One has\nto consider carefully what questions were asked by\nthose gathering the data before one can draw an accu-\nrate conclusion from them.\n\nD.F. Taylor\nCU Department of Chemistry and Biochemistry\n\n\n--\nSpooksmoke: Revolution, Assasination, Thorium, Cobalt-60, Clintin, CIA, NSA, SHC\n  DoD #202 / loki@acca.nmsu.edu / liberty or death / taylordf@ucsu.colorado.edu \n                 Send me something even YOU can\'t read...\n-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: 2.2',

In [273]:
# transform the partitions
#includes expanding contractions, PoS tagging, Lemmatization,
#special character removal, stopword removal, tokenization

train_ct = transform_corpus(train_c)

test_ct = transform_corpus(test_c)

In [274]:
train_ct

['sorryistilldonotbuyityoubecertainlyrightthattherunnerbenotoutmerelyforrunoutofthebaselinehemustinterferewiththeplaybuttheargumentherebeoverwhatconstituteinterferenceyoucertainlycannotinferfromwhatyouhavequotethatthebatterrunnermustbehitbytheballtobeguiltyofinterferenceyouhavenotpostadefinitionofinterferenceatallimothiscallforoneoftheapproverulesthatgoinsmallprintintherulebooksomethinglikeapprovedrulingifinthejudgementoftheumpiretherunnerbyruntotheleftoftheallowedpathcausethefieldertomakeabadthrowblockthevisionofthefielderreceivethethroworotherwiseimpedethedefensiveteamsmakeaplayonhimthebatterrunnershallbejudegedguiltyofinterferenceorapprovedrulingtherunnercannotbejudgeguiltyofinterferenceintheunlesshemakecontactwithafielderorbehitbythethrownballintheabsenceofsuchanapprovedrulingiclaimthatthisbeapoorruletriviaquestionsinceitcannotbeauthoritativelyanswer',
 'beamerefemaleihaveoftenfindicannotreallytakethebigoffensivelinewithassholecardriversoifindamoresubtleandnastlyooopsimeannastywaytogetbackatthemifsomebodycutyouupjustwaittilltheyhavepulloutpastyouandthengentlyleanoverandbendtheiraerialeverytimeihavedothatithaveeventuallysnapoffnearthebasewhichtendtogoundetectedforawhileandbeabummertoreplace',
 'ibewrittinglettertomycongresscrittersandbewonderiftherebeanyreasonswhyishouldnotsupportthefollowingbillotherthanthepreviouscommentabouts458justcheckbeforeimailthelettertomakesureidonotsupportsomethingthatireallyshouldnotistronglysupportthefollowinglawcurrentlybeconsiderincongressastheywouldeitherhaveapositiveeffecttowardsreducecrimeorreenforceourconstitutionalrightunderthe2ndamendments441campbelltoamendtitle18unitedstatecodetoprovideamandatoryminimumsentencefortheunlawfulpossessionofafirearmbyaconvictfelonafugitivefromjusticeapersonwhobeaddicttooranunlawfuluserofacontrolledsubstanceoratransferororreceiverofastolenfirearmtoincreasethegeneralpenaltyforviolationoffederalfirearmlawandtoincreasetheenhancedpenaltyprovideforthepossessionofafirearminconnectionwithacrimeofviolenceordrugtraffickingcrimeandforotherpurposes458smithtorestorethesecondamendmentrightofallamericans488spectertoprovidefederalpenaltyfordrivebyshootings504kohltoamendsection924oftitle18unitedstatecodetomakeitafederalcrimetostealafirearmorexplosiveininterstateorforeigncommercebillvojakvojakicebucketstortekcomnrailacoloradofirearmcoalitionheresastoryboutamannamebradywhotakea22bulletinhisheadeventhoughhecanactperfectlynormalheprefertopretendhebebraindeadheresastoryboutawomannamebradywhohavenothingtodobutsitaroundalldaythenherhusbandbecomeamediummartyrnowshewanttotakeallyourgunawaythebradybunchthebradybunchthisbehowwegetstickwiththebradybunch',
 'nutornothebeclearlyaliarhesayhewouldsurrenderafterlocalradiostationbroadcasthismessagebuthedonotthenhesayhewouldsurrenderafterpassoverbuthedonot',
 'ibelookforabettermethodtobackupfilecurrentlyuseamaynstream250qthatusedc6250tapeiwillneedtohaveacapacityof600mbto1gbforfuturebackuponlydofileiwouldbeveryappreciativeofinformationaboutbackupdeviceormanufactureroftheseproductflopticalsdattapeanythingifpossiblepleaseincludepricebackupspeedmanufacturerphoneandopinionaboutthequalityreliabilitypleaseemailiwillsendsummarytothoseinterestedthanxinadvance',
 'doyouhaveweiteksaddressphonenumberiwouldliketogetsomeinformationaboutthischip',
 'themicrosoftwindowdevicedriverkitddkdocumentationblurbstatethattheusermustseparatelyacquirethemicrosoftwindowsoftwaredevelopmentkitsdkwhichcontainthewindowtooltobuildthedriverifwebeuseborlandcwithapplicationframeworkbethisnecessarywealsohaveacopyofthemicrosoftpressprogrammersreferencelibrarybookwhichnormallycomewiththesdkandmicrosoftmacroassembler60whybethesdkneccessaryfordevelopmentofvirtualdevicedriver',
 'ugliestswingibenotsureithinktheuglisetstancebejoliofrancooftherangeriwonderhowthatbatcomearoundintimetohittheballitlookbadbutheyitgetthejobdo',
 'geezwhathappenshegetaticketfordrivetooslowohbeyousayyoubenotanedubreaththenokay',
 'ites',
 'orcenterstandsorweaselsqueezerorlater',
 'iparticipateinapromotionbyacompanycallvisualimageiattempttocancelmyorderbeforethepackagearriveibenotabletostopthemandnowihaveapackagewhichidonotneednishika3dcamerawideanglefleshfilmcarringcaseinstructiontapeandsomejewelry3vacationvouchertobahamacancunlavegaorlandoipay697forthepromotionpackageandthevacationvouchercomeasgiftireallywanttosellthemsomakemeanofferforthewholepackageifyoubeparticipateinaaward697behowmuchyouwouldenduppayandistronglybelievethatyouwouldgetthesameawardasidoifyoubeinterestedinthoseitemyoucouldgetthemfrommeforacheaperpriceletmeknowandmakemeanoffernoflamespleaseihavegetenoughyoucouldreachmeatkoutdhiramahiramedu',
 'actuallythestorygothatluciferrefusetobowbeforemanasgodcommandhimtoluciferbedevotetogodohyeahtherebenothingingenesisthatsaythesnakebeanythingmorethanasnakewellatalkonehavelegatthetimetooidonotthinkpointoutcontradictioninstorybethebestwaytoshowtheerrorintheologyiftheythinkasupernaturalentitykickthefirsthumansoutofparadisebecausetheybiteintoafruitthatgivethemspecialpowerwelltheymightnotrespondwelltoreasonandlogic',
 'twosafeguard1thefbicouldbeasktoproducethelawenforcementblocktotheescrowagencyandassociateitwithaparticularcourtorder2ifthethingcometotrialthedefenseattorneycanprobethisissuecloselyitbenottoodifferentfromprovethatthespeakeronalegalwiretapbethepersonthecourtordercoverputitanotherwaythisquestionbenotverydifferentfromthepreclipperquestionwhatbetopreventthefbifromgetacourtordertotapalcaponeandthenuseittotapjonathanlivingstoneseagullinsteaddavid',
 'whyallthequotemarkroyicanseethattheymightbeappropriatewheretherebealegitimateconcernthatthewordbebedistortbycontextorthattheyhavebeappropriatenewspeakstylebutreadyourcommentaboveonemightbeexcuseiftheyassumethatyoubeclaimthatchildabuseforcesexualactivityanddamagecausebythisbenonexistantorgreatlyoverblownpositiveexperienceindeedpaulelliottmemberingoodstandingoftheoptilinkmafia',
 'hithereicannotseemtogetmailtoyoucanyoutellmeyourentireadressorevenyourdotdecimaladdressie131202310thanksrocketcalvincsunbca',
 'ahyesiseeafewliberalweeniehavecomeoutofthewoodworktodefendtheburningofthechildprobablydroolalloverthemselveswhilewatchthetvcoverageprobablyhaveafewlikethatinnazigermanyaswell',
 'nottomentionthatthegmanbelievethechilddonothavegasmaskbutthatbenotwithrespecttothechildthepointofthegassingthefedknowthatthechildshealthwouldbeindangerandproceedundertheassumptionthatthemotherlyinstinctofthedavidianwomanwouldremovethemfromharmswayibustagutonthatonesomeoneelseonthenetobservethattheadministrationsappealtoawomansmotherlyinstinctwouldneverwashwithfeministandliberalifarepublicanbeinthewhitehouseisaythatsuchanjustificationcouldonlycomefromafeministmindsetbtwiwouldreadinthepaperyesterdaythatthetypeofgasusebecs2thepaperdonotprovideanyspecificaboutit',
 'rememberthearmorofgodtheswordthatchristianwieldbethewordofgodthebiblegodbewithyoumalcolmlee',
 'julieitdonotnecessarilyfollowthatyoushoulduseitmsgorsomethingelseforthatmattersimplybecauseyoubenotallergictoitforexampleyoumightnotbeallergictoanimalfatandliketheirtasteyetitdonotfollowthatyoushouldbeusethemregularlymsgmighthaveotherbadorgoodibenotuponknowledgeofmsgeffectonyourbodyinthelongrunmaybethatbereasonenoughnottouseitalthoyourexampleoftheulcerbefunnyitbenotanappropriatecomparisonatall',
 'ihaveberunadailysummaryoftherandyweaverkevinharristrialfromhereinboisethesesummarybesendprimarilytomaillisthoweveribewonderifpeoplewouldbeinterestedinseethemherepostoremaildrew',
 'youshouldreadthehistoryitbehooverwhostopnixonscointelprodeadinitstrackbecausehesayitbeunconstitutionaltheytrytogetaroundhimeverywaytheycoulddespiteotherthinghemayhavedoforthisalonehooversavetheconstitutiondavid',
 'herebethefinalstadingsfortheusenethockeydraftcongratulationtothisyearswinnerdavewesselsofvictoriabcwhoparlayhisinitial1000pointinto15759pointthankstoall262teamforenterthebiggestusenethockeydrafteverihopetohearfromyouallagainthisseptemberforthe7thannualdraftithavebemypleasurerunthedraftandihopeyouallhavefunandrewusenethockeydraftstandingweek28posnteamtotalptcashlastposn1davewessels1575915741912gillescarmel153901538103bobhill15390151524024seppokemppainen15152146847245theawesomeoiler15130145868656hillsideraider1503014967067maktheknifeparanjape15000146931078janstein14923145735389thisyearmodel148861471176910tapiorepo1486614671961011rangerofdestiny1486014444201012theunderachiever1459114491011313franksbigfish1457014352201214goflames1448314084031515onthinice1444314123231416moparmusclemen144171438371717littlestgiant1439614043561618lindrosloser142771426171819diepenguinbandwaggoners1412213922021920samuellaucalgaryalberta140191397492021boomersboy137421374022122delawarewombats137231371132323generalaccountingoffice1365913452092224migodsmenschen1365613343162425wellsysbuttheadsdecnh1363613115262526fifeflyer1356413253142727rockymountainhigh135281351182628davesnell1346013212502929fluideglacial1341013231803030geraldolchowy1337713043372831gaoler1317213061123132smegheads131631316033233neuralnetters1309312981133534theyoungandtheskateless1307912654293335samhisdog1297612861163436articstorm1293312543933737youngbucs12930123810173638softswede1284912384693839simmonac1280812602084640miltonkeynesking127181269284041jeffhorvath126661261563942legionofhoth1265812501584543lefleurdelys1264312392534344yanthemanloke126371263074445kuehncrusher1258112134514146hamsterfromhoboken125471246874147streak1249811955484948brianbergman1249312262335049thefinnishforce1248512262254750grantmarven123991237295351icelegion1239812112884852goaldingers1237012152205153tcoverachiever123191229295254randycoulman122621221526255bozrahbruins1225211804525456skrikowolves122341218545757buffalosoldier1223011686215958houdinismagician1221312031835659stevenandmarkdreamteam121911216316460realbadtoejam1216911684895561recsporthockeychoice121631215135862bemybaby1216211625426063lamplighter121391208596364lippe1212911991396165philandkevskarmadude120581205086966dougbowles1203011832007267bloomcountyallstar120231198436768tom1202111891316669indianapolisbennies1197811772086570bruin119611196016871smithw1195011742107072aikexile1188511543457773iowahockeyes1188311721637174frankworthless118631180637675thegreatpumpkin1183411295447376non1182411661647477shootseaman118011180017578invisibleinc117811177117879bradgibson1174211472727980cougarmania1170811462488081johnzupancic1170111432718482davidwong1166011116618383garryola116571156978584garybergmanfanclub1163111585186staffanaxelsson1163111481518786kortelaisenkovat11580110316418187chocolaterocket115451152259088plpfool115311153018289thekamucks1152010977619790chubbychecker11503113416388kodiak115031149139392derrillsdastardlydozen1150111282218993kendecruyenaere114701142509194fisherdirtbags114671146079295neilyounger11452113114210696bscoranienburg114411137719697nonamer1138010835829498arsenalmapleleaf113781134389899thecampimachine11370108265395100mombasamosquito11311112561100101bjoernleaguen11300112730103102elliislanders1123611167699103zachmanswingers112281073498101104kingsuke11201112001108105larry111681105118109106votenooct26111581084318111107bloodgamers111511073421112hetschotishard111511097181110109hurricaneandrew11146110776107110dirtywhitesock111441071434104111wormtownwoosbags111401059726105112brucesrentedmule111191100119112113oklahomastormchasers111131083283116114teemkanada111101095160114115edelweiss11109110829102116franksfolly111021086242115117pondslime11097110907118118spud110861096126117119psvdartmouth10971109071119120kokudokeikakubunny109631056403124121bluetalon109531082133121122stanfordicehawk109421066282122123timoojala10883108803125124marksander108811077111120125ayecarumba10879108439123126dirtyrottenpucker10872108612128127garyteam108711070171133128clusterbuster10846107776127129haral10833107673126130apricotfuzzfaces108131058233129131garybillpendynasty107861059196132132seattlepftb107791055229135133nesbitt10771107611131134thelostpoots10767107067130135legroupemi107621046302137136arcticcircle107561038376134137latenightwithdavidletterman10740107400136138wembleylostweekenders10713107103145139wildheartedson10689106449143140dreehobbs106641053134149141closetboysboy106601018480142142scottglenn106521055102139143gobruin10642105862138144andyyfwong106351042215145bookemdannosbushbaby106351053105148146mckeesrockrocker10621105751147147boutch9293106201042200144148teamgold106071044167141149goddessoffermentation105621026302151150convexstar10556105056153151flykiwi10551104691140152einsteinsrockband10540105400154153drjoelfleishman10537105037165154timrogers10531104581152155myteam105309981748159156tap10525105205156157sundog10524105204166158butterwaffle105201006460157159gohabsgo10510104380150160princetoncanuck105009951242155161hubertshockeyhomeboy10496104906157162satanschoice104751033145164163bobsblue104681000468160164lenordiques10450990604162165pierremailhot10446104226167166furleysfury10416103836161167slapshotmarco10398988518168168huntercollector10384996424162169thedreamer10380983637173170sanjosemahimahi103681005318169171jeffnimeroff10348986488171172eastcityjoker10340979691174173theleafrule103381008258170174darsebilling10337999347178175flower103309781136177176darylturner10304102824175177lanainc103031003273180178ridthepine102871008207176179spinaltap10274986414181180stimpyadgzeta102701006210172181chappelschump102401000240179182bigbadbruins102351005185184183enforcer10221994281183184mikemaccormacksydneyncan102209671072186jimparker102209671790182186bulldog10204997234187187yellowplague101921005142195188jeffbachovchin10187972467184189absolutlehigh10179100989189190voyageurs10157101327188191republicandirtytrickster10100955660190192ninjaturtle10093100813196193drdandthesod10091992171192194henrysbarbq10087100807191195bunchofmisfit10078984238193196robynsteam10070977300194197cobraskiller10067975317202198cherrybomber10052100412203199kutapapercuts10035985185200200greatexpectation998399623201acadien9983980183198202darmansdragon9943966283199203teammelville9939947469197204killerape9903966243205205kaufbeurenicebreakers9886951376206206jaysonskinkypuck9879961269204207rogersmith9876948396208208firebird980997739209209ikeawholesale980797917211210umpire4life9801969111207211those1stfewweekhurt9800925559210212outlaws97509201649212213400hurricane9731941321223214frackattack9723945273219215believeitordont9701949211215216toddsturkey967996619219217thunderherd96609111636214218kneeinjuries9654955104217219the200club962895668213220fredmckim9620907930222221crazyeuro9619944179218222creepdeath9593938213216223ryansrenegade9569906509221224pigvomit953395213224225icestrykers95208971054225daytonbomber952095200228227cdnstuckinalabama9513941103227228fightgeordies95008951416226229cafallandcrew9473909383229230shipsway942793487235231zipperhead9419908339232232chrisofdeath9410886836230233bankosbeerranger940293642232234swillbellies9397921187231235oz9340899350237236laubstersii93108762016236237ninjabunnies9289884449239238greatscott9280873733240239jolietinmates9278882458238240nyflame923891678234241sandyssabre917791347243242widefieldwhitewolves9109874369241243floridatechburghteam9093860493246244theicehole908790627242245southcarolinatigerpaw9030848784245davesteam9030871320244247mudvilleking9006873276250248redliners8989883159252249roadrunner8985880185249250forxtc898289082248251leobluechip8944884104247252newjerseyrob891789107251253patphillips8911881101253254stewartclamen869686816254255demonspawn8680843250255256sunnyvalestorm815281502256257allezlesblue80307484769257258upforsalehockeyclub7850762230258259petespick78307281685259260rinaco78007251140260261brenzrevenge705070140261262dinamoriga65806035716262andrewscottandrewidacomhpcomhpidacomtelecomoperation4034620666ext253',
 'doyoumeantheiconoftheprogramgrouportheiconoftheindividualprogramintheprogramgroupiassumeyoumeanthelatterandtheanswerbesureyoucanjustclickoncenotdoubleontheapplicationiconthenaltfpfilepropertyclickonthechangeiconboxandtellittheiconfilenameorusethebrowsesubselectioniusealttabholdthealtkeyandrepeatedlypresstabuntilyouseeprogrammanglerupthenreleasethealtkey',
 'butofcourseitdoitbecertainlyalegalmatterifitbenotalegalmatterthatinterestyouyoumaysimplyputitinyourkillfile',
 'ultimatelyitrestwithpersonalopinioninmyopinionthequestiondonotmakesensetomemaybeitwouldbebettertoaskwhatmakeademocracybetterthanforexampleatotalitarianregim',
 'notquitetheanswerbemanyhomosexualheterosexualandbisexualbebutthenmanybenotormoresimplylotofpeoplebe',
 'hmmminterstingandlongmessagebuttwicewellidonotcareforlibertarianismbutthatbeaphilisophicaldisagreementnotatacticalonereformofexistlawwouldbeanawfullygoodideayouwouldnotbelievesomeoftheoutrageousthingtheguardianofourtwopartysystemdotoshutoutdissentdavidmatthewdeanedeanebinahccbrandeisedu',
 'thisbequitecorectbutabullethitaburnbodywithlittleenergywillshowvirtuallynodeformationieahollowpointprobablywouldnotexpandanfmjwouldbepristenealsothebulletwillnotbemarkwiththelandanggrooveofabarrelbecausetheydonotcomeoutofoneagoodpathologistshouldbeabletonoticethisrightawayletushopethatthemesthathandlethesebodybemorecompetentthentheonewhodojfksbody',
 'thetwohistoricfactthatithinkthemostimportantbethese1ifjesusdonotrisefromthedeadthenhemusthavedosomethingelseequallyimpressiveinordertocreatetheobservedamountofimpact2nobodyeverdisplaythedeadbodyofjesuseventhoughboththejewishandtheromanauthoritywouldhavegainalotbydosoitwouldhavediscreditthechristian',
 'theyuseatanktoknockaholeinthewallandtheyreleasenontoxicnonflammableteargasintothebuildingnontoxicteargasdoyouknowwhatteargasbeidoonceuponatimeihappentobeinaroomwhensomeonethrowateargasgrenadeinthatbesupposetobeajokethesensationbeincredibleifeltmyeyeandnostrilbebetornapartirememberusabunchofyoungmeninourearly20srunoutlikeaherdofwildanimalknockdownthedoorandjumpoutofthewindowthankgdwebeonthefirstflooricannotimaginethiskindofstuffbeuseagainstchildforthemtheworsteffectmightnotbethephysicaleffectsomuchasthepsychologicaleffectofbeincapacitatewithoutfullyunderstandthecausemanyyearagoibeaccidentallyexposetoatinydoseofteargasitbeinathensonthestreetleadtotheamericanembassytheredbeamarchthathavebebreakupwithteargasimusthavestumbleintoaremainpatchofgasthenextdayasidefromthetearfeelsicktomystomachetcthereallyhorriblepsychologicaleffectbethatofsuddenlyfalltopieceandnotknowwhyithavehappenibehorrifyandwonderwhatdiseaseorotherhealthproblemihaveidonotfindoutaboutthemarchandtheteargastillhourlatericanimaginehowhorriblydisorientthismightbetoveryyoungchildsuddenlycryuncontrollablyandfeelsickweakandoutofcontrolofyourbodyandnotknowthecausethisgiveusachancetotrythegasofpeaceyeahright',
 'iftccutalkpoliticsgunsjrmgnvifasufledu626beapr141993isupposethatdependonhowyoudefinevastmajorityyoubecorrectaboutmajoritysomewherebetween1outofthreeandoneoutof10willatsomeperiodintheirlifeexperienceaviolentassaulttheriskbegenerallyhigherthanemergencymedicalproblemlikeheartattackandstrokevastbeprobablytoolooseatermwithapproximately1000000americanusefirearmeachyearovera30yearperiodwegetroughlysincesomemayhavetodothismorethanonce30millionamericanwithexperienceinusefirearmforselfdefense30250yield12percentofthepopulationyesiknowthatbearealroughestimatewebecloserto270millionnowbutmanyofthesebeminorandshouldbeincludeetcthusthepercentageifanythingbelowatanyratemostminoritygroupinthisrangebenotusuallyrefertoastinyminoritysoidonotseehowtheotherpartofthegroupcanberefertoasthevastmajorityalittlemoreworkmightsupportasimplemajorityofamericanneveruseownordisplayafirearmcertainlywhenyoubetalkaboutownershipyoubewrongnearlyhalfofyourfellowcitizenownoneormorefirearmpleaseprovidealistofothermeanthatbeaseffectivethenyoumightconvinceyourlocalpolicedepartmenttoswitchgoodluck',

In [275]:
test_ct

['frompaynecrldeccomandrewpaynemessageid1993apr2000441811548crldeccomorganizationdeccambridgeresearchlabdatetue20apr1993004418gmtdoeanyoneknowifasourceforthetcm3105modemchipasuseinthebaycomandmypmpmodemideallysomethingthatbegeartowardhobbyistsmallquantitymailorderetcforyearwehavebebuythemfromadistributormarshallbythehundredforpmpkitbutorderhavedroptothepointwherewecannolongeraffordtoofferthisserviceandallofthedistributorihavecheckhavesomecrazyminimumorder100orsoiwouldliketofindasourceforthosestillinterestedinbuildpmpkitanysuggestionandrewcpaynedeccambridgeresearchlabr110bwnethal9000',
 'thatincludesuicidesinceithavebeshowinothercountrythatsuicideratebeprettymuchindependentofthemeanavailablefordooneselfinstudyincludesomedonepublishedinjapancanadaaustrianorwaysuicideoughtnotbeincludeinthecountifthisbedothenumberofvehiclerelateddeathgreatlyexceedthatoffirearmsrelateddeathintexascertainlynotwhyunlessitbedosomethingthatdirectlyhurtsomeoneelsewhatbethepointotherwiseyouwouldbetterstopoperateallmotorvehiclesincethepriceofoperatethemgreatlyexceedthecostinlifeoffirearmwellitbebedoatleasttwicesouthnorthcarolinadoitafewyearbackandwatchitscrimeraterelativetotherestofthecountryrisequiteabitvirginiajustpassthelawnowordyetonwhattheresultwillbebutiwouldbewillingotbetthatareductionincrimeratewillnotbeoneofthemselfdefensedonotinflictonotherpeopleexceptperhapsthecriminalwhobetrytodoyoudamageandmaybeindirectlyonfuturepotentialvictimwhomightnotbecomevictim',
 'soundasthoughhisheartsintherightplacebuthebenotadeptatexpressitwhatyoureceivebemeanttobeaprofoundapologyapologydeliverbyoverworkedshypeopleoftencomeoutlikethat',
 'helpmywifehaveinformmethatshewantaconvertibleforhernextcarweliveinsouthflasowebedefinitelyintherightbeforonemywifehavementionthemiatabutithinkitbetoosmalliwouldliketowaitforthenewmustangdec93ithinkanyonehaveanyopiniononanyallconvertibleinareasonablepricerange',
 'lookaroundwhowheredonotlookatmeiwanttosendaidtorussiamanyotherconservativedoaswell',
 'ibelookforinformationoninfraredbasepositionencoderstheideawouldbetobouncetheinfraredsourceoffawallandthedevicewouldreadoutthedistancepreferableitwouldbers232addressableanylead',
 'iassumethatcanonlybeguessatbytheassumedenergyoftheeventandthe1r2lawsoifthe1r2lawbeincorrectassumesomeunknownmaterialdarkmatterinhibitsgammaraypropagationcoulditbepossiblethatwebeactuallyseemuchlessenergeticeventhappenmuchclosertoustheevendistributioncouldbecausebythecharacteristicpropagationdistanceofgammaraybeshorterthen12thethicknessofthediskofthegalaxyjustsomeidlebabblingjimbatkaworkemailbatkajccmaildaytonsaiccomelvisbehomeemailjbatkadesirewrightedudead',
 'sorrybutneitherdictatesthecostitbeanegotiationwhetheritbeupfrontatahondadealershipinanalloutdickerwarormoreremoveonalargereconomicscaleieifsaturncannotsellatitbepricethepricedroporthecompanystopbuildthemitremainanegotiatedvaluecontrolbymarketforcetothinkthattheconsumercontrolpricebeludicrousiftheconsumercontrolpricethencarwouldbefreeandnoonewouldbuildcarregardcharles',
 'hmmmthatbringupaneatideaunfortunatelyitbesoooneatithinkioughttopatentitsoicannottellyouaboutitsorrybillcopyright1993williamsyerazunisakacrahthemercilessallrightreservenoresponsibilitytake',
 'inresponsetowhittenfwvasaiccomdavidwhittenandyourespondofcoursethefeastwathesederandtheaccountofitbeveryclearonthispointthedifferencebetheconnectionbetweenthebreadandwineandthebodyandbloodofgodthisbeanoldassociationofthetammuzosirismithraslineandnotreallyrelatetojudaisminanycaseidonotreallyintendtoarguethepointisawapossibleassociationandpointitoutbutihavenotthefoggiestnotionwhatreallyhappen',
 'hiibeasociologystudentandibecurrentlyresearchintoyoungoffenderibelookatthewayvariousgroupofchildberaiseathomeatthemomentibeformlulatinginformationondisciplinewithinthechristianhomepleaseifyoubeaparentinthiscatagorycanyouemailmeyourresponsetothefollowingquestionaireallresponsewillbetreatconfidentiallyandwillonlybeusetopreparestats1agesexofchild2doyouspankyourkid3ifsohowoften4doyouuseanimplementtospankwith5ifyoudonotspankwhatmethodofdisciplinedoyouuse6yourage7yourlocation8whileundertheageof16doyouevercommitacriminaloffence9howereyoudisciplineasakidthankyouinadvanceforanyreplyyoucanmakepleaseemailyourreplyratherthanpostthemonthenewsgroup',
 'ihavegetanadaptecscsicardthatcomewithitsownversionoffdisktheproblemwithdobethatitwillonlyseetwoharddiskanymoreneedtobedobydevicedriver',
 'wellihaveprovideexampletoshowthatthetrendbegeneralandyouorothershaveprovidesomecounterexamplemostlyonesurroundmatingpracticeetcidonotthinkthatthesefewcasebeenoughtodisprovethegeneraltrendofnaturalmoralityandagainthematingpracticeneedtobereexaminenobutmatpracticebeaspecialcaseiwillhavetothinkaboutitsomemoreindeedbutwhilethenaturalsystembeobjectiveallobjectivesystembenotthenaturalonesothetermcannotbeequatethenaturalsystembeasubsetoftheobjectiveoneidonotclaimthathomosexualitybeimmoralitbenotharmfulalthoughitbenothelpfuleithertothematingprocessandwhenyousaythathomosexualitybeobserveintheanimalkingdomdonotyoumeanbisexualitythisbestandardjargonreadanytextbooktheweformbeusethroughoutthatberightthegoalthemselvesbenotinherentyoucouldbutsuchwouldcontradictobservationbutapostulatebesomethingthatbegenerallyoralwaysfindtobetrueidonotthinkyourpostulatewouldbevalidyesandithinkthegoalofsurvivalandhappinessdoworkyouthinktheydonotorbetheynotgoodgoal',
 'nearlyallofthemwitnesslafiremanbeamongourrealheromostofthetimeiwonderwhentheybeactuallyaaskedtocomeoriftheyfindoutaboutthefireoverthetvshotatbywhomproveitwhenlawreplacejusticethesystembedieordeadnotethatwehaveasmallrevolution216yearagoonthispointorperhapsjustwaitormaybeevensendinafewagentwhobechristiantositdownandprayoutsidethelinetryaffinityratherthansubversionchucklesowouldyouifsomeonepointagunatyouatthatpointyoucandieorliveandiflivingmeanstaynginabuildingtokeepbadgecarrynutoffyourkidisuspectyoumightaswellbothsidebewrongtryagaingoseethemoviesophieschoicegrowup',
 'ihaveevenseepictureofaninstallationwherethehampullalittletrailerbehindhiscarwitha4kwgeneratorandrunthefulllegallimitwhilemobileidonotknowwhathisgasmileagebelikethoughorwherehefindresonatorabletostandthegaff',
 'cnnjustclaimhebuy104semiautomaticassaultrifleandtheysaykoreshbenotgodlikehemanagetobuyorbuildacollectionoffullyautomaticsemiautomaticriflequiteafeatiwouldsaytheybestillmakechargeofsexualabuseandsuchorcoursenobodyseemtohavenoticethatthetreasurydepartmenthavenothingtodowithsexcrimeormaybethefedhaverecentlyinstituteataxonsexcrimeyeahthatbewhythebatfbetherelookforunregisteredgunthisbemyweaponthisbemygunthisbeforfightthisbeforialsohearthattheybeclaimtobecautiousbecauseofkoreshsheatammunitionstockpileiseemtorecallthatsmokelesspowdertendtodecomposeatevenmoderatetemperatureiwouldberathersurprisedafterafireofthatnatureifanyofhisstockpilebeunexplodedorunburnediseemtorecallthataluminumpowderbeacommoncomponentoffireworkthefolkonrecpyrocouldprobablytellyouithinkanythingbelegalifyouhavetheproperlicenseifhehaveacurioandrelicpermitibelievehecouldlegallyownhandgrenadestogowithhislaunchercharlesscriptercescriptphymtuedudeptofphysicmichigantechhoughtonmi49931',
 'sonyd22portablediskmanforsalegoodconditionflawlesscostomeracadapter6vdcpowersupplytest9vdcthefactoryadapterbetest12vdcac110vinputatthetimeibuyitthreeyearagowhenuseitalotofheatbegenerateinsidethecdmachineofcourseiwouldnotuseittoriskthisbabyslifemaybethatbewhysomanyowneralwayscomplainabouttheirportablemachinegokaputafterashorttimeusage9vdcfactorysuggestleddisplay',
 'letuslookattheeffectofinflationon1930ssuperstarsalaryireadoncethatthebabemake80000oneyearandthatbeaboutasgoodasitgetforhimletusassumehemakethatin1928ibenotsureofthefigurebutiknowibeintheballparkpunintendtodayassumea4yearlyinflationratewhichbeanunderstatementifnotaccuratehismeasly80000salarywouldbeworthfv80000x141993192880000x10465justover1000000assumeinflationbeaverageofaround5fv80000x1565almost2000000idonotcrunchthesenumberbeforehandthesenumbermightleadonetobelievethattodaysplayerbeslightlyoverpaythebabeappeartohavemakethenwhattodaysaveragetoaboveaverageplayermakenowperfectlyaccuratesalaryyearofsalaryandaverageinflationratewouldmakethisanalysismoreaccuratebutidontthinkibeoffbymuchchopchopmichaelmule',
 'goodnowletuslookatthosesectiontheywillprovemypointnotethatthisdonotaffectallconcealedcarrylookafterthewordexceptitalwayshelptoreadthelawbeforecommentonitwouldaprudentstorekeepercarryconcealhowaboutsomeoneathomenotethatbothbelegalandalotofcommonpeoplequalifyforoneortheotherandy',
 'sorryidonttellexactlywhatineedineedautilityforautomaticupdatingdeleteaddchangeofinifileforwindowtheprogramshouldrunfromdobatchfileortheprogramrunascriptunderwindowiwillusetheutilityforupdatethewininiandotherfileonmenypcsdoifinditonanyftphost',
 'thecoloradodailyrecentlyreprintthewallstreetjournalsarticleonpaxtonquigleyincludethenefariouslittleparagraphthejournaltackontotheendafterrecievingmuchassistancefromvarioustpgtypefolkiwritealettertotheeditorcriticizethislastparagraphandsurprisesurprisesurprisetheypublishitthetextfollowthecoloradodailybtwbetheuniversityofcoloradoboulderstudentithinknewspapernotexactlyabigcoupbuteverylittlebitiguessthetitlebetheonlythingtheychangedaddedgunstatsthedailyrecentlyreprintanarticlefromthewallstreetjournalprimarilyconcernwithpaxtonquigleyauthorofarmedandfemalethearticleinturnciteamisleadingstatisticthatbeoriginallyreportinthenewenglandjournalofmedicinethearticlestateastudyfindthataguninthehomebe43timemorelikelytobeusetokillitsownerspouseafriendorchildthantokillanintruderthisbeanoftenquotedstatisticanditbemisleadforseveralreasonoutlinebelowthestudygivetheimpressionthatifyouownagunthelikelihoodthatyouwillsuccessfullyuseittodefendyourselfbelessthanthatofthegunbeturnagainstyouthestudyhoweverfailtotakeintoaccountcasewherealawabidingcitizenuseaguntothwartacrimewithoutactuallykilltheperpetratorthestudyactuallyreferstoacquaintancesratherthanfriendthiswouldincludethefriendlyneighborhoodthugwhoshowuplikeclockworkeverymonththesecondyourgrandmothercashhersocialsecuritycheckpossiblyanacquaintancebuthardlyafriendthenejmstudybebaseontheimmediatedispositionofcaseandfailtotakeintoaccountcaseoriginallyfileashomicidethatbelaterruletobeselfdefenseespeciallyconsiderthesmallsamplesize396taketheseeventintoaccounthaveasubstantialeffectonthe431ratioquotecriminologistgarykleckgiveusaslightlydiferentstatisticagunbe33timemorelikelytobeusesuccessfullybyaprivatecitizenagainstanaggressorthanitbetokillanyoneatallfurtherpersondefendthemselvesfromaggressionbyuseagunfarebetterthanthosewhoresistvicimizationbysomeothermeanorwhooffernoresistanceatallstatisticavailablefromthefbiandotheragencyalsoshowthatagunbe245timemorelikelytobeusebyanoncriminaltodefendagainstcriminalthreatthantobeusetocommitcriminalhomicide535timemorelikelytobeusetodefendagainstacriminalthreatthantoaccidentallykillanybodyand50timemorelikelytodefendagainstcriminalthreatthantobeusetocommitsuicideitbewelltokeepinmindthatnearlyanythingcanbeprovebyuncriticalquotationofstatisticonehavetoconsidercarefullywhatquestionbeaskbythosegatherthedatabeforeonecandrawanaccurateconclusionfromthemdftaylorcudepartmentofchemistryandbiochemistryspooksmokerevolutionassasinationthoriumcobalt60clintinciansashcdod202lokiaccanmsuedulibertyordeathtaylordfucsucoloradoedusendmesomethingevenyoucannotreadbeginpgppublickeyblockversion22',

In [276]:
# extract features

## bag of words features

# using bow_extractor function to build vectorizer and get features for training dataset
vectorizer_tr, features_tr = bow_extractor(train_ct)

# get features for test dataset
features_te = vectorizer_tr.transform(test_ct)

## tfidf features

# using tfidf_extractor function to build vectorizer and get features for training dataset
vectorizer_tr1, features_tr1 = tfidf_extractor(train_ct)

# get features for test dataset
features_te1 = vectorizer_tr1.transform(test_ct)

In [277]:
# tokenize documents

train_tkn = [nltk.word_tokenize(text) for text in train_ct]

test_tkn = [nltk.word_tokenize(text) for text in test_ct]

In [278]:
# evaluation metrics

# define a function to compute evaluation metrics for classification models

from sklearn import metrics
import numpy as np

def get_metrics(actual_labels, predicted_labels):

    print('Accuracy:', np.round(metrics.accuracy_score(actual_labels, predicted_labels), 2))
    
    print('Precision:', np.round(metrics.precision_score(actual_labels, predicted_labels, average='weighted'), 2))
    
    print('Recall:', np.round(metrics.recall_score(actual_labels, predicted_labels, average='weighted'), 2))
    
    print('F1 Score:', np.round(metrics.f1_score(actual_labels, predicted_labels, average='weighted'), 2))

In [279]:
# define a function to build the model using training dataset, then evaluates the model performance on test dataset

def train_predict_evaluate_model(classifier, train_f, train_1, test_f, test_1):
    
    # build model
    classifier.fit(train_f, train_1)
    
    # predict using model
    predictions = classifier.predict(test_f)
    
    # evaluate model prediction performance
    get_metrics(actual_labels=test_1, predicted_labels=predictions)
    
    return predictions

In [280]:
# Building a classifier using support vector machine (SVM)

from sklearn. linear_model import SGDClassifier

svm = SGDClassifier(loss='hinge', max_iter=1000, tol=0.2)

In [282]:
# Support Vector Machine with bag of words features
svm_bow_predictions = train_predict_evaluate_model(classifier=svm,
                                                   train_f=features_tr1,
                                                   train_1=train_1,
                                                   test_f=features_te,
                                                   test_1=test_1)

Accuracy: 0.06
Precision: 0.51
Recall: 0.06
F1 Score: 0.02

C:\Users\bhavi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [284]:
# Support Vector Machine with tfidf features
svm_tfidf_predictions = train_predict_evaluate_model(classifier=svm,
                                                     train_f=features_tr1,
                                                     train_1=train_1,
                                                     test_f=features_te1,
                                                     test_1=test_1)

Accuracy: 0.06
Precision: 0.51
Recall: 0.06
F1 Score: 0.02

C:\Users\bhavi\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [285]:
# classification matrix

import pandas as pd

cm = metrics.confusion_matrix(test_1, svm_tfidf_predictions)

In [286]:
pd.DataFrame(cm, index=range(0,20), columns=range(0,20))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1,0,0,0,0,0,0,0,0,0,226,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,284,0,0,0,0,0,0,0,0,0
2,0,1,4,1,0,0,0,0,0,0,284,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,283,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,273,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,8,0,0,0,0,289,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,5,0,0,0,287,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,2,0,0,292,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,1,0,280,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,293,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,297,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,299,0,0,0,0,0,0,0,0,0
12,0,0,0,1,0,0,1,0,0,0,322,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,272,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,275,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,277,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,259,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,261,0,0,0,0,0,0,3,0,0
18,0,0,0,0,0,0,0,0,0,0,232,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,183,0,0,0,0,0,0,0,0,1

In [287]:
##### End of Session Text mining modeling using NLTK #####